apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      cloudflare_r2:
        type: s3
        url: https://695051d557f576416fd4b96344422c4d.r2.cloudflarestorage.com ## DO NOT TOUCH - THIS IS WORKING
        bucket: ${CLOUDFLARE_R2_BUCKET_PREFIX}-jellyfin
        accessKey: ${CLOUDFLARE_R2_KEY_ID} ## DO NOT TOUCH - THIS IS WORKING
        secretKey: ${CLOUDFLARE_R2_ACESS_KEY} ## DO NOT TOUCH - THIS IS WORKING
        encrKey: ${CLOUDFLARE_R2_ENCRKEY} ## DO NOT TOUCH - THIS IS WORKING
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: cloudflare_r2
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedlue: 30 0 * * *
        transcode:
          enabled: true
          type: nfs
          mountPath: /transcode
          path: /mnt/Applications/apps-configs/jellyfin/transcode
          server: 192.168.30.49
        family-media:
          enabled: true
          type: nfs
          mountPath: /family-media
          path: /mnt/hhd-hc-primary/media/photoprism-original
          server: 192.168.30.49
        movies:
          enabled: true
          type: nfs
          mountPath: /movies
          path: /mnt/hhd-hc-primary/media/data/media/movies
          server: 192.168.30.49
        shows:
          enabled: true
          type: nfs
          mountPath: /shows
          path: /mnt/hhd-hc-primary/media/data/media/shows
          server: 192.168.30.49
    ingress:
      main:
        enabled: true
        hosts:
        - host: jellyfin.${DOMAIN_0}
          paths:
          - path: /
            pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
            - websecure
            middlewares:
            - name: real-ip
              namespace: traefik
          homepage:
            enabled: true
            name: Jellyfin
            description: This is a jellyfin instance
            group: Media
            icon: ""
            widget:
              type: "jellyfin"
              url: "https://jellyfin.hoth.systems"
              key: "${HP_JELLYFIN}"
              enableBlocks: true # optional, defaults to false
              enableNowPlaying: true # optional, defaults to true
              enableUser: true # optional, defaults to false
              showEpisodeNumber: true # optional, defaults to false
              expandOneStreamToTwoRows: false # optional, defaults to true