apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capacitor
  namespace: dashboards  # Adjust to your target namespace
spec:
  chart:
    spec:
      chart: capacitor  # Name of the chart
      sourceRef:
        kind: HelmRepository
        name: capacitor  # Name of the HelmRepository resource
        namespace: flux-system  # Namespace of the GitRepository
  interval: 5m  # Reconciliation interval
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  releaseName: capacitor
  values:
    # Example values override. Adjust based on your needs and chart's values.yaml.
    replicaCount: 2
    image:
      repository: gimlet-io/capacitor
      tag: latest
    ingress:
      main:
        enabled: true
        hosts: 
          - host: capacitor.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          traefik:
            enabled: true
            entrypoints:
              - websecure