apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-simple
  namespace: flux-system
spec:
  releaseName: nginx
  chart:
    spec:
      interval: 2m
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values: {}
