apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: recyclarr
      version: 12.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/recyclarr/recyclarr
      tag: 7.4.0@sha256:619c3b8920a179f2c578acd0f54e9a068f57c049aff840469eed66e93a4be2cf
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
    workload:
      main:
        podSpec:
          initContainers:
            initconfig:
              type: install
              enabled: true
              imageSelector: "image"
              command:
                - recyclarr
                - config
                - create
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              env:
                CRON_SCHEDULE: "@daily"
    portal:
      open:
        enabled: false
    credentials:
      cloudflare_r2:
          type: s3
          url: https://695051d557f576416fd4b96344422c4d.r2.cloudflarestorage.com ## DO NOT TOUCH - THIS IS WORKING
          bucket: ${CLOUDFLARE_R2_BUCKET_PREFIX}-{{ .Chart.Name }}
          accessKey: ${CLOUDFLARE_R2_KEY_ID} ## DO NOT TOUCH - THIS IS WORKING
          secretKey: ${CLOUDFLARE_R2_ACESS_KEY} ## DO NOT TOUCH - THIS IS WORKING
          encrKey: ${CLOUDFLARE_R2_ENCRKEY} ## DO NOT TOUCH - THIS IS WORKING
    persistence:
        config:
            volsync:
                - name: config
                  type: restic
                  credentials: cloudflare_r2
                  dest:
                    enabled: true
                  src:
                    enabled: true
                    trigger:
                      schedule: 30 0 * * *
    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
        ingress:
          # -- Enable an ingress for the code-server add-on.
          enabled: true
          integrations:
            certManager:
              enabled: true
              certificateIssuer: cloudflare
          hosts:
            - host: recyclarr.codeserver.${DOMAIN_0}