apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maintainerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: maintainerr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      data:
          enabled: true
          type: nfs
          mountPath: /opt/data
          path: /mnt/hhd-hc-primary/maintainerr
          server: 192.168.30.49
    image:
      repository: docker.io/jorenn92/maintainerr
      pullPolicy: IfNotPresent
      tag: 2.2.1@sha256:c6a3a886e20e39759014a7bf3d2843068e722d9ec2138ac43acc7a283de92bd0
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    service:
      main:
        ports:
          main:
            protocol: http
            targetPort: 6246
            port: 6246
    portal:
      open:
        enabled: true
    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
        ingress:
          # -- Enable an ingress for the code-server add-on.
          enabled: true
          integrations:
            certManager:
              enabled: true
              certificateIssuer: cloudflare
          hosts:
            - host: maintainerr.codeserver.${DOMAIN_0}
    ingress:
        main:
            enabled: true
            hosts:
                - host: maintainerr.${DOMAIN_0}
                  paths:
                    - path: /
                      pathType: Prefix
            integrations:
                certManager:
                    enabled: true
                    certificateIssuer: domain-0-le-prod
                traefik:
                    enabled: true
                    entrypoints:
                        - websecure
                homepage:
                    enabled: true
                    name: maintainerr
                    description: This is a maintainerr instance
                    group: Media
                    icon: ""
                    widget:
                      type: maintainerr
                      url: https://maintainerr.media.svc.cluster.local