---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor
values:
    service:
        main:
            type: LoadBalancer
            loadBalancerIP: 192.168.30.215
            ports:
                main:
                    port: 80
    ingress:
        main:
            enabled: true
            hosts:
                - host: capacitor.hoth.systems
            tls:
                - hosts:
                    - capacitor.hoth.systems
                  secretName: capacitor-tls
            integrations:
                certManager:
                    enabled: false
                    certificateIssuer: "cloudflare"
                homepage:
                    enabled: false
                    name: ""
                    description: ""
                    group: ""
                    icon: ""
                    widget:
                        type: ""
                        url: ""
                        custom:
                            key: value
                        customkv:
                            - key: some key
