apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:SiHTXZ8H8q5C8i/DxXJHmsT/2ktDht8QGgXodq+hKA30UuqU62mQMlNOdbelzGR/MfS2fYHn1DPj39JvRgSGfzo=,iv:ijx/8Yc7R9MUiRZtMpZL1HlnUlK/P7JQFx4miVGFNfE=,tag:0nU/LF6uZFOWubDMB0tnyA==,type:comment]
    #ENC[AES256_GCM,data:sK5rMIlZ9bZEPyG0F0uOzsH12QyXRvCh7H95Lpl4ROy/xTxaQlWxyHVdrGPjri0HFmQqrx3sVghU9tA/,iv:6vMbXaklk0dC/Je+Pz2Bn+M6sUi5OcqKcN7JU5GwkW0=,tag:FN9okVr07YqwBm3FjkwJ6A==,type:comment]
    VIP: ENC[AES256_GCM,data:wpj6rgW8UUY84g0tjec=,iv:f3cmJYO/g67rcOOFyZmOL4UbiUExQsmA6hn6NQo4ABQ=,tag:BPj6ZQh89xe/4/VvkhImRQ==,type:str]
    #ENC[AES256_GCM,data:u3VXrLOIBsILEaJBjACDvHRdv7IG5SMeUADDboWt8VAOmHA29j0iWA+r,iv:fgmwhHNALMR+28rprw3cxJDbnc3/5XH7N/dt/2+BWQw=,tag:wsSdZMk9j4lR7gy/aONd0A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:cRjFot12fucdfJc11+0=,iv:L33mOXJSLtCo2vxlWP2CdoyQApVjJhXEEiyiR4hy3Hw=,tag:1tphgs+lf/ju6Hig4BmqXw==,type:str]
    #ENC[AES256_GCM,data:XJWtE3qYyqy0p8403DlP9takUgpGn8FdXry1JLYyAbFJMg==,iv:uTkWOydifVL1j8C5bDywEOGngiIqVqSQpfDW3jL3PDA=,tag:7+mTfzM9+Xdy+At+OPvUsw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:cKTfgydcYd3NbrKt,iv:QdzPmYc3hrlbWEEJpUV4bGqD8YvO4i4amn+lTxCd40A=,tag:2rRemFbAWNzHYXiSzHNe3Q==,type:str]
    #ENC[AES256_GCM,data:9PMdR7WasChcrT1Y/xHo9SSmua4YK692EfSTMx5c5mNwN5Qyn2caagiOOa70WXe66fzEazJBVnHOUHe3P9AhZHV19PXYasLP0wTDnqA=,iv:NvFFsLiaRtDooHKZ8xztZdISa7uBsyng7uWB+QRW65I=,tag:6JU6hFX6VwiAlcpxRc3LUQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:g0qYiNqNNOw3XBxjt3OBOcpVeUzoiaCyeoKl,iv:gVSTkXouSeLlOWCTk/hm0UqHtR5LWLfV7rI4sO+Jlq8=,tag:iTMh3YUbNPf1t/7VYBmWxg==,type:str]
    #ENC[AES256_GCM,data:P2fls6Nu91DQ1NGUZHiLXrP7Qcblte8ddOcJW+hu/qw7nV/xgvSPyHgPAhdVX5dR0DrRYUiEma1dCP3LHgiFA2YfOda+yNW5I2YmsiPbCPw=,iv:PYo5nagGZ59Jq7t2z3ubVZ2xeDwK2YZW760vcNQfKrw=,tag:8SFvUEP4/Wd5hsKm/+/Ltw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:rnsNUyy8leqUitYyCQ==,iv:8XFa9W570Pdfl59VOgPkjvOf7gJ/c6g86X+jC0yQdL4=,tag:jBla2AAQZX06Zj+l4nWsyQ==,type:str]
    #ENC[AES256_GCM,data:sCTInNIdm/iUthP4yQnYCD6xKpMNqexT4WlJe52h9Q2Tx+l7RB5LnM8TqZjXNewLehb1CQ7PGOpaGkL46MAp6dpkktc=,iv:hTNkb1nQFUEskq5YuB6P3Kjgy8FQylZoAcMheoneze4=,tag:tLHVEm1MnqIuQJOxOKMuPA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:n90k4alzt0ko9wfwfA==,iv:eTeJL07QZz2rtWUrpr+lRnZ2LHBWgznvXgt0lKeROSs=,tag:D+77uxHIRMBWsRnJcnzWyw==,type:str]
    #ENC[AES256_GCM,data:Ud6OvswbcyUX1YjXlLyNIEvfAkBg+y28nIgLzwzeD+qqiXwBQT+J4cbVhyfkOxMoCn+xXp6H8Sc=,iv:uMZ7fEFJeO+nPRTXZ6ecvId3E9BZmDnJLcCw1d9TjXI=,tag:NYl+qQiDQeLslSx+rkHzmw==,type:comment]
    #ENC[AES256_GCM,data:fW48YXl+IzLOtbTioU6PvMVKqsgusFoPsg==,iv:Ei0irVTvcq4wIaRT00j62C8HhBWzEELe+xeyhJbd9+Q=,tag:bSnEGbDTyomqnThYpbKk+A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:GPJfH7qYXtsMDDRvFodBBLykkTbu2QMxKwA8Ot1MbM07lXCwyAg0A7kdbouoE47Lc0J65g==,iv:nRe9HZEVEcRZ4sQcxsHn5d4zFqKOXx0h2zCAz9XNu5w=,tag:b0aAaeqTimaJrMa6f9oOtw==,type:str]
    #ENC[AES256_GCM,data:xLkSyXeBHfKUG9RALg==,iv:Jw2YUMr3iPbbzZIQ8luxcOLr7Ecb/A8/7Gghcss0QxA=,tag:rV9oQeijcFWgBUCankJGxw==,type:comment]
    PODNET: ENC[AES256_GCM,data:rGHiuG83FMbrkuIQsw==,iv:+pGmRARDSiMx552oyy69R46sUQNJShHjdVgpuxknHgs=,tag:qdpPbmhYv9NZ6/p9mYmnBQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:kPF5wFuLaSvrkTpJ3w==,iv:IWrtuX+qpMHT/VZyqi1x/zUKMUGEXCWvThwSo923h1w=,tag:v8SdM8J+kpA65EDxq99mBA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wns3u9cpkrx6s5t9end3p48xvwrpr3rqcfq336lsmh0nwwj704gqqgh522
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbzcwcDdMMVRGaDZXS0c0
            YnpDMWJtWGVhZjZmTEdobVlpUmY4bGpJYTJVClZDTWl2YkQ3WXQzSzd5ZFVLaml1
            Wk02T0hiWVZlV3RvOWdGZTEzdFBTQWcKLS0tIEhYMkJzVU9ublJXdEJDNmRiRmYw
            eWxqMVpmSnpNMTFNOUFlSVloSGF2a0EKVMxfNHZ9qrvgnPlrqo9IDMdPacomrSvq
            UdOVrBMZChl6gk7Mn7NW7W39IQprVooVPCZy8EBzRLeiOD3Eeub7EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:48:01Z"
    mac: ENC[AES256_GCM,data:I1eH0hzc7txddjJqw82vbopPZP7QNH9oKKr8cOIefAQrmJfEt153/ManaFJ8dJn9/LdBTadj2mfnfxszLNvrnHQLAKjdx8WforxDUctHP7awraSfJSn1MBwp4zJK5FmaZ2eimmznlJTKltBky0mpoAh9vk7jQOK9Ia4HIxAiJI0=,iv:nMPLCHDgafVnnEP6iYLaNIWFsZRV8iCVCbaCnef9DLk=,tag:YyAc9xcPno5+teC5+CQkgw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
