apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Kc5qn74A6CHOsWfy3lEMz33nIzn3wvgNuMbEuhVH75/R3OLW8uiHCa6oCeMI6SbeRoE0La1Gn5T0O+jYBV6faXE=,iv:9WjjQ5mFNhYuaP5z7aOYcigCZRFpgUJmmUvGJL9Q4Ck=,tag:y/2L6T59VEJQET94hbEq5w==,type:comment]
    #ENC[AES256_GCM,data:f5zw6hLisVl082/6EkaVsUXEs4vMl7mmU1XB+EA0qzl5ck9VgnZNOXbzOrU=,iv:v8el13Oea+rTStz5LLNdeqMlxEv2qIxzEULqR5Xt9zc=,tag:u7HibYUGIaVRE13zFLW/Pg==,type:comment]
    VIP: ENC[AES256_GCM,data:n6EdWuKMaFWEjnHOLi0=,iv:RmFZAy9xUEKLNm1m++4Yd23Bkn9bixfH9pIeKjW69cY=,tag:x+ljsBCW4k5DzR2DAnjl1g==,type:str]
    #ENC[AES256_GCM,data:N8ytE0VGAzYqdHAeh0h1xuHxlN/KghBR1y8=,iv:e0mGv2PhUlom8nnxkzk+7oReCr0eNXR1Nl+YuwPQC5g=,tag:dhcYdXDneUk6pGwtdFD5OQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:nH3meNj34kl/uvnw7Wc=,iv:2jqisoNbBNQ9AkbCwTlmPXqee+uldwWLU7tilmS7cls=,tag:AgGKMk0iLHBff+Hfub4f6w==,type:str]
    #ENC[AES256_GCM,data:oUMa1b584/FjyOX7WM0znPUU+WFZlckvZhmv+wFAuSbfYA==,iv:6afiYT0BUrj3748yoG52GZmAI5M+nSHzevnjpQ4q9zw=,tag:uOpmj8ivv6DBeS68rGR27w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:JzwcjQNxdYCSgwjX,iv:Qnpm2OYTacyeNVPcTDYaGFhzz0kGeU32UjTru+utbOM=,tag:Jn77nb+6B4+cg7moYeFUJg==,type:str]
    #ENC[AES256_GCM,data:AqJJZrr4pxGqD3R6P8QgcWVqhIOkvt7PfSzcpm6k10rf/4km4LRPR1FCARNwLhA=,iv:2x9twhXfwYbW0XKmlpmm81U+E9GNvoN0HJaqxJI9D3k=,tag:Z5Du1QX4CIzmnb5AVlxERg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:52UbtJJZLbfx9RrSeIwgLM1aZEs+YVoAI1As8cY=,iv:8o8idJtsxiLicbZLZwEwrD/ps6OK/SiyBflk9wmZ3zk=,tag:gWcGPUNxe01KIECdnHgELQ==,type:str]
    #ENC[AES256_GCM,data:g6mI67T/yExTGaXfY7l1Lw6NBRKBgZeOPjxpdRE1P7BJW9i6ovq+/zUw8aTd3pCLyxdjytuV3EBkVwVlXgr5rIv31a976eaPFG5RM9ninmk=,iv:tPyc8nvCzIZDm+yqV5m3uC8ft4e1998C1f2UdAUlss0=,tag:aoJ/i6bBLPoYq4I4CyqqoA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:yH/HXq9Ud7OazaXiRlM=,iv:iGLQwAXd3bSCTjsClT2Dc9VEPa/RHtVgV6bLEGoLdoc=,tag:K2Vufb1XQrBqKaRhAZUjBQ==,type:str]
    #ENC[AES256_GCM,data:rVQx4RtkfjgYVxcJTYpTyE0CUI6LNxz7GLpEEn3jQneSB1s6uSASmO43lygGHEknMl8P/ma1y7001NQxG+LJxaGuaIs=,iv:P+MniOLie7hxN+l/ZnNj9ZiUWlnEc0U7WffgSl0p/IE=,tag:2kFV48pq72Z0Sdna2wRFmQ==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:CEgIMMHfDG+JKBf21Yk=,iv:bgMk05W//llPGr6QOkadqYJFor/vAjvyZ6d6+zbhcV0=,tag:I8f+9z8QyO32mhsjXwgGkA==,type:str]
    #ENC[AES256_GCM,data:fviSb6NEp5kFcpY/6mvq3Q0tG1vTDwTKL0jTUGbZivAHg2kDBGelkC3Fv3KDdYVPBku3FvqDeZ0=,iv:5IqLgyqiiJ9GaouanBPqlzLrx2paTwKgJKN4gTDQnbg=,tag:Lue4ZvpKxRnscGjhmnCIIA==,type:comment]
    #ENC[AES256_GCM,data:H1nXY7iU++IWxGE9gF54yvfwQNqOM8LtBA==,iv:c8Pg1E1cTuARwkoiBXg8PDgjcuOd6kvn3d4W7mY+UK4=,tag:WdVm7L1u3+Qn+UZMfH+ZNg==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:UTFSH4brqLuHJtYrZQ==,iv:AsCKCBmuj51xEbVF0b9Hj56AGoEyTkNlh9Dz6rutWrg=,tag:CB/P+/wEFfdzLB9AE9Eh5w==,type:comment]
    PODNET: ENC[AES256_GCM,data:Js+bKhUHPzIcK7O0Lw==,iv:TB7TOAj+h7p7l15KXKBX7Ge1ZFqdnozYryk8dwhzWmo=,tag:l2kPV6AYxG4Zd6TPr4R7Pw==,type:str]
    SVCNET: ENC[AES256_GCM,data:51p4RKLLxBO6ZiU/XA==,iv:T2S/cAGN29n+dJVXsh0AO7PztWoLSRGvC9WHY80+yP0=,tag:CWe/FJQhPLpfZV5blXyZug==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wns3u9cpkrx6s5t9end3p48xvwrpr3rqcfq336lsmh0nwwj704gqqgh522
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeVZBdGdVUDZKQVBtNS9D
            VTVZdmt5dTR1ZEFHZDNjTGp6Vm5pQ3RVSUMwClpHYVgyTmpWVk8zb1J3UGVyeHI3
            OFZIL0dCdDZwQkxva0U1NS9jc1dFajgKLS0tIEJEYXVuLzAyZ2VhQ2NTNld2am5U
            cENYZk85bjlTUS82MW5BVnRITTBacW8KW0wOaYQUCaGTVb3ZwhkWobkROi4t65oK
            2n4vV+UlaZLofcRZYxxOMBfK7a9oNIK8RRdyC8p8S/2aS4OdlMv21w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T17:58:22Z"
    mac: ENC[AES256_GCM,data:NP8BQ9yHZ3am5ObUqbgDZAfbnVsbyUUar/CWG2lEoUSeWI3SfcWcOt/6m3U9V84we6vxat7lCsQmaENFKU5u5sBNGwGEM0/0m8V059WPODrvPElUpqeprDhvrbcaiQO4pMHsmzPoeLxhFwECyWZbOh/mbyqxpJFioDqp5KCsJtY=,iv:ndsmZHOoV8zJIftWnHuwYRGH7aPV6ctumbxxT1Qksqo=,tag:3Xe0YfrGfaWqU6/slx6tGA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
