apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:C1dOB6iSfU1X1AQU6KG2BJyvveu1bAKPg00YfxzRji3RXje8+HSHUUYxQi/l4EHd+S2VazuExiyqT5A+rvOMKLg=,iv:ZDtvzW9lK5gheR72XBOyYCnMJQkMWCa4/evtpOLB48M=,tag:Asxabqw4GMFWneeMsf2ADA==,type:comment]
    #ENC[AES256_GCM,data:MN01aGz6FGAGHLz++dH3fUwnoJy2u8eYmCs/tq1F5AHpv2vQGzJ18194YS0=,iv:P27SUHuFNL/sabj9P+IQFkgyPZGhs9SnYVXMkLwXkoc=,tag:sTUbcFZE2wJa/V1aG/+Zng==,type:comment]
    VIP: ENC[AES256_GCM,data:wSwBVNMrXgoh7PGjiA==,iv:Mdrtx4XIvZeXBmJHFwK6jgPIxSVjXw9yQjBKOto6Mbw=,tag:Fwewtu1QjFB8i/+KdlVclA==,type:str]
    #ENC[AES256_GCM,data:G36y2Yy0U62gL6m86UlTerx1FmbZCnMiPhnl,iv:sioPzPTI91Z1D3KXzz0FB2+AeGNHqBWgJ/Mt3r3FZpg=,tag:Aw5TwjTZIGccZMT++F6vCA==,type:comment]
    #ENC[AES256_GCM,data:CsV5llXVsWHD6oIeo2+rmzi2UHVJVpxlJ9MHeQpUBS15kjtYgDSZgwgE/DOgcTKURWtuooHJ7tMA+FetxLj4ZMdstv+e93DcDYbTHCea1NmazaMBVL6vEEs=,iv:uAnMDsqUSgoR2V5v3hzZ79ux6Rnq6WW+M2cPoCgf5p8=,tag:TaSeg1UMyEoSS1NgvXnApw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ScpAwCka1hdfoBlNEw==,iv:8zjZm4TDvBIkVEVEtOeCIPIV1zOobdGHtBXJOOY8LQ0=,tag:16u41EwBjGXC1tuNDQzsQQ==,type:str]
    #ENC[AES256_GCM,data:/DhnT+TcmxdFGSRnlLevCgbcoAuXHhaAfVmm0L42WkK9cA==,iv:F46v0PjCKcr4XjV/daGe5Wi59T4zY1RV3kLUZIUD8P8=,tag:h6ZAiNh0FiMcTV80urSYag==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:iKiJUKuAzG8x8lpE,iv:01gjgeP9T0ARpDcIqK55dIfPHTrG9Kof3b/89vDadIA=,tag:bJJEfJVOPxgXQ5P9xrvilQ==,type:str]
    #ENC[AES256_GCM,data:iUIen3lRANtDWx1KnAiS+5L/4bvrfvFOqFPAhwbagqzGNENTawYm/s2d/N8882k=,iv:ETg0ivmR43gb1K9CuKD56C/XeOmzoGEzMP3Yoz3pLEM=,tag:2ah++9PB3H07zOQNUtN7ww==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:3Hgpr6d3qHSmBCl/nIvO4BSs37InkSxeIIQeK1Q=,iv:Ar8ld06aQi7F3ZAJqxNmQ/cnZks5Ct0ygGCX0Lg6/14=,tag:wpwk3iHmgbLTCF+/u8iDug==,type:str]
    #ENC[AES256_GCM,data:7LNtFqSuVjwh5J+Q8zZ88r7xYu34iHvMtzb9oMqGkn+vFs1gLHNV8ovbQC8XlBNGOt3yXtNHZ41VTmi4KE/SzufurbyCbz60D3gKaK9fe6q+Qg==,iv:EhMmAcdOUN1fDIdfEYyselTy3K89bFL3JmG88EDPH/c=,tag:xtWqL8RAR74wNVSX+2ojjw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:DpprfwMhhtKcQiPBLiM=,iv:RKkRpi/ednRb+/O+O7Gm5HRulM8qq4y7g1U7cFo1+P0=,tag:ZLYkmOfavvieoUNaxlIqfg==,type:str]
    #ENC[AES256_GCM,data:YRdwWpxw+wrTBtTpkBm6arzEks2NKgioqrtCtqf5IAen,iv:6IynVXSUocO/JxJvy2+4TFE7iUBSPYcMO37JTxllEL0=,tag:QCeOyokfnJWdOFNfDlajsA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:Uj1Acd/QeTf41Pj35AY=,iv:YHCKhdrfjA0cqWdBSwso7GN3BcmyXMp8m3z9vAreP9c=,tag:v7C+U3ClHdxLr32eDAEgWQ==,type:str]
    #ENC[AES256_GCM,data:4X8e/Al6sUNMET/xXn0ERKgMG7WWAqZlMXBPEc5kjzVsGLo8mVZaI5BcfPYLUO5ogcKBpHs/tyszZpehbm4C/VUVab7LXWsOXT7yUoqfGnA=,iv:kWrPFLcalN7Su5keiavTBVQgA09tlVrbNyw6VRFLFUI=,tag:+ZrSsDApID9sTmI14kZmSw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:wVzFgnRUDdQCCTyNjW8=,iv:QXaEMfj76EXvpLuzR6cErivVvtir2lPI/cq4mUiZnAs=,tag:uMFEnZ16NkqL7nEDAy7zOw==,type:str]
    #ENC[AES256_GCM,data:a4Qq7gYf62TzS9ef8Cd+Y0w+Lcb0h/p5b6i0Wt1Oo9xYb+f77T+Y8kUHEq5JD2ASu4nvOKf9bxd6QfYFTFgGGtrBDeFUP3+F3BkrOX8Oz9xYrnGJYdEC,iv:BON3HpGP30m9kr09YcVwyM3FENVoI6qIHq5u8SamrdA=,tag:WhcmIYf667iBuHuj12kong==,type:comment]
    #ENC[AES256_GCM,data:N99oMzGNEOjhfdRnVHdv+7YiRhnfdMFmUpnvkXtYG+SFW6Er11Qjnvzws5Uolr7ywZBEiVZGOg8cft6myYDRK8mwpKPF0ZsGhMzIikPnIxHpV/HVebTWcLoiZTvQQZJwFnB0FmmBq+G0QlWCt66uLIS9gLzjwwPW4OjoxA==,iv:oiy1XuDntXvcm0ES2GH5rkaq1OERB2karIdgjxqNVzk=,tag:kR0mnoJj1ryaprZnzBTN3w==,type:comment]
    #ENC[AES256_GCM,data:EGFVC32+Q8dzUY/2vLJjQFbMzBeiNeGidZG+pNIgMFgzTFBWwfjOv1+IYt6Q80NBp++j5BZ6kYKzeSjqrKjpsDtPZrxmRAmLD2sPEVglQSg=,iv:npQZCE4EZrI46Hs94Mov+H+0wJD3qY4cdxDXTzf35o8=,tag:Uy6jTFk/69Nw2xlmEB8toQ==,type:comment]
    #ENC[AES256_GCM,data:KytZ5qWC0XMaKoYtTyTttsLjNx58FuuvuqsMWGMtJa1379Ff0UVxRxlBoLpeDJ+RCZkU0AzK,iv:rn2Lnc+8HpA6gglw+fMaZuQoBliodRuCSV21YpWZJcI=,tag:g4HXXWVFgGpQvbkJndRsTA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:Z5y3lvhmpy1+VQ8=,iv:J+2xWXHxR2H2nHzhLbVW3WuB4cTTBXNF5dIy+Ibfq2s=,tag:8CaDjPNzSJ32LzWYzWlLSQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Tq5jPOXP9GIJl5ZrK1iATg==,iv:utl3wXuFVVMgfDZw/WQLdOJ0TYV6tHbO8xV+6Qa3SZE=,tag:dyJModuL4tO/1aEqOq6n3Q==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:jjw8gjFVdgP8WPfYoWXaPNGx57x4wyTc0wIOEUXimSrL+wAVnFwUJw==,iv:FuPBuaFYv9MFcUDdYJsaNpvnxVB/rq6ZRLCxqSz7zOw=,tag:vQ/TiglGmuxjH+bcuyaPJg==,type:str]
    #ENC[AES256_GCM,data:MHbTEBEK4B9pi4SNoU223mlyjHEOnvLk2rDna6MHCBPDxuZDDJhHEt3aA1+yjCXCFJUfQ5t6PK8=,iv:c+RTmcVi3TNa0TxDoY/zlSL2wcoR14geeOPkXQ/Pt2I=,tag:frZ875oVpjRAg1JzSLvUuQ==,type:comment]
    #ENC[AES256_GCM,data:eK7vro0ZF6z2JYTkg4aFq+RLs/jH1MJUdQ==,iv:WJDRqEUoC93Ak8+81ExJ5h2d5KwqxGg3b+XjoUWbvsI=,tag:kexMkhSkmKwjfTB0k5NzJg==,type:comment]
    #ENC[AES256_GCM,data:B5t7pV6VSnHW/1rrmCdjXVdlVjphCzpPMRAf7xWFehCfnAb/AhYvYZ+L6i6rQq3MhDx7jkcdhtnY1vJqe0n2w4QrxFc1u2lqimQpa7s=,iv:N2s51p0un5v3OOQOZ8mBlcCpobR+6JGylAJilG/VdEY=,tag:RmFhK5Iwve3oCF2Mg5mjiw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:pemQPebF2Y+fNiY/IQvkkd9XWoF4YiW+Rqb+82cV3eSbGBdGm4AiDrrzdHQpDZFDmvcEcA==,iv:WSjyEx0MTIDZz5+wkoQVMbwMrofC8YwRY+1R571/V0U=,tag:zTClikqGQHZ27dNI3SgBLg==,type:str]
    #ENC[AES256_GCM,data:xvJF7bm/5X+NSSyZh3Blol0P3BDX8cW+S/1UXjGEEvii/D94v4IE05be6tamlC/whHkkOgPnMjLf18y1ddUkHRbp10V5UpE=,iv:G9Gwes9ZvCmKqeuzX9fD0jodcnOYeCqC8C/wcUb6N2I=,tag:eAWPFPbiq+LaPXmXLzPPyg==,type:comment]
    #ENC[AES256_GCM,data:pWHUNqvs2G/oVaQyOG1x1zvZ1vZf1AA8HbHndk+gvN0g9TI77yn2l2iY3tuPkNucuC1nbkev,iv:nazDUmL+HM9HVKCIt41631Kj55K+Ug5u/Ld2+TDH+QE=,tag:eYna0zYmWWBREFbr8szqSQ==,type:comment]
    #ENC[AES256_GCM,data:7fSCeqNwBMILWlkU77vHBsB+aNLk4bFQKsSiiOzZTS9zEc4=,iv:SQ0/A5Y4GVbeMlPE20MN8W+R2jMs509qjkYkpXtpFmw=,tag:rGygRKxFFSnDIvXD+qFq4A==,type:comment]
    #ENC[AES256_GCM,data:bv5Q8lQvA4Kl+AtZsXBNTip5DemyrfVfkATWXZbsJYhzNDE7uv/z,iv:fVZNlmJHXUEiwMHnGOmqd/x/eTFeBhdVdpxIvZ6dPRU=,tag:igIm82LG5SENzZDjXayZLQ==,type:comment]
    #ENC[AES256_GCM,data:qU8smENfDmr7RujFhk0=,iv:UqQ0SM6A6Jbk65itFJwEz/I44W8CtaaaEHM+vcT5P1Y=,tag:UcPCrfJkPXK1U1j32yaYdw==,type:comment]
    PODNET: ENC[AES256_GCM,data:aVs/TZVVH6wGyhFqqw==,iv:tQm1HjbNvCWth/1vL5CywgPrOJr1VWcloc37NKIvL+I=,tag:bXnip7gT6VlD/jHuHXrYuA==,type:str]
    SVCNET: ENC[AES256_GCM,data:s2y1glDf8ozVZPbs2g==,iv:9Qrh9FXLXzZc/5wsmkbFG39VtkTSnG27SAU7KE9ONfU=,tag:u45vhzR652YP40m0OdIFHA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:rgjCiw==,iv:licTYUQuKxEvoj55ZJxpKR5jMzmharNuF4GBriN6sJA=,tag:Ix6rR3GvUugthAF9tqDM1g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l8p8vhf8m5tmfkrkr24phx4wf4uglqvwxu5x958xnpfae34qgpqqs6l9qw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOXlZb3Y1aUpObHZGTWwr
            aEhmUTVYcTc4YW82TkhUdWRFeXg1SDZEL0JZCm1qTEFQNXJRdnIyN0xXcEZoWDBN
            eDBFUTRNSnVaWldNNVdZaUNpNHBhUVUKLS0tIFM1cFZHSk54RDQxR0JLUExzTnBU
            WlgwVnUxVXF0ZnZDWEh1OXhYOG9NcFEKy/XiFo9LdURC8zZSb6W0cKB4TFTHHDvw
            kR/q0U5IoQcP+tlPaVnmHyprFdyW9DYKhacPIi/AA1njEaYJkkgyoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T00:24:50Z"
    mac: ENC[AES256_GCM,data:WG3HzOpXmJoE1lz8gaYi7q9FtDr2S/yZPysmG7q5VcVvKLrMCE0Tt5d13+6MLDbP7qjv9UKb5aIRGmLg0MwYblZdTy0Bi4myWbr/kC+d5FULnFeEVFmuPXHzP2VtbhJiIiJ6cvWwunVjtBtrljjdH8gZLpo22KDuaQEhGPl/H+M=,iv:65V5jeu5Qq9xKBTphpy9CBZsVGP4Ybz6rX2ZhI3DbBo=,tag:RZELO4/SSrVlb0qsNHwb4g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
