apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WqoTwlUdQ/GtmzjCXK2PqgML1ZwRACtpbVzyrnioKL1+B5T+AdTm94t4QwRAoMQZ35mf0yYUoeAyXUwCwYFPVQ2iMoqESTmhMNYe9NUe6tsbURi1l8Pmyc6/mjUL5aK2z3xwIdImsam+FvUvcQTUSSOubi3soxEWrD1KdbZJxqCymGxqxWOUWSDP1aRwSdNKBFw81dB6JGnxm96ytALorDgqhg5BP567LExutZO6vHBEwdqn/OlBkKJPqFOLREtbBQAp9vVUsjLiWO/3o/NtPs75VeS2LsSB+ax5B7S7ET8Wjjn+Nc7f/Xa0kwVcfJTm3T5qxljCTe9ekry26u00QVkR+p8Bj6kEDC/jOb85a4IHLsKh6T1ClAfpFeVv9txJ,iv:S7DJieJWZKnBF8qYh5rtp3FclLif1xXFwnimnmwTsfg=,tag:on8DkUtknSu6D4oxYRP+Pw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+KNQ2aMz0W/Blmr2V/GNhRBxmMXpI5ANe0VMD4uqOz0yKBMFzMR5krS1r7Dd7cs2jbpYrkIdW/6lIaVBH8NSumzutFAt30O44WleL2eFKOtOzMKanpptKy+7NG3NPyhz8XeNA3TnJ11K19C5FMXPT3qYxF9Q3r6PMOaPN0d167VZlW7Ru00QYKAQ6DWytOaCFQZbACO3oqHSmi+q5oK7S63XI5iaiIXaq714TbkUeeznrVERSMT1YslqO3RH1S9Eobljic2FvbTd+jbH5g==,iv:fg0FgMfm8syTTgdrgQlI3yCTWfbHo+E41JmQlZ0oMY0=,tag:BR1yISE3S3rZsprEAEp6cA==,type:str]
    known_hosts: ENC[AES256_GCM,data:6npCqDO26OScf7BhKPxgy6tansS5xQgobJjb+BytZ3nNLulLuVZIhFWL79HUOXLpaPg1kCLUc/D9s6QSqDnDQCgBAbe4ZHbVHOrpK0aWNJqk4Kk3+uyv4LMDe+1uWo/agJtNs+MNMFpL/YPQ+kkEcclPwZzORVyU8LaoPmCZbSi1CcPhvaS1lc6xMnSWMCSeQLm+8H0YCTRCVoGKWOzhlPZQy3LOCvVN1LHg,iv:Pt8s1pZI64/Oai6S5/vMx5OkDnvUmz2fcoi6JKpB86c=,tag:ZOa6MP0bsh0Vu9Q850anMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3c2S3pNRmZLUHRXRnI5
            NmhqRyt0N1FuZVh0anJWR3FoVGNrcDBZcnhVClhwWmh5OXFJS2VCdGFoMnhZUGhL
            bHhDTjIxUUNVNi8wYkw0THZJVE1tNzAKLS0tIHdyMFlha0J6aHdTeHB5ZENENmdm
            RExlY1ZWQWZaallvblJhUUtTbmtacU0K0kXwaliQyvT0ZerMzf80DsewvWS2vX5u
            Tcbrjoi1xXuMRpgD3Cnox8LaNLGeEHODNWz2Pl55lFMy+rV8ggmFmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T22:14:15Z"
    mac: ENC[AES256_GCM,data:6m/YlfP20puPyS7JcyzDWglJ6b7SXErj6XrRaJVVaYSBcUkXPpQhyODsv0gwPLBaYhthYp6CqSE5jsUKULC3YGcOYMgCkHCu73LPtkSUW2JmmDKwaKywCMpkq5Tzjx00oZBYQw6hc9nHACorFFrjn70w/ipm4RVUVnIVUd80dZs=,iv:QhOeJXm2XFOCLb9Gzf+HtiCO9emzm+KTSk/GYrVv02c=,tag:EXHnvyNIgCBaiXvCtDmLYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
