apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jYX16kFUQIyqgAVwVdzlcydVQUggQJtVxCd0Y+0aXPSldxs2R5KawO47nh7/TYVYWTwq3LveJunHL5fqmZvWhZIIg2aNgNV28xusu031V9YBxgGMmW3tycObsA2ZetXht3CXIALypo4SsMo3rhcGKWPio17y1u1UjwGmVUY0ypIs/60vHLMwEqWsI168oOkFc5Qs6g5G0lBEHbLEl32UXoOq2OEo3T374/aYcJo2s87o5ZD7uSZrgokWwcSTP9tq2etc/c/Gj2W/1AqwNjJUymjC5JA93QxCohxylbicyO0ELg3wvGILYjgCLMwhBvvKMINw40vus34w22LsRQeceKXfGUPtcMJXEI+7vSZJH+Fc0PDvZ3ftzyqqupP2JE2I,iv:6k3+mvrwBEuqWIxfIlvNaPCKmCffsDncJyP6KvyS160=,tag:y/+eihemAk7EbiWx3hhyMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qJzzn6xUldCfzCClxt5CM/HD/Ca9Rr3Sz0xsC7lNn45/gd2z6HXPGG+jguKycfTWkWANpjJrNCszujyzYUVAcKwyXc5zczfw52961xIHqcwXvK/3bRsjfgoqoAkJk9GpKgNmefi2gbk6xCYnwm9uMkhbp/1Gor6fF9Uze8pdp6hn3hYBzl86yif+Hc+LyN/EX7BvJLZu9ZtQmvQIDragRBhYMseWUOPy2mhdTq5hxpkTxCIqqRzTiHYeX0ioHPK269zz68gLItqTZBJx0A==,iv:BYvfFl/ThxFrSh5boPsA5nsJnNw/ihmV950Adu8rcp0=,tag:ddZh6ylqe2LEU+y+Xkd3bw==,type:str]
    known_hosts: ENC[AES256_GCM,data:yt979lBTUUT7KARZ+5NZItOyn5jZ0hlISK8H4UbaojMfC/VqJEIbjPjymGL837CHqaCp7ZH46S1ZEKYhWUMlsXUJqYK/PpYyRB/Z/UZDk+5CZIpesXymCPkC94rT4cKNfL5pNESm54IxEWSSoa0Kjh28MdHwvFyI2b0bmle3syntZJ03ubNZ00jCTITY56qn2tIhlY2++yq/C9ix+qGL5cfXjGXa7IfEdPTD,iv:ursZ9LD6hFNBx+QOOm6NcRfLozSWk4TQQuq/SOay00Y=,tag:2ZNw4tT4fS8aoPLzssThZg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNmxyNHVocGd6cXNEdkNy
            bURlZThIRW5iVStHa3lqa1lLUlR5TGpUakRJCisrWmtSNXV3aVJ3NTE3WEtKdVh4
            d3FUUm8vUXpPRUdiODluclhISTZmUG8KLS0tIEM0NFZsNndBTEpvMDRXUXkzd1ZI
            SUg4WTBWTmljdXZEMWVMUlczNUhMV0UKi1hMVUPzV+hcLCK5D0v8+mFIhxLCPSR0
            7zuzG4f7BvwAI4F+bSbV+y8mbsbHTMpwh0reUp6fg7irNnwOrl9uwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T17:54:51Z"
    mac: ENC[AES256_GCM,data:WJcXcncWTk7N/PnPkG/c8w9qNgPlsmDTnYwStj3dlz17pqw9zp35bq1Jvvblq4W8QyeEp1zU3bIiiqT3JQzMVLLPDSqC/P9aBX9nNlcnlEwywFW/ypgHSRgMwbSdUm+B6z4p7PImTDfvpgsWhW+jS+7+fM6hQRK+VCReO9vtE2A=,iv:UKSe2JX5+Mh1dAm1cuvj1FxEOs1zqzzF5a6m0B5WwKs=,tag:P4k+uzx5aOGSGzRyXjDWyA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
