apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ecg0THqMvqji124cx/oqW9NNR0weY/trsZfkKTwOdhdamFX6izRgbzrCAD6cGACAwbrVultCZf9WKXj/cHDAgfGhEYrtjJzKmKaxMX+r16PgggXpoYb75BkVvC4clAoTM6Kst8Cynagvusnk7U5O1iWc8/RzOeuVPpl/+PbZq5Ju9/Mqvwv392hve93sispt/7GGkW0fQapg+rUl5fcFVqreKtImgzobCogONVKTJLMi4Rl/Hr6bCad+Et+ugCVf73cnCN6pRkGEeNn5++Wja4t4n8QkBvcqyHsKxif41Hrv3uts6FPOlUdACpyA/jFbAHqFJ2DXIBwRy7wZ03E8+ARLZ1xQDv7fYp3ovCojClW6ZtSvnwtj+m5oIZkjuWXb,iv:ISectT/Sr+6oj+O2VeHJ+Iysf6w6f4GYbv3DN930pLw=,tag:sBzpqqSXK5M/J/gAwMXusQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:GtdV/DEDh1LPOzjLMte58nm0dgF3flVWGp51xm8q41DHtlbXuBWHXT8LKknpTdAhGDDrRJLqLXd/4aFvOAJAwkvE+Ot+UuvCFR2dJaf6F4Dzbs/cvt25P0vfM9W3w0/0Q+HE91Tbb0pNHV/vKez14FdV4iirZyGkEc0XKa/wTDYdlJ6KdkaXhEIJod4LrdZ9vWDodn3+evQMEd3knL/i59AnQubvMzAPXaq0d5FoyiAPnXHLG6GZ75ePYvmd8dIiDY2uPj0NfMOcXoQI7w==,iv:fETWCHu83BU9yGlFM239tCBA4mnVwkyx3Cbti+21m0I=,tag:ciUF66Qij99nE+1G+0R8tw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RZoWayi6q0ehwjAUakWWrDgWF9na3JCByeajMj3dQJqPT+WD/W404wYJKVSMGxSFDWxPjETer+i8Pcn+d419Rhu/JaiYc3kVv8SXDqg7mf4LM69JfMM3LUFSqcKvSlISVM1nGjlC6TGIqLz1dgWcRN8joQAKHchA+9ZTrmFsIvL38lJ8T9Ymh6CcT1pnUq3WZCtx95y973/pVSxT7WZC6tkLc1HBWd71+qee,iv:cjr+QNZzqvsF3lxJ4SJu4Z120cCvLpv77xgLNCG6fIk=,tag:0FqUFGhdPrGRTEQszy3CQQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVFVHQUFSTjg1VEpPalVY
            ME1ScTN5aXVvMUFmK2NwV3Vud1ZodWxvdlNVCjlTVnJaVjRyWE94MGFJWTk2dEdM
            cjJ3RDRZeEJJejlxUkFZSUpYakxRZDgKLS0tIDVOOGZEeEZOV1BIVHVmYlNWMkVn
            cFNBUzIvK25TMm04WTdQdDNqSnExK28KL33Qna/s+GGhX/IPzM3TyJu8vvbR6ZTP
            o9W6XiSAzUnMzUKa9zP9zN4SNY5B8I15N/PU+0NcsniiPpHgcvA8Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T05:28:22Z"
    mac: ENC[AES256_GCM,data:UQbAYaGYPsBv88Y0vikq2W4DxFYO3JUIRuk/b8fQli4LhEN+LAkmbFBhOQfjiNeSF5hlX5CvgmGFbXnEezVzaZd5/vXgIMQij4vXFCnTZKRJk9pjJoNoHBxCkRwdHE5lJDYJV/qqhSF/99dHzROkA0FYiQDzaEBzlkXadOut7fo=,iv:9DcuEDkT/r3yivtV2wI8j9HCKuk2dUQnnjUPghrk8+w=,tag:D49U3tBJQFywOiiPD8KFOQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
