apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KngEaW0OSKd/KR9U3Sv6w/StAGgZmuu4dpnb8tWEzZj+RyynHnmIXIdwFu3d77twYpRQAspDp6VhclxNVMsAR4tACyMY2eWyVJ32Y3NYJYjcjtv4Z869PkZuY9RXCxUxnmv/fe/dCy3K9d5gumsUZlzYrCcHVUy/o7nk5S77Wg4mP29rE2WVbLwL70B4+iVbukHi4SeIYJtxAsQWcqHlb1BdcCxjSD7vlRl0r/MCu5zyJjhAxll1tIJ7Wa3dHGfVzmco7W/uAxKkbeBPDn9ULxpErfXpECehn56FqCR96y2hqePd2/6Q81L6Hn5h/jOwGhlzmj7rkFgB0nMKq1NcVS/ZgCRuhnl34rzDTQAsuFc5cE5YqFBm2QNPdifsy0/L,iv:g7/Pnsp4U9LA2ln3fvXP9f9gJYb4DJRycqhpN2d02nI=,tag:/PD6JfIG6rwSF+JgiEhIIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:W1LMPKuR3nrwgCyrke3YG3Gw+9AlybR0Ms03CeotP/fE1k/gmzae9NM2qYDwS4hjfDvxm3/rUgs54lgQArMx1zSKeYmXIzfMyvXW80hcDo4ENwBJ6CnZ+xMLchpLCpF+JvezPX8gs3b0OJ8+HbTPvw7YQ+t/HurczFaIxFOpa/14LAHk/d0Fg8njSrKAktaNavJTKxiE7rAI+MnULiQIQB1Qww0RjDIz/XWt9tZZ7Ol0Y0N/B6ZOZoRbr6T/fWxbY5BraBswrrq9rNo1+w==,iv:59Grq6LuHcY/jl5mzwN4+jMGX4w2pGcLutO68OgKLeY=,tag:Ji4bPDm3pYeTfyb0Hw2eow==,type:str]
    known_hosts: ENC[AES256_GCM,data:qmmp612QmEmJA3FjBg7fljcikJPdHHIWVe0b6romK8dBbyJFqO2ypy4XXUhL9uJMEiB1P9jEeFuPp7nRGaeJRgF4go4R1dV0wXkupaZzX8FLRgTcYUMmcSF4oEgBX3W0wcOtEttrghjKPBUDSK962RkIQPMcel4RVFEkYft0LLC2Qx04gKN10286pZBN8zVP9U2nP7jgYjNAetocsp/7P/zhnORzsO7Kk1oB,iv:VQjjAupmi8f6KX8+kf1P3IWofCdsv5R1OVooYTC/BFg=,tag:bBopO23uFrNWTNMyMhx6bA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmFDR1hSbHNHd1pvMnN1
            QURWRXZHYXFVdGtSZTI4UWtjTTRjQTBEeVZJCld2dmVVNjRMejE1TkZXaFFIR1ly
            bEdhejdRZ0h1MXFsajVhVnpYSjZoT1UKLS0tIG5uY3pjNWxDL0RndnU2K2RZeXZY
            QW5LSjJLMzNvZWxqcU9zekExbVZwZmcKYtFnrlt9HMOE3FxdZODrasD2Q7sDEju0
            zH+3SwL5/Y1B4VWnrDS0NoLo9mLe8z7eTdKRNcaRuzMPdCnXYY6T7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T06:01:22Z"
    mac: ENC[AES256_GCM,data:weM8NBvSCb1cKKb0npA/z5rKQZsvclYLD+0pBWm+PX1ZdAYZfROGByYSylmdsW7Hx5j2f2I9zAt8evZxk6o6C9syAqkqHZ54U+1pJytRU+Q2UvM90GWAhx2eFu+j+snbGQFRvNjhOdG6tYEZnVbURucMZ+kwK8kDbkI0QBWh9Qg=,iv:P4soApAPAldobAE0BIGzivZ+4rJrletqwATE718FQEo=,tag:fhqVYaYW2f64ta36CKASMw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
