apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lRLVyktksKxu0Px6eupiOBxHIB9WJh4pNJMSvcXExmbr7TFTVRqd9TqeUYBxe4JxYVRLWxq3GOAEsSXv7yxEnbrAKdWE0MdUPvtTijF0Vdka/rgDY9x5I/O28HHVfOWcdhGVFbUGVzZuU6IlsU8OnA3gq5dShdp3yMaUJ5wO2epsyBrOIVUC+dwT4r8WbjoSOBR+gaIoGUHeogo+GWJmEr+4H4k6dAlPMJohPbWzyrQZJWHM0Xz0cRqgL0dHu0GRi3xAov+LMGI+UMaHSf9iyiqkbZB4Z7LDHEy2/Pi3aJjjTxdLZAzz5VdIaNdmmq3qeOXutMMidHehhl8UlSmqvzXhGkr3Oy//YM7h9ONQKO5Sb+sFleVT1IlFVb7dED/i,iv:iNahZ1eoB84AJnpavy6+RSJ7NWJQMRY32GEJAATODPk=,tag:r4MwC//7pF/zmEbKer3vdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:aqR9otwYDrS6tQWcNqRYzoQ8WmV908WzYeEa2Si5iRnMbqx8GaW+/+heBBfsLtxoCapFNsdK6TfIYyydFSA5PPT9VyXwNYAUPGOdFsZs9DYiv6djqYvWPJc9G05oObRnWAAsf0S4nUfk2rmovlMe/kAVsjWIA5g7ZoEI0mrWtdH7jRQE/n9kVY+1K3KQto+zOjNr4JvCV+S8ANBcgIwZ8qyuesKZZxadTVgCAh/vINGEWRNQIhgSfHy2pgMBAT1TMbtcRR7wF0ts0xC8PQ==,iv:UAF7ZSjR4o69p4AeCn7EFg/eL+3HNj9OAtsPrDhgxVQ=,tag:9mwPup1x12FzyheV99z1NA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yOq7kj2MZlTbBxGwAxXz8WbhYSO5ZqFBlEy2XVtBVJIn/c3So3EauDSK0WtDYwNrHrZfLrofOD3/G8Copp/8NN5RSMTFFPZJIoROhT+RRI6AtH5uNsPxmRZ28b+pi1n5COrZPgO9hzQl/zHXPtbVUqck6oA+GyonOETlpXOSL3OpdxTHvC1vHqJ7Jy/JrevBYVtzpEYnOi4K9dji73+B7XNJNwDGl+eGrLco,iv:uNVqUgju2ODIEgaZOVphprYuEg9shDsxxuomhAEpN6Y=,tag:BQC1OSFnj/CwWg5qKmsT0Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcDVISGl5ZmZCRFlGcjFI
            eTVTUWdqaVV5a1Q2OVVCMmVxVUxNcjhjdFhJCk9mb3BOdmwyOGJuUk1GdWFCYzV4
            NUdqS3BGN1dWbEh2RlpzR2hSTXY2dWMKLS0tIE1YK2Jzb3ZzTGxFNWwwU0ZRZEkw
            VEE1aUROS2ZzWnpOVFdMVEQvODd5c0kKfPXG5vOocGTMSuyBB0szSIjJ5nzx0pp9
            SV68l/+TZSElYRMtZeAwwKmnjR/GxlhIi/dpxbrR2OWimIo6D81hBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T17:55:38Z"
    mac: ENC[AES256_GCM,data:URC4FZZNaK2zg2AnEL1WjepzNEuJzK4cAHqUIBAYzQD6NmiEV7DRJP6tlalSK7u0sFIycRJD7pV9R+cZD8Z4yon9YXp/tTSG08pxO04F4UbZdd0i7BX5yJ2hv/uoLn9sRiuYbRiimhQGtLGxStgeJ/EqHgO5tVyWyvPx7W9pUhg=,iv:WwOAFJclOQ2ujjFoxY4XmArwYXDdsg3Am/Vg/nrckoE=,tag:LaZL0ElR+YzwiFZM62Tj2Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
