apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ssCATSllku9WOqkSLKslQ0EHOD9qJxZbWAYBC/IOpwVXxDbN18Cfeb0FyW25xnYIZUgi9n+wWdrbMonDsrDzYG7Wa7p7lXnyIP0ylwGZPT2ZabrUkBdudQrqf/lhfpSs3butC2apcHX270YKB9tI061uXgrtROTX9PhvgASqz47/KbbpdLr/PY3n/j3QKgDnYsiP8FaxA18i4KKMHHEyTM4BvYlJVa8rE4XLamZBN86cylkS1+z6+Brg+a+N7vyBszUAVGf5/jOQyPx2S1cnBo8yZ1vrUSq73BotGwxpRckTmGS/0kvgengBflkezDcSR3pNWUZBfbf0Mp8ooG0tVnT0PSsRaBV42FbBr7g77NhW0WGBvpao69ysrzXZohgC,iv:yLi3qChSAYIPCRpq2+ct+8Wsqyf0HeiDkzZTytS7DnQ=,tag:y7qumikaA0u8mxQUGt+ENw==,type:str]
    identity.pub: ENC[AES256_GCM,data:YT2Y2Uadn6nn9nC/8eOtk5AK3cYCOR1YyVIwPZyTKljNHICocTnQpGlB5s+9aqvlQLS1a6tzx9g15hoE0pTnE7olUcFpeBQvZHYGY+XIB9ehnUThF+odFPchx5gfV9wJ7lejtfd4HWAZ3u4X6ktkJNsS6mA4gLruqt4pgUkUiielwzTjaUc+ExBcuZUugxu7zsvqTn9YoqImu6NHrlF7urIMQ07mPGTtvme2j0aZGFEHxUn7JOZXYyEbItCDMBpEs8lpgIYwF5xmRvzHdg==,iv:HAgnE01J03BoFn9b2/pfs/wt7c/m+d687SSWvd2BWcw=,tag:DjawnfNsYvGHDqgLiowj5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:eHrcq2ihc3MVxZt9e2rJdFs8XfwZzc4mPXFJJYE9ahcJ/qtcVgfyHQCfoVlVrk6RrnCAOoH70nuborEydahGm3n0mMJNCxIfirgrSE7zGd/WUiZGXKVPQ1ysrb4CwlmTRdGKl9ihbQ7PHBaMkU7bDRc+wfytbxYj+fjPT/FP0nEPEGfPLkZcYhfU69iCRlVW3YnqnOb6arOIBIA3NiREj76RMmvC7M/8s616,iv:32vC49EI9uo1ZdT2xm6PsNw3qJr90xC0MCNAVGBMlvE=,tag:PRbBsd0MSlomqIRpZzREww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d1BGeUhGQUN5YnFCd3g1
            bkJ3T2w0MGVndUs1ZjRQSllnSzNTV0dreTFvCkw2eUZjWUxuNS9wL0ZSZVNtbklM
            dGkvQXVLVUtPQUlnVmR0M1FCN3JYSUUKLS0tIGxjVG56U0tCNkVHSWJzZUQ4UytI
            MEFOYTNCWklBRUJkWHpub3JoTGNrenMKwhWlRUFRO537bugJIvxCxPk9ter63Rra
            lzD6tWRZ/03FbpUKn++1gw97XqDkXOVHAqYIP96ayIeR1zbVi08gKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T20:18:09Z"
    mac: ENC[AES256_GCM,data:Aim1DEHcG5CmbvT6svYhmTv0HMMQajObQAq0DYn1uotbeDalxoD06ry4dCeUuexCYHrEpvUM1cARL4M77az1bNA1WICZ++ZxRyYsho2UH03ArhLG1/IEeaBvbMUMrbn0Gt4iQJWUmgFS1pLIHEYj7m7NbDc7zZYDT54UxF5W7Io=,iv:Iefe4J/YGtkaBQpoQ+niKhM2jvwQhLkZjJa1QhmM7wA=,tag:tfq1qvYMP7ZjbWJcOiy5MA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
