apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+sG/zXQb39lrYKXyGW/cCIOlqqw2HkIVG0QXoQYYI1s2Y/ClpZVx4vKc9XD3y4lSlcSIcn0lQJon6aScH5QbBs4L/pSX3VrRX4ok+udGzmTUbBA7s6VXaERNft12KMJ28k2lx34CLelV5YouuyJPoisrFOmn0flyleQLs9EWe2Ymi4PFfHC+Vonf/OtV7lwpMoSofDR7HTvWSYZztkZ0MQaJuXSYqkZES2K3UpRO9uS51f6HnIh2gZ334FFewnDN5LKf2TlouZo/eBKLotokxyLiy3PNsmOJC0uKM+TiCf65pp34mElI5IwKddO/L/zZ29KeO17j5CN7otFfzr7B1q8E7m2yJglKG43cakbqWnbdQK9db9o4gwC00yZ1t7CP,iv:M3L1TX5IsNS65JzCGu/1JYA4dNrT6sNKolm+aEzZo4U=,tag:e2zwGdQzeeYKPsBRLNKqrw==,type:str]
    identity.pub: ENC[AES256_GCM,data:bBGTMSUck7ZI1J/5Dv/Pq32auQM/YTLD3/QFvLntwe02Bne50DHHoW0QY43wbcbEWGGegNckK2XM80mvcdz/XAa/g4JMw0OfwjvRuv4iTBvgolNV1vXwMB2qjGpyNdKqZcQf4toMROIxTTV1s/dnwqNAJn+sbtXlLtUXAarI8hvadQEg5jiGvwmToai9cUY8bvu41CkFz+WZdr5gN9KbfASn2nRSA6t2pq7B+AdJiSaKhkkfSWSpENCh9jRf5+F0R5N3OmsFsxc3pF6HwA==,iv:n7UUydxmZROyxLDSUvVzGX1F39nu6cGsKVXTnVjTMho=,tag:peWz+gJ8z5OmacPlZGQazQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:fzW9oFDj4t2UhX8z4h/JOgZrMX/f+u/UEL9o5n1zwc6rx94MDWkvG5vupwOMt2phupL0pmtdLeV5dmCvRIrOKTJzbb9oWCH2t8HXBP/a2p/JJjKwBugZk1nrALfjcVMfBzXAiwj4UUn5w54fUeJUxUY+L6ZUdGnRb/pFMoBvOsh4jlqq0ILo4pgU9NZOSoxqBo8lw71et61G07/hU813yXLkgKRmw+3QsQg7,iv:iYCdDHdggburZnU3YPxTdtljjT0UCtmryHwviG0IGEQ=,tag:aD+8yfaJl5g3UwYDrLONuw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S0VXbGZCaWRxdHc4UE15
            NWtzZDh0NFhWVFhiSkIxREdqcndrc0lFc1I4CndmOC85NlRXRG9kemE2dGlZWWpl
            Nkl4UFRaSTJ4dGY4ZkxNZHpoU2svNVkKLS0tIHI5M21Ua2s0aHFKZWN5eXdZRkhs
            cjlkeG05RERJeXdxK3JCR2VIbEdVb2MKK/tughMJu1v9kocbnkcdSrXS/7ZB1EoS
            EEXmgwgHK30CtK4o7DD18e5f0tQg9lGs9fFn3RPLejXWEsnHz8hNAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T08:25:05Z"
    mac: ENC[AES256_GCM,data:Pz1yhDHINXgA8+bo3H/MQ1DSTLwYlVxv7DcKJyRLrHSa1d2bD6x9D3TeDcY6lr/hBkQkfumEu1f6A4zXwofxa3KtfMSawftNdrLYXOUkBt/Yz1ATyeqhYcimT/j+RkV1F1mEiAEkmgFFe+gEEABuOfvDNSx7gkBwgn1NB8rdo+I=,iv:iXGt2pndOdrVYul7uCE4WocogWblLIJ3o5ljqibH6RA=,tag:YcquifMF1ej9n+2YogwVkg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
