apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DHO2GqFbseEIZz6THWnyWXpCPZvQ6+jknphG3TRGkuMun20QOX8y328ihmoIIqhoozvyw8fwCivAshG+9BwHOMewLzusbesBBwzfiA55vkrPvU4PiSUbHNz6/BJsebeBh1mtacj7CRJ5L3BMI6mHbMfo5iRqAEunL8JKi3kHIW3i3jI/wNjyXca2CKoMg/jYR+ZWgMoJ4zp/zsbQtmiOKroziPx/KZ9Sj11A3YBpw6ci75Q8d06MChpMkXf7OriEF9L/kflcquMW9wJNBOLXjTV5PWdmkaf8PIlMd6zJXMllPKpspyqiMY21arOnrMJMYBI+UYZasxO6cITQDXgGmzliAxDcwlY81wiCvAOxWtTp/5nRC/XnW/PeyCQVwqsV,iv:rlZxDUWqgJSbk+1GAEWfyp7Si6jMIzaNCSbUuOH84QI=,tag:44WwbkB0HoPPtuglHlsgbA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PLpBDlKDwjmDBOo910kI6gBN/nUFY1u/+ia2qt+pLviPUsCFW6nckDGhNZ095UYlS13kjhtF1poLFC7A0xWIqRF7upQrz/wLb9MLcRO26AvjXpmGYetYBppXUxrDwoand8EGf4+VgftUpESATnKof+gbLTUe6RQ+OFxuDJ+ckFKxTQFVrD38QkxhknRIGpSRkBqRriUJqfb0vt7UJCJft9jB4LNWAQfSAOZFoTwq/blGBdBXQuGVlCng+N0cOoCpBuE27J4riZSMxPZELA==,iv:uqWt03KK9E5gP+p2QjQXJ++7YaimgO2hYb5TAyJ8Gq4=,tag:MabI3CJ9YQ4SUrm3i4xxMQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:13aA3so9sDBYoq+zaT2CltJ+gBtBk6f7HvwxNrEjZyNo38fZk2zi8Wf8u1xWgZ0Qt851mEZJHObfhdcKXH2FdbI/Sgncbu1lBHA+5pjOORd9GxIWp2f3+8Bu+8BrLbe1SXZ7Rn/yvOFyTOS9IihgHATfsN5qNFFSNWcpf73Rg+2P5Gy3wJ+a2nPhf+iRJFQoZQTEdcIfrHAgFhjrCyvEXvP6W5v0JHEiDq7l,iv:4QoH1Erhtc26/4avkoH+B/71H45mZbgHVnNDur4UwUQ=,tag:qB352hk9Xj7sAeispYBBLQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWU4xMzdaVUVZNklLbk1s
            RU1nVDVUUDI0VTZUK0RtV3N6dDVhcERLK0hZCitFYlg2T0IxclhFR2xQZGxNbVVa
            TDduWlRNcStmUWwrelhva09HbndKQW8KLS0tIEE3c0FxS3VJY3NMMHRJRGF5M3Bl
            b0l3SDFWZUhsdWJZelZuYk9BTzMzVmsKWmRdikAh4pP12BEASi0IeezVoyoL1H7G
            iz+61DWytaKGIxtyaIAeWODrWWLpSbXlyvm0WoA/WKmnA7iLBJgzRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:00:44Z"
    mac: ENC[AES256_GCM,data:15Uo8gZohg4jTSabe3dpnoJyWwHMzNHh8bhbjhji3SP972cdgjIOxwsWdtJ1+OFHD5d14k9Euhru6A0wLIzAvXfVaPFTmagikPZiIUqDC/r6bfYOEcB5A4ukb25biNdduDaDHDzg52MV5J0pdGMwdrFPtzKjBBREBTdPLsC5F/E=,iv:HKIq63VXJ4+LE9uOjOizECFE06bxU0yY3wv4xFm10LI=,tag:SdFoJfFrLEvge1fOv5h2yQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
