apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0BuIWGLr/BFXJ5qZqe7grvd1HILXLMSGaxrH9TBE3n4PhGhd6EGbnKAsVXZUMQuue6Neablvpt1ZowGWLolzNGFN88073S7hBTcq1znP0Ufzgc6E8FIEVkvdeFPsPo74Py54S9ZEjF1bzsgMxlUm27u6hO6Shv0+U3uxIPkBvyIXtIr+5AA172PU6bb/gQoBCPnO3WRYkjY3owURnj6cSQILTaBU3GYUPx3jnzjbq8IdU8cnxeMsFt9sbVZEbZxUFt4cQKGM/9cHsfVODLZ4PGjg3EJzswl6lDzub/5Msm+bPcAiF55bSs8iggicig3wSSYHYsKaBfM4k81vZ+81KnJ8hGO0jhmjmS0UUrV322z8xunn3zJaH5jRpgi/Wiue,iv:VeFaV81dsPTz+VoZRMjLgL5e/0gQZzJNgyH6uO8iLY8=,tag:6KDHdLG/skyuyEBnhHDppA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PxkHr3vXh3lyeCOK4SsfI/UyW1E7rjK83XP1445R/ofPuNp8gFCXLFxBCQ7T3BSVG9X1HUl3XjaJiLi6patHIeyUsdnj7HCUn0bmwjBX5JkXHsY+12nVA+r6bEZab1YlsQVoqoBKVlvypli0q1viO3YIRVRycMIQXgy0uBxm+um9/Nn9jfSJ9e5CLdrYdq5gs8bRRVzwVNniplzhBnsn6nAyXyb65vmij6f10apIjvuxVKqxqBWYoG9vtDUhUkHGrNhy1sWppWXwvqsCvA==,iv:ofZaqS65Pk04qoC4B8181DK5uZVr4RbOaQaQveYpqGc=,tag:R2gM+IZzb5G5tO7JCasNqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:q+o37tvMhji2dYGGzsHQxzggj2nDM6fJesaunTgXIDl/kzdxyKdRpZWzyIxCyT0PctY+3BY4QyBkjRieqYBEW4QpL3q6qMD4pir/Dg39uUrJOy8OYHoLQXTSGN+gh0JfEpA9U19XGUfl5su3AUHLkK4Eum9s/L5S0MM4ASH0mTE7VsQxQRlfreqiGZ5sCkLa9vKTX5eujGXykv7XIvD2i7nqmfbg1nR6gZ05,iv:WfzsdRydCsLd2+cDys6dU+x+DU6VzXINktlypMkfmkY=,tag:6pdgYlI5eAlYsBSQfcZKaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUTh4eGpwVE9OVGhTSHRQ
            QVJzV1pJUEdyODlick5UL1VmcUJOWkp3OG1BCkN5eUVSeXZDcHVzaEU5K2pJNlIw
            bG0yVTIxOXRaQnBLc2xyRGwxdHBKYjQKLS0tIDBDQjNjOWxDalAvd0hxQjBlb2U0
            akxWWkxqYjR4ZmdJa25Sd2k1SXNKUEkKufGA/mbJW84JvY86oYPWhjB4gAvxYcwL
            yiw7V9nsVVHvLTh3B85i1jEKxV4pc/HMB4C/trQ5DKqlzOxczcYmKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T20:19:01Z"
    mac: ENC[AES256_GCM,data:a9KmibVM26jMgsIAICWge65yYzTXXKruKUKPU/YzQbMlEAh09H46wNGTxKrkjJJrpLchTGIRqGVlFn6R+dc7ogQBP6Fd8bQQxBzBOVmbfWMJc3v0IP7OSNtulgQgONbCcQgi/FX/cDIKvdiV73/opco/E8coy97M95nliVaviZc=,iv:0UISH6CINwz2WhLfpDHRV0iVQb7f575MVOyGyficUZc=,tag:5J2A+41TJBGQTNDMrbD6xQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
