apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:plp9bZo06FHG7uqfv56Su1agL503XRhKEyr0vL0KpWlMXgu39gBPCn6s5WHGbtFk5siTltJxVl26O2N4U3jj4acz0uY8nsdTshCabFkYTF3NY16rdyILQzVz65OVDrOgs3rsQ4Vh5YdVyMunBsGOm9frMlveVD78ARzU0+CbMQnAtPju72z/vCx1//VPtx9OcjmEgrS+TuO2uLkD1EsNDe6ZoLVrSG1xVG6GkGrbGgTWmpQmrwIAk1h6Yr4pUzUIx6c/5+ST7BcLsPl61Fy7NLAvDunEUs3z6SbiOa32PWK2/ediAD4MY8VUKiAsZaWj6ybbu08lVW8tDgSVRZppeDMAaz9QR980tNYXs2FvwdF7i9iD8DYrXi3kM9vBo4sT,iv:7Y8c9FsfxhSNhvEyKGQPJUnfnrjVTxgX4ILXIVg/9po=,tag:RWyPIjAyAKg9JQON9o1PQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oThSEFZhXhb8SMUTCGMusLrM9fgjVEDh6UtZ41aMjT8bwgGkwOErsFeTnCRtChkr8Hj3IiLYxD9blgIsVuvmHplQDBPmMXRakcDtve4SpU2EmFM7q8P/j8EPy3HWhrZ651PZR+jIslNmyiO5hu/j6MROPnubVZV1b8xogTkVeivISpxh1SZs2o6sTmz2kanabb0XqM0TCaZlbv70XbIuJBSqHzrCuknwCfZrRkGTc0/RVAKIeusuoGT9cLrXT0xhcssybQQVqVT6Ll+GWw==,iv:JUjg+VRrcwVFWcS9/hkeUoIeIXWrYhZ7NyB8//z+dlA=,tag:mDUeOWdCJNpTvLQPXih3Ew==,type:str]
    known_hosts: ENC[AES256_GCM,data:cBj7uKaKv1BYtf11egn0NKCtpkNEIpemr3A7sUY7Anwu0dxAyxYmBchkTAiLEcNxpmNVEHytAVGmLWu45ThLdT/0iwpKzt/45X+rQypsMaEvNk5kDiX+7++X6Zw4nIn8y9c86fHNhxiv9uNpGY5DAn3trGwaiqDt2L6S4WA8rc5KzS2wn2f3J7a1sKVFMOTzimvl8Rgw+8rtGoK5yWncjimssPjuq34uviEA,iv:+Le9iE/9e8+6s6NineceN0xu0ldrHZZHo6PotYBj5oI=,tag:KpMyR8wr5iTONwz7o4mBVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QWFlbDZVbFVtQmxhTVZh
            MERiT0tza2xqTVFWWGhpSVNEdjlwanpQRWkwClNLY2MwTVBHZUgzQ3YxOU44RlVp
            eUJDTm01Q2MrcndRNnRBTExIZ0V4dVkKLS0tIEdxb0REeGY1dUVpdU52eTFCV3pW
            aGw1b3FnVDNmdk9OSU90WWU1NWRaUmsK7UE1Ber+iOOq3JIatuaNFjUyNj91bYQl
            hug5vJEzu9S//svG5KW9BDGzEC2p999g5XMpEOQDpQ9bpYDY3T+wlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T05:48:40Z"
    mac: ENC[AES256_GCM,data:5HPE8nVfRhtk+95LMef7pbelqPsw5DGZyjjW47eVdEwDlLp2zvKyjJjseOHE54NNVVYYkoZCSkGwcQ+IK1nhmnYDTgfds43LaeEj+gvoKljmvliEqARaHhOh9RLkc7gKcZWOkzUueqtLCLf5861EhUBtKxeWkZ010+8jO/wHYkA=,iv:1JU+PwmZ6nmd1wvXWU7J+Zus77ySAA5l79bqY3tuO3E=,tag:1xD+wluQe71YtNfJE/HAmA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
