apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4Ier1K0w0WV6rW5/G5Cy53/UCrOBvJcXneyZDG2LvV8fYnFOR3zEkosrMcaegI7GsvpYiZ0DHfZtANcXg8nGx8JfjSKkOSWCl5k5etzrGvAjqv01zlZh0nD3qij0dibegZsbMITSayzxeCexKK4hFp3L3ZqyNXEyMTDAKFBKCzUGoNJGWgRHnKbwd2XIDv2smbJncpqOBdWc7usiDQM3wyCEtJuSOU8hH2yLv/5y1MfPr2F3zqA6P7sxnYGLEnaMTZzV+0IN2uzmWtD3M6DYkvy4L5szLJ3LQU8iggA1fYsWIvDwepxKluQFQYhJpbFcSwxOtrmPCz8uuVNGT3y726j2ZHJq+KEPRQmYdBMf/2x6DqB4usnC0R0CbyD7tFRy,iv:g662Nt6CO8Fo1ZvffltExj9+88O6x+XgTQsf/+/KxeA=,tag:YjpBEoYMdSwVOFgDiQ+7jw==,type:str]
    identity.pub: ENC[AES256_GCM,data:OpKFnsf+JCfwLa1SvD1s3V/tF5MlShkRdmkQg1R2zXcMpdkp/XOu3s6N2858i1lKBzoC/h+CuFaAAB4YIfYL7SVA/6z5pi2h/H7wlXbOcuHytu7ve1XHGIb9vBdL89YP6MdSGYwOakGcsblEom92c50qKpDN9T8i3eOxUqXxhgg4iTSZNokaGj8y4CC1s+hQzbI2CwZKSsSCFK6wGeF/3+wNXPcmtzOQgUG4HxjAaaOLMfZWxxKofrbmO8eztS1kNKKl6D5XMvHeR4xVZA==,iv:4XEYGTUjomtRXIpZ6Af8jwzEhfFiRboKaWcGbAqcWFw=,tag:aCaCsOSjvl5ld/bf9XsWDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:oP1o0Kr+WL4g1q/HIqePA63yjLKrcXa8mcqQnpt7rvUUBYCR3sCwAnnrgZyeYSDSyE6tOiF23cMC4XfpXZr9gAtCFEZduL04ya8EepBSOJkY4yUJ097yS4neyySFxoYGrsphaeZyUrOaVYQAFJMT43dUujPFpnlbB+7RtGuTWMRgAJnyoFUSJZVEjMN9wxsJgr13ZzxFAwfck8lo8nxaAbYWKZnRBzzNM1UN,iv:WA/I7yC+JI5Rl8Yn7mxSz44UujYD5zgSJunim7qunwc=,tag:qkjuROvWr7jSm41Cqw8IYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM2VJdnNsRkp1Nzh5Ritp
            Ujd4bndhekZMMmlMcjdtRzBocHkzc1RpK3hBCjJnZVJ5UHBCQzAvam9nOW42Ykcz
            NVpXUmJLSlYvS0JLd3dGbmpLSm9nOG8KLS0tIFRpc3NHbHNZRGsrMFFER1RBRm0r
            M0tyWmk4cy9DY1NuTUptWUErYUpKeUUKnVlkYQ8yNHoaf9BCnzDKmGAiRVljoJY1
            FrfUAoDkyEdEWDCm37eXsKogsRyL2gc9GXB9br3n1db/0BmFFWNPmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T07:25:55Z"
    mac: ENC[AES256_GCM,data:SO1EmUU2/5pH+TN3+xqF3hEQj/zOxBtsvyyNWgG50/Ag15RJanmiZhPs9o3mikXOJqYHJ1CSRHCJtSERB23QPYYvCIiGURcrPqaAQJ4urAMr3ThlM7pzR0XWI5wTlcu8ZcqJWwUp1TGAK4Q7LVLEe4TSdu0kkXQ61Lfm0UDNpWg=,iv:fGaZb6qZZldYroMb3b0s3yaFS7SmtKLpk4gyfdh+MIA=,tag:myAhgo3s/7lkMLuYTMdlNw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
