apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XXt6XH807a5Bpszv3oXrQCvCoMAQ51XaTQJ3+gH10znXUUWRp79+Wzy0F+kOHNi+O5fxKMGXhaoizPd2AELKg4xf9ad1ddpovaXqQwRhU5RCOa+aRAgqV79H1F7KaTD7j8baNOs/Q4hWcWn27ghNh/E2XxInmE1yVSyBhvlZRx0UfrPOilq2HMpDIh2jBrULFezQI0EUYgzy5CbHj3MguYhKxAFpy0rcJjaHOLHM7YdWGXguLDBXeAUbrgIKHdmqoyxd+UTrDeFPlUuvK1sreg6m2ZIGoCwNjsrSreiLJBwfFBxL3mhwhFoq5zyZeqMddBqo7IWZ4hsF6trqV53m/awdcZmfbvQS0cVoi0a5upseRcUXKbVsQukvQgfewSTc,iv:d/Hl43ZB3GsAlO6YDMoSyHFgePDHkvLlpn78Ebtu/II=,tag:I3bzmq3Kd5iO7sH93wqX6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:djZOv8SQaBiuKwc/5sqOV1pC5J81y5SM3NIGwx7sJPbKUqb4BS7KMnWLQ4q9uY6rtfoElGySn/wTdIgyWPHxu0u/eNj9TsazMFl3YPN+5To5OHKacJO/AU5ZX43EzwM1DIyYGphP2/5k8CzpnRyucDPVy6IDf3s0lqgbpG8UroIR+LCuAcAqZHhGUGBRb2qLU8tRzHAlTjEWGUgxyjKWNihGUcBixgEIayxLPZtvfyujh98uYgLyZV22jUQRXepV/sL9DF6Y4txmLv/SJw==,iv:KmxphbOnicC42O+GWXwqM2B/s7kz01yROlruI3Nssw8=,tag:kRTHJhK1IVaEUnqhg/P44A==,type:str]
    known_hosts: ENC[AES256_GCM,data:8KxuGF2c2/ysSmgAVEIlP+5plrsOHYFM525N75K8XQP1cl6Tg+Anq6zNKavf0/9Qdpm5qGpx+Tq4xz0dLPTb6Tt7zTBquD5Toa1NO2dICUii1YXSYkFgPGV/YAxyBv/SXSC7Hv+789k4LRQ8XuldjbjIQTvkgl/r60VnNlWO7Lpz+1tvnj0FIcGwVFPKF5KLOFhme6pdwKOx6TXzUwskKQ9U+UYwpV8ztwjN,iv:RGs7Z/ctcAg7FXq2Lv6GDmN7mCuJNP/3HixQ9sgZoNQ=,tag:fpBQVPyCqdhNly7s3Jizpg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zndxb25xSSs4YXVDOHgz
            RnRhYWNXV05YRnBWcUxXNzg1K0RSNjlINUM4CktFb3N1RGNkTFNuQ204eTR2ZXZl
            SWorS2N1SzhFQmJnaFMvQ1NmYk9CTWsKLS0tIFdJVThub0NWdTRtdDBEdE5NWURt
            VFhXRkZkNVBTRXlQMXJWRDByVWdwTlUKgqP67BMBUZ9zeo0N1pSgJNhzSxrXKDff
            /IMmAROqkTjHln0p9JgIxW8pELJtT3su9JqLbxh8COd4xMXrE5uA6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T05:44:58Z"
    mac: ENC[AES256_GCM,data:rC/NdOlvLMOAlu1M6kWiRD4NJtgcr7O4LGmV4hKvKJxxcDEiL57UaiUrRcKBVSVHLXKHNI34DgcOe1KIPKola6z6t55k5fFO/W+lwN0LfaH0bF5issejNPYHdtQyy2VA9sYMxbMGKd+0NJZDcOjgXSEIRku5fQG3PsStEFo0cKI=,iv:uP83YMOCnQUFRP50MaXGUCbFMxHFjFyHuOlBukuMMbc=,tag:P2goC8oWe4uPVmFFiIP5Yg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
