apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aSVoXNx7fCEzAPoERtnEC94riloY9EHJ85YZJ0aAGnpT/ly6uesdovMZPZuAdnG2QxIZZAosEfl/SFcvxyk/uTnQ4J3PtuEbJteSAZi+42HPwir3FnLRWCTwJfzR7tO2FhlT4EjzH+Hp5Yr4pimvYcq5ukR7xi/0qMDY9VFPHWGoIvaCD5T6r4JoghkDl0H7BVIsFQRea2EjW372OChsImv/mQxNTbOP3+kAeDn7OhWPA8m2bZPDW2jaLpRm546avybCu4VqYAzBrac1M5sBGG9eaOx60IZ8Ky98lxfmWSOPKM4uDUgV016HCZPVY3/jh0qUN4lq7nn51dcr57e8bLjPcdbet7tqnbfOSjpbEpGnLSo34k7TDqSWh7ENbxje,iv:QXcKnpt7aFTuKlqahSFcruVS02hZ1UIw/kVU6olyNQw=,tag:ONCNfIufDdQpTu5t14ZlKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0eacgmPfqZzfKXNzJvLQQJvUf+nYyhaNh39YcWcyfaWwlQXRX7xRRGWoKyU1ULbPjdGyQVn8PQtCf1RbuI/4g5E5cxk5lbopm88o90V1LqroxJ+bBOPP9L1P7ZJLI8jmTUOymRDBJuBaFK570QOLK9h3HddSGLDnbzqz/zXXoFhHbE6ygCxNCk8ynF1bCxetFlpvTLaUQjeSXHCxKkJIDY5XOluCktjfzNnbxnzB96eCu+jS3Qhebot7uAG0VSBLlozK2TzGGqSRRM+Fxg==,iv:yYyH6DMkCboljRsfXk98+kEW4zV+7GKY6h9Irk+52dQ=,tag:C9X0LfF7uIkKTIv5BsjR7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:XPRM69V0vBFS5fXb0auu5hdbzpso8LkFDuNFyIWMn7/PvAgvajni7VNsAENv6zG1lL7Y1dRZ0IcIa+Ut6oFH2m3rbk0Eyq4FQLjSBTgNgyf3mdHLuKYX+gmhg9np+I8flYiNhZd24b3ZbsFADY1U1/Huoxehzecv4HS1DKZcuOcV+vj0vgysw7L7oAXsXwbS0f7puu+EmEicifxUaP7w8SO/FwPY1f8qDYa2,iv:DgTQrMS9ANLMqRRajJfZn714ia+ONolHb4tO/IzD634=,tag:einpcTjGQxUSfIR4l7f6BA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rmwfcjtjys47397zwtzp9cmc23df6897tlj0x9m5hn55vaxls97q9ampt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQnEyTGxpL1V3NHNEQTNa
            a1FqeFlTVUtTdjExR3VhcWtpb0x4dzY0NXowCmQxb01DUTd3TnJIYTg5UVJsVzZC
            TGMxUkI0LzMyY0tjeUwrWG4zVmJETGcKLS0tIEYvSlRsbUFYZFFnTzJpMTFlZHVR
            U0JxdUFjYlpMTEpSamRTcFF5VGpkZG8KqVAnfXPPP6GdHDV5kXEvuhwi2npCaRE5
            JDZyY01r5Nk15ktC9kFWba3Eum+LsTEYNxAaTSN5SWYtm8vECxgOLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T22:40:54Z"
    mac: ENC[AES256_GCM,data:ayG5Y9a57CVaOPU4dlnHOVLfZdNQ4oEIRyjzA33Xwtogco6N9XxmMFv9SFJ9LooxeE5+hMWoBgsqjORPxTzEpVzS3wAZI0swbooNKtTH+Yt7y7xZoVlwfwY2oO0zJsp6wCbIIu8xNC6vsOOtg3ME/MhdiraLhQlqjlHvXlHZ6Os=,iv:rtfGx6pqpToP4Hacbcn+Wv7n8MQoSzF28otD5hxhd90=,tag:igiLf6udTOAXZV/MWXAiaw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
