apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wQ4Ags6M1LJyGffbQ7cG5S5nfEWfgfS9j+0BJ4Uv5B8a6RiCDwth/LpWu7KA5PkkrlS/gG9kBmdOx5erzrjf4Wb5L0MDFPgU0Q2guxZDgR62roNgzO6UJiIdX8TamkHaeHtmz+6VuNeEZPdBng5OU+13EVLTpVZH/TdtoO3s+rrtBWz5OL8cOZErgmdFLOZtGVXu2mTi8beT84d1f8MNB9pgiBNxtsn6PFjMEN7E6BKnN7OXdH6ilp0raity6pY5CLvOXeVgtdC5pXu59EMAIn+3kiaXHehIdiG7XJa0p9q4eHy4Mvb8HUxS+0W9+obWrGTfsV6Hq5NI2a1348J9yTHEK9rwoZ7vslGwSimPm+YyqED7LX8zj2gi1OAFBWG3,iv:gvhpCEpaclUWumNupQJWWIUBGoqYhnOjmB5O8TLoROs=,tag:jkMTMGvSagqXriEP6cUI8w==,type:str]
    identity.pub: ENC[AES256_GCM,data:AmQ9dOqZJk0wKr2SR3NAMLxj86/+Vmp2dLIuBfbQ+mW5wdm/l6q9LIZTMbsCKFfYL8WUPA4woVqWNTW6rBR2Ajrx0fqlHd24N2wNwQa4ZSiQV+tuyh5uI8y/Q4AI0+NWc2jRtJza1x0BmiEZNL0Z341ZL85x/c2eTEznYN7617C//MZ1H/xpkppXRAZJItFIYYvYDg6lyULYrzTJsfPfp9V7xr1H9rRI6rZVft02owVOxg9b4ocS+swOr6SMGa5z9NEgZaDM15Fw5Ut4oQ==,iv:o0mRUGW+PynfSxuTr0wiRaTZxPOuhEWq9ziMC7HW7dw=,tag:Fh4XoigOhzBdHQ5YPeuS3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:ucKw+DS0hYMpjopSG32zhjuVtNQQW0JZ4N23bVzELDB0ZJC7caRgG5LoNMiXLZIp+C2fPD5Tzs8yKJKoJitEOld3cW6v+UDTZRWGYGz0bilDascQXUI2efXenhjlgJnE9k5Tm2ICxgNy04tqvKZ4VUqHkqb2Ws42iFduvVrFg3+Q50FZh1Iq5ENRM4mZaKCz1x/8UDs6KRQzaZE/JjAZZdmoQStoj/sst6UC,iv:Np6EDHKeYKNOB6+CrH1f3STmwJo/XznowCd6pxLCk7I=,tag:bsPgllrGguro3ZCjyzMIfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc2ZMWkZDbFB0Sk9ZL1hO
            Vms4blpYZHlya0VvMWNpUXBIOGtmRXd1eEZNCm5WNTh0SUNFczUwV25mZ01hOTZn
            bGNWMXhnaElEczVWTGU1VTNxdFFQNFkKLS0tIFFta0dndVB3eW41a2k4V09PbTd5
            WmNyVlhjck12V2IzaXZaakJmRWtUZnMKpVIXuLBp/AAoIwBrxfPliY838L7dFOgX
            n796p7d+Ifhs7QHcMyHerTpOF2jRCgMnXFsjSjAD9fxKA5XwUnXFsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T07:02:38Z"
    mac: ENC[AES256_GCM,data:bsDfazdrJFENP458S9HQtib9PPbVy1iOKjT8WBqr4wzmHaDE35mZRkUpxc4y/wSKrB30KPPuR+qpRuJ1sJA6ef8Ujvtep6VvPLvJZFzQ190rPHrtpV76Sm7hVJhwtyNzUVkzZNpfebQ9npUBAjZCQNRQAYc3/3kdyDZVy6oX/5U=,iv:F82P1cBoibgaBWI928sVI3bzZ/GdEj1e7wYQg974cqo=,tag:N5Wt9NxfDhRuiu9wYjcS3g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
