apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vB/SNGJb/Lq96i6WMCrZjh4G4eudNeiRGYmNvUxbL70xqncN5a8bLQVepSCMe7lWAnwC6cvYMDp7ELfbg4e6l17rdsuQk/fTiH4hlxEitvfvoaPN/hLJX0/xs60jiOWbT0PPHmSMEzYKPitHW+JCb/gCbQNlwTicaH+ZFDiBT7oT5YdjlGnLMpDfDWVVvKa4jWQ+vywY0O8AEbDA9Lq+YGEQWshI9foHo83ceAi/dLb0RkM9jA87isxDrkPvlIfnZDQp7RE8InWY04aAUtS+b+0/kOc9kJaACkTjuHITqGoHXx6buEW9eL9+LFlSkoz5k3ogBGAXvJbofXdGL3U4QbueziTZjmltWblK6deoRECrhoIA4pgsvUIv/DhSzcO8,iv:G6Pnh1N2acflc8tVyzSILKblBcCpQ3cCBrnxq0qmKnA=,tag:zbZmK0BXeGIhH3P2lJKmPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vR8rtSS0bAK5kkqb4nF8Z/ePIO1GiyevdmeXbdsGJEUCHUgHNWJaMV56AnmoHpmjvbXVGZub3F0RhebLf68QulQlPdP7YJGxzqyuDe/iH1S8O5ddpBvkawWKiIv8A9m2/Y6/UbjRJAc/mDY7bWuHysmxt1zaZIH7Xzh+1Hb3EvvoYEtrrMCCNNj6kN5UqTSo8bv/sVnRmmiZo266XsWD1TtJfx3LaYPY3MNkdZ0kbk1y/IJtebjvgzobe10ajtDjPNFOYqqzTiKaRu5wjg==,iv:+sCnkOP3XNmmda0rP/Qp8p5/wiRikWrDMyoDI23J/NE=,tag:jz1ZyhqvAoS+VWFG1+uSUg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5aY+SeTX60FVntIszvVvZeY3R/FBxHYE+QyWc9ZW30U8K16CGkzWs0ucDndsJ+7k2B2eGL2z8F1fsGrzLSB+dPvOxPIOfeaRNBLg+c0U0AgGXpk7W8zOvDg3V3yG/KhrUaExjtb8wFkDZxVd6s2Y3g5Cia6zzx4NEAdZ+Jak86hgOR/Gd7FgfQHJqM+TctlE3j0v008oXkdezpDd2/nX+0D9lT6sB6TPOQ7z,iv:Cnywu5BxwRSXXkYI65XwLZEY4/AMu16wS6AYbvgD9CE=,tag:sVmeJU4hUsjw8puY0vp5Yg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN0x2VVRkTEord0pOZTdr
            aGVyNjJEcmQ2MmlCbkI0S2hISjJGNFg4R3lzCmZZRFFDVDFKWnJkdDlLMWNhNkVM
            OFM3QjJxTHV2dnhnRWpSWGROTDlsdU0KLS0tIGhSU2M4Ty94d2VmY3pDREJNYWt5
            VTNUT3JnekNmSGxrdkJkaEpSSVZQUmMKhFPlYMtyyBSDkVLvoFMN67sU+5G5j0Nn
            gF7KLLqhHjDVjiMfIIJT+iWCYpLiAhqXRmDJNwp28DEcQsULyNQ0kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T00:24:09Z"
    mac: ENC[AES256_GCM,data:M3iZElKFznNY0lSY2Fs+BpiU2UmV7a/xfhfBPF25mx1q0I5WDz7QT5Y6ReP5e4atpAu0t3F9zu7UUxN8NVVw7h07Pqv/BVkM1VGY+W9+kWQqqYAg6c4MdEK0b/OpaM2iEveWRltSW0UMLziKHhpeE6ZG/w0/bX0FSYx21Se+LCI=,iv:L4QfbYZFiBC79o0irq2pJ/FVIjShmP+QLwwcjKafHNo=,tag:7UI7KfF315wFljXEHqWNIQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
