apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2RaqenEGr5FS0ff4ggVfT87HnvXJo6QYsYtMa3fXRDSoJsMRxn/ljrFjtEM0pV8c9ngEdVdfRkB9UES7xLZ1R7/baqV5vPFbdYqTrxseXbjjdtNSiiMAKJFFK5OBa31mDBs2+/J7xVguOUzln8+09UepCnJKSvoEgPMIVb5p1D5upyynL9NoiI6PFLHFJ4BIu3pXacmAK5+Hv2G0eymDt7qrDu/L2LT6DAE7j3H2m98i4yl1z/luP3kwaaxH31RGEXuTsowPRFomG2bK4O1ebGcU0AqmDztR28E0Vll2B9IwWLks2iJzfZRd8D3qySjJaBtGTNKVbhtflubC64cG/5/1Q8seK88eXav6MjicoFpPjFtWSN8kwSA/aVuEZ+vj,iv:q9Lghx6DgvmqOQWdt2cYXQMbSrzBax+0swS8COMJj+8=,tag:5dM48NyQYBXKXW2fEu7sKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wlJpTc43qh/Td5bykaMufLAASJaWGOXEGKKjBWTbsgBZ5QGra0VqgKAlfKMBF4e2ykA8b66r24uR6zl3hjEe7iHFoljQfvej2gBsP5W+cZtORDQLz5KS8+B/huGDE6OE+/FeHTrUlOncN2UdmC0d6TvzuniRNnxjef4jYuzdn5bAVGQADlXt9XeiVcham3Obx5koXk2wIGfOH1+EIvQGN8MHQCOZKceP/rTbEHP2M1Dm4x8mutvqYVrh6NbtJmMSykSITovV4kHNqAU9bQ==,iv:G7FpXdrK/YWLgZbe6Om0okT+JPExAxLWnqyYsh3Ij1k=,tag:7LQ3Oi4K8z4BU2f4dON/Fw==,type:str]
    known_hosts: ENC[AES256_GCM,data:KgnvwnVPNO/r6Iva5KgeHmPpS0Mpfm0nJBvBGirSNw/7d0yyQ62W5ay/4g6aXOI/pr/s4aTmrGNNbJUR8xzlPoG231vWLqXd1l0y67XdT+YrrFRc/EjsBwop9HZ5zavLi2zcQ57iNA1wGbCuURs2oXq8eUYoBoQSkyGaAw0n/0EAlqfVyL14MM1dAPJSZ9jaBPECviWf+9gH4aw+Cf0EjRD2D1dawBOtq79p,iv:nBZlwSiEz6y/A7SoTtu2FpsAOEfNWPba/Bt87fbASTE=,tag:AIxNwz7xrWoQJ5x7XpntFw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUVhqUnJuUlZ6ckl2Tk9U
            U2RHQnB6WGxhTGNUUmc5QnNhWCtkT0VVejFZCjJIbXRXU2pDbndzYUJmTGUwRXF0
            ZXY1SWJwSDN0SlJiNmcrK1owY3NrL3MKLS0tIFhyZlUvTFdCVE9uNWoyK1gwOXhm
            MitJMGZtMTZheTdlSVpsYzdQUGErMk0KJUgFfLJoeRaHkhSMbxZ943JyTsG9sy2X
            vCoEzhZX1oYOpWlJyumEHrYE+iRqDGN+wSxUBFoGVgbK4Nwewy9aEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:06:17Z"
    mac: ENC[AES256_GCM,data:/Mx/4VsbWksv37D3oNkmCNj0IeP0M1Pk7jabDjtQHRvP3chAlOYrxQ3Ldb1uPnMO+Rpt35XekVRgi5wH45g0/PbhlQhvhK3HzbbTcqjAUYyvYAgqQqeynmF8GSMKUD4THLfphDmLsNeueE/9e4QmO40nRXWi7KCsf5t3XmuQrmw=,iv:Tk11kiFBW93AoCCbENezlDftV4VNG3g3BfWPpj8MSVs=,tag:ZfYUDlY10HWzUD2hohkSPA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
