apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2L1SWbaQEEn/teHGTS4b69u6rijLpFcJvSwV3flzcMs0DiPukldXTRJX8QZECm+c5Nf0eFq3vbQ8cXobsLxkLkRv7XgPevJkBRYE5pA3E+aqR86jdtcqJ0FTUOU7NWm0L+FsZPHQzuNB5ylIbailFBM+fChxbJijBw//04N9uluXwcGj+X3fPYhRxSm/WkOt/IdNHhgZqJjn96aJ4RBJHdWz4F+QE5fTkEcNecsrHg0czTr0RL4fblJALdYIDSKHN7TVkpq6PUX2rR++vW/fIh0uE6unZnjHl8cceN3RstQ4lsNa3SsJK+XAuvni/e5FkH/r1c8/4FYJoPpx+VA48drTCEVlZQ7/SqKL6Z+Di/y4Rj79YGbHOqkRWZn2b73c,iv:/MHadb5sR0O9HlRHsz1tJ8J0m1n4fR7N7/DdMiPRJ1M=,tag:ZxgCvzESv/h1SzNRg6P/uw==,type:str]
    identity.pub: ENC[AES256_GCM,data:NfJ+Qz+RUYCkCqdXEPJJ4nciVEqRB6j13zYcsxO3AzmCjq8rZYdUntBQLS9+fQka8h1rFa+oY5pieizW3uLbB5u0+x2fEwlpYwxfJtdEWW1xcPfBsZKPsWRi02HBXFMGG7UjVe7vrSsBj4rn55B7sRdEyGwyakqN/eYaQ9zR/nwYkWn0uj3xFlz9aDGSjg9zp76fttQSevu5+RWmb5Lp3/oT9rvYjqBFso8wzY/XBwx+EuW3J0esYK3aGFyV2YVF1FfAjuYTlWzXvgZvCg==,iv:1vgpcMH4Ridt/Ee9Cxg2AhiZEEvaCP/iC3Tgv6NqCmc=,tag:+yotnx+4OzYmcVt04T1jhQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:bzTAtfP9FUI0/aun82AqGKLOppRI59rrkP+94dHnfbONz+M/kQ1ScpQWcfi/tNKt5vF5MFO4wg+K6hrPAUtvoMWRHiakrHlamc9Tz1FlxEvI+IJK0MqC+UM0wUkfEUUDOFHYQ+IbxtnKgxkuDxSFNWduar4GaBkmYhR6ZCqIX8if7l12Tdox26BxJIt1+l13WNxY7Bc2PLhyxuOYhe+2LKOihgekY0x0XZLg,iv:Laev8xuWKecOA7KAuPuNqnpzA4Ut/k2YSQtCxSB/VHk=,tag:5XXPnADGJ2Y7MqTOYcCwnQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb2lWUS9JUldkVnl2MllO
            VjZuNU03cVdDUDEvNEJFeEhhbGtWUWxVRldjCjN1RUtwWnhGa1pZaGFod0Y0SzUx
            c24rN3RDWDgzcGZYVi8yUVBOTWhuK2MKLS0tIFozQ291bURxTTdBTzNsSC9NNmVD
            ZDIyRk9URnAydFdsamJVcm03MHNpdm8KlZwAXW8NEHNZNfesmABBmziVUJlloAMs
            9c49Cr1DkN5WMeR5g13DwU8g1SkIyTx9f2u5Vt+8oJcOZXqqswmh0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T20:57:40Z"
    mac: ENC[AES256_GCM,data:o1Cd5OjtnsyWCVXDlmS+gq3VhiWtSteIIApZu+p9LbkH1tcRcFrZcbELUsbEM6RhWVnmmNs16NDRXFpc0lukth2716NPTTBWi+8t7ItcgXNgWI7610k/6fImznoKqaaSLTWqFlscW9BK9vJuQ/pbUunjMss5XBmi3BkKRTtnD9I=,iv:25hO//VB2eLQf8nnEQ3+AvdbwBiD9NNWmTrH2VrunHE=,tag:polO6zwUxYhGemVD4BYmlA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
