apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K4BQGepH1HWMz1uDkkI8kI7K0bQu2vvIxu97KLCvYiDZSmI05kVenrPWDS8Gocz5v44i/mBsB0aDaqIeWSxOS9SujYmxs5u/mxphaKgG2sMCFPEZdb7xvmx80ikMRN/kCJzUK3/cNQNKXG9rohHpSTkeF8zm8t9XhaRjro6r4AOa0I4xdwA4d+TyrQgBDCCwBUW1A9TuWKQ5kKIpqSPlJmyIf5p4gKcv+tYB32Z/mFSHORmyhhruVJwjA3jbxN4YgBIKSC557c4lLwZQMYOhIkm5UYevmxn+1SkmSBsh9YHUWe11njOCRhH1zq4w4SexUC1axDCKxg4u12Srg67+48FBGgzbwUB9ApqrBD8dUk8jdQ8G025pXw7/Q96fw1ZT,iv:/kN4Xlq1eHuFGtuQ+S6FmCAMw59hQaGWvnj6Hzn1YjU=,tag:Mubt2yHdPzsPFTNIO7W28Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZQI7MF5XIs9bnW+BL9JWGpzy0p4W2bLhtLnbikq6ob0e0mlCkdhBTp2IrjwXgkv91ni7Dz00WeRR7Q2Z3rXynuWf+h2DQ6387hTIiQQ1sjJ+MaonUvkPUq79WehO/NShvg+pLub1Dj+zVziLjjpBsJFZSSDH20K0v1/jKtjjt1mSOEzE0kbstlrTkXrqfBT39hyyUh3FWSgo0Izr6sS3VrGV4+2slQHZTovrFiAS/cMI992Kj3u3ncswSzF8Rg06M8Dbyjz6ZuQBmBNNIw==,iv:2p2ayuMkCZFUBaZ6eCPAaa7DBAf7V+cdgrRlb+ubSd4=,tag:xvOXUor4yvBfwkiZE3X1NA==,type:str]
    known_hosts: ENC[AES256_GCM,data:iKjyAktXXjNZfB+qMa72X7MlqdDVJZRTSGswvtK31LDvdHnoFr4w2F+A3foVLSV2jVZIZIAx48S61qSxcoLz4oSbB0MrbsROhZjcnrZ1lTSlfAwhbabC4NHb/DvltMEFTgSyUuUR06wySGMFLwcxESiQ8WFlLe9fEW0Sf15YtY57U3A1fDt3DjsTtelivwNNrtUXz4OBw/Rur3ILeLw6w8MLa7w22Tmb+nYr,iv:Jmp4o23VW7Rvo8pZmtIkPOrxp6pPP6hnUNgc6jllkpE=,tag:kvj3H5HHbbQ5wGZIQOj8vA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NE1CcjN0U243amNJLzdE
            TFAwd0U0cFdrMXJLaU1DdVFDZFl3OXAvZzJNCmIrQzhyZGplUFNmQjJkQVUvamhX
            dzBlTUpYNkpFaEN4MVZKN0p0enlLOUEKLS0tIHYvSEoyZllOU1czbFlnNHlncU4r
            ZEdtQUpTY3RWaUNWU0dYMHJJNTMxak0Kwhzj3rtSearUjWYe3ltZzHacDwulRNwf
            wx6imDuEI7d/9LNOWn5lTAAvJtevIIUy++ApbZJx+JrkCK2wGZhNTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:27:57Z"
    mac: ENC[AES256_GCM,data:tz1Wfr30lNtyOtEAacn/P3Y7gvpLJUuH8f7BGL8h+llLFJ9ZoWLi/kjgB0/b+voVUlWQlTM+RpomIOwWgWIFpL0V9Jl+s4YujBIUra8nbwRncS75fc0Bj41uGqpohOQMieOmzfOXpJcxhW/FZxIYrnTPbSxCSvonxJT5nJhHYUU=,iv:C1dE+tzO2AdVk+W7a7LqZ//9YGDDY8Btnl6JLZzyu8U=,tag:oOpBLPbmSa6Czngb5QHLvQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
