apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kGdX/7zpp6sFWY2qMq0XqAFnP0803ggy/HdLv+AdCp0o+l6H4uP5EJzO1ikmBUpg4vxd/xGEIAvgI8TQhwOA+xWuKmWoL0HiE5atBRCx8RNwG0e+gwhcMU8KGKoh9cwaIK6s8NHi3D4U1XxUGnZkkMasXxTf+maNMemq62vr/kWoAeF/0M3THTt01BwHSAoGEZXnr9xx0GCW1EyJd+M+TRqZG3R8q3SRZtf7zwI5pqd9zPMt9D6jWYLcTtuhV17yQFcFdp5r22z+hD2Q4fhgTtFCIAxnrAZrPsLhk6JdUA8xTCmzqogf6U6HKRsFCYSQYo+jDVew6C8mZmWNbcKaZmtzIN3sQXq/aJb/w33zLGHmuwL19q38HMqMgbzYvbZa,iv:7XPb2NAQkZNSXFb47s2HQ+ZUpWR9HBib3w9j8UaOHu4=,tag:d8BnMeuxkfe2i3yNmY2ETQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:/OLArjq03yrjq2zQ4lIITYpF1jKNYdkMmCea4osb0H5Z+eMqFMxDTRzuMXnHMqVDNVKczyNLBKFDqtFh7fmVasy4+ivOZWPcHmJEkR9EXN59L9hpF49yz0iRBuFr1v6k0WLA2QhjOuDD/I6A6GEtoin+dPfzzSCfB7ONK7QOxMwFLQTP7yUj2cgE8bwgNcxl5dq2MFCIVDo6objP04AP4dPi3rxOx0LDu8hA88D7/nbSLYRHiyWBd/JIjgMqGLO8HoVWU3qEWHwF1WORvw==,iv:gNZumOWImenoxBCbwz8SGnf+AFshKC1W4/k44HhzQ7Q=,tag:46jR09BOpqAatTV4Ly3Ucw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ldniNOGrDvB5b4s4ieCCH5/oVUkxMJklJTKhxy4ea68ETBlwFTxTvwbE8rONdmuzc4jNlfD7UraS+dheWXXweX+B7iBE2s7FRiSWf3X99s3moOGPBDFkuG9S69s4eb8aiS/AyxI3H8RGpdKnfZFfe3pYTEwfKXLmujgt46VmcFV3MMvGkIiCqCWKc9AeHplv7DZymTuQ4Ng4TThklNml+aW0Gfnf0npqkRpK,iv:Qy0XZ4BpGphcKfPmpjdN5el9b7Eteql6fnjV24Mx2tI=,tag:gTPLF2D/KqA14aEKLLXsZA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdjBwSUhLL0ZTWkg0TGxE
            VFQ4Unp1b2p4SmZoSDU0bFFOUmY5eUFXTmp3CnVRVzgwVllnOFoxc09wTmM5Q3NC
            bmVSZ2tYb3pON3VkZzQzZ0lhK1J6NVkKLS0tIGpFMUtHaWx6NGdxOWdja2ZkR3lI
            anRxQ3VWdTVFb2YrVkFFY081a2llUTAKs7FctshRM3YbbdAVKcvQ8LAM5SjWSlrZ
            fwSeCtrokou0zu++AAoe09NXTYkKje7And08WhhvNBEWtH5JjIOG6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T05:59:46Z"
    mac: ENC[AES256_GCM,data:pcWVvyawgE8uJDc+z5gdIc0QzgR5nImViedm7XjIeISANkE6629KfS6njdCwA4KNEJPT+pfAdBUEBQ7oZe+UVhmXXYa3xXq02d+MvdZvBLYPVt2JeZEGoWeN/nIKGQHqujuR4oXI1oc3Nznio+ZWyyYIhwCH+qZYEhFRRBmiPOg=,iv:EzqxfUIfxY8JmPL+RQ6o6O22mrBqoM406/T7GnAye5s=,tag:QyeVVGoKH2d7//+ZLyGOug==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
