apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:blMMCaMITAmiOR/ikITdD+Mk3h2BBiS5/ZDexYFEIqHCEhqhuxF10YlipqX4/lHzL6ODSK8VO3/lt25YrBTLCXlA/KN6o8qIRHi8v573H2a2WL3pKK4tExSUeEpRnHMGR+rVQu3RIrkwhzmXwSSeOEsHvIaDqUoct3SNZUJzmAfICmKpYFIwpQnyIo24/3dz29COoSvMTZ07soNGaiqJavUTGIXQkghRq7iFp0/tPMRoBWh19SwC+NkjXc280VhOUPwVHlol10PiUJKMhyiwR/KxPAK5XLzJkJJwgnnjMLygEc2tiadUfxud/oDRi1v5pifPiMlO6tnLSR851svsG3IFhcRas7o+RH3yxhIifJhyKWyh6x0ciHVDKt5epn/s,iv:/jbCW93jcswMvQlrJNmq9NpxbJzSBnCKsC37q9i3YMQ=,tag:X8yRAZuVmWYVXxb/ll/JPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hbaCdN3gDYi39AGfoM+vgNZACYQpvq1P6pquyDm3inTFuAx7kJdEhF1hPbcC7dNl6hNCO3XmIJIt3iV/IbJZvWMLya8shbEsXERlIRpgNaJB8mtS59ay/LLVthXiTW8xQuGjRUdMh0yRobziOn+odx7b3KgXFCCGvbcDVY2bLpi/pgRpIKzx/nKRYIVwPZVZ/rf2jJRO7NM43HTFFeCttXAt0QHpX+BysHIOVlyxGDYkgSPIJx7W115/UWc/JYpS7Zod9Eu1POGQgJdVlQ==,iv:W4rZJGVP0eROw1wJG4dV5CvLpQGhORltqwAlTVvbxIk=,tag:firzwzZ5hRYUWRImdZgAJQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:lkbL35nEe47x6bI0yKcfwujS7dnYqMQWcOGkZExDKG2J5szqTy+YvafnhA87qf7Nx+rw554LVVhTaiEpWemiei2xx2UM9ecaydq/uqC4MNWa3BI2yFGMg7R+cbAKrL+EP0YOI+/MkchtgJxgivvK6/tQsaEXZDGdkQegu+erXAVFlL6MMcEm19iVeiNH3irkEOma55P/BJFTr69qhWWkBks9aG99ATOL/cuJ,iv:bBV7jqzRKOTOSrxxh4qufg5DnIm4bdB1IkgoXth+944=,tag:ihzqw3yS1ihzkYQ6gx+buA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV3pGME81eVFyS2F2RVVo
            WjltS0s2NXYxMjVzTEVDa0haTzdwNUtFSmhjCnlLWVk2bkdoQ0paN1ZJWFFQb0Zh
            QXYxMVk4WmpCRU1BS0dlaENJZXB4L1EKLS0tIFAvUVFEQndrSkFTVmdrZ1h1OXI0
            aEhCSzlwUHNVS2VkQklTUktHTWZOM3cKVYBn67sHjSVaV+GS8+/r+9KqREksBtIO
            i/vKS5dmGg6ImrLSD2C+imlhgH24pXbO/oc81BY5q//8/EujbZltVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:39:10Z"
    mac: ENC[AES256_GCM,data:ggm02UTCnOkFZzxvCGwRNVLVPfeIlSshAOnAgtKC2nwRJ7PpLaBQI2S1SqB0OsA4PUeAhllfB/7m+d/1XWKw8V9HA1zoA7bNJtXrr687q1xgtsE9Bg3qD1b6U1VNVxv+HXZKawZtlzDXEb1LJarHwWZWmGE7U9ZBaO8cklGCXPw=,iv:OJVv0rD46bI29ZKKAdicMskpc5RspNCl4VMi64N1Mpg=,tag:n1NiuJIYS0VvHclOjKIWtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
