apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z9EFd8ns3qHZKaE498GVMI6xjLPR4nyioOJMvIEnCilJd0MdAvD7RchySjS4VLBEmhODQepf+RxvBJZ7gtEsFmH9gxbKwk9J+XBFuQ3WxfZP1FbWeDBbY9GR7BLc93CNvFDdXUA1SdXwkXKyvoOuVy0CDCiRpQHllQJV6tysQrwhZHuNTPtuue0FeXI/0vCBujViEEmR41NIuTC8SpN9hiNHntcfG0tptyE92mf67I5gUcDq5ut0Y2kJEtCQfWBtv5jxi/gdTwdExktmgGCrfrxCZPAhx7aGnG9GzgEQXhihXnMogG+Flz/KwESs6oooLaNGo9DqfHygmao/SbGU4AnB9WLqRwZXKajPcSmzRwUrqS6+QT2LPHUU/Plbawpt,iv:uxSwQg1TK+aJNlEU4KcGFeZudDsqophmVseZXzmiRpE=,tag:PcIW+hGUfmxwthaaTZtLwg==,type:str]
    identity.pub: ENC[AES256_GCM,data:UYud7hFDQWXjNvC8Cuksj9Gu0HYHs8CeWBG55yCCBjzHSaJNW9uWHu6geB+Emwvw9uNoTvycXbKhTuVf0lKp5nwTy3DZ7XHskahIfJd25U/EfHIr82f0u8sd9nagNiJS7OH13DiO6/sr5ASIxgUnw/1DJOQEvn99lzMzegudR01IdQo4gsPa4D53qniEl0UTH7wqEGdywaDNdUqzjL1pe6EwuRhpLCnjTIjSGp/5dpRwHrgYcz4sFDq/SGzr9ht4ZeFlpzoMN97fum4ALQ==,iv:nVAdVH8B3jtvjJVAuRRhkGmw8iv+QN8oHwdLfbQti+0=,tag:tZmT818UQHQmfwGuXDKDtw==,type:str]
    known_hosts: ENC[AES256_GCM,data:XIN3FN1/O+u189CJ/9gBdzR4qz8Uc7KFD7GQf1y6xrMZT7QQWqcYYfEcL6GCZM62ZzkcohljAYG1ck64620FSXYkx3yNTG3qPPgxmk4FPBUEeoctla2g4lx2J3p+ZDd6oFrogkKmy3fTBH+8jfmfFJI8ndvpUe7TUKfRGiQsE5XJhb2DOy7zPcr6GN8RoF8YiEk7QOeXAwRWkmRLK9jbcFaTl0NJZ2ORSb0y,iv:ZgMzS0cxYyqkiggcOhbRvHRoke9UMjJhHpCwxHYQxfo=,tag:/xVcxznAwr65LE/PsNG1jQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva1ZPbmc1Q2dIeEpEZUhN
            RUoyKy83RkdSRzdqZ0YwOUxWeVF3RXNXNkdBCjRqRXF0RFlDZ0tRVnRtQnVrZDhN
            ODE0T3dIK3FIUmlkN0lPT08vWmZ5TFkKLS0tICtNcURIazNCVGJRVUJBbzlaVFJW
            aVZ1bHc1N3JScG0xQWNxTVRDYXdHSmMKs3klxR9kTaI74bQx3tgTTfrDYLq5U5/u
            hwZFXW9FqrATK+H8rbVkFXi1hRa84v9fWNTcY03oVszwN5xO3UEiNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T18:46:48Z"
    mac: ENC[AES256_GCM,data:aHs/H5edMPvjgGO2Lah0JBotT1XaOB7+i1qi3WwV+eS8vOwOK3Wze/bcOkHdrpTkgJb0uJbYgkqlNY0YZ5+y14Uedd67atF1Cc+PjcYGxth4g2Sttru+PabJzEt3NjYb3YzhIDx6C6JVflcE+0R42eko1ypPUxVwio8cj7b5Dgo=,iv:6Oq+7kRmP/N66fyVD6AjR2LgvP5Q1OUjsHFqU0/TLz4=,tag:5s0NHAPSpJnYCAxunJ+Sog==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
