apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ladcBjFW2sE+Pch87xFqCZ40pbZuoZ8/CSZt180/8D7C7oA99vzMfY3TvUlV6gs9TEYc+3yfldKQ1gz0/UBAzTBL+jJwpne1eO0ufWqMmt3ZrW+UeKabffTo4hZh75Pn//eGRS1pZIYTd3Hd4fD2TNpe1T2Hw5D253cm6e07pxRfKgzhFh2v8fNkh5q+bElrk/Hd7/4pw9NOg9VrU+rLC5KMqwAxi4r63/Y47/hMUm4matxGYcFfxznOolHAb6gdKFKPbcslQoKaLDGthYGqHFEUOsrFmmS5maUYdH+B4l5JWEZeNiKiMjawOSIhALPWfX8EXUUIja5VtZrSkoBds6q7F4ztUuhgk1fUu3F+9H6kLZYu0Z1Oy0MUCMu7Wk1F,iv:5e+nOay2wuQyqEPidwMgAUCZ/FGYh3IGuZiJxwQmdfA=,tag:AYM5Fr1YWcNqsm4EUExJyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:eaT0rybDupBKccNfVPYkW5/RaXH/fXay3UAme3qoDem0BRNMIsUghNI3BANh/N6Qa8fvPiVr50D2XPQrGr3zJdRjrNHoTJhHy6L+rlfxWTdinzVIcce8JIjUSGqBlpGiY3Lz5aBzFzXucHsgM/auNgvn+F3oJTM2kBMJ9Y5F0rjXRszjfjfr1L52ajZAjVD30/7ZXcIfqR4mwyGrhZg3NxqRES7jl6QWvZYDfDP9DdTWBqFt9A+vGy6sDwGtSH2mSoafeXo+snUsGhcjOQ==,iv:axFX5cAD7qu7qgQwCMgcu6k+ZPLIZv2mH1zNU0lR2Hs=,tag:MnamXs6mf7iS4CH2oneYww==,type:str]
    known_hosts: ENC[AES256_GCM,data:u25V3HtZERxqYtUh363hshMPlfQrQWnIuhF7sclnJVMr+lQ1lgYQedIOeCJBK6Z+DOD69iYzxc1xnuEwdstZPvHKHMJvPjvJyZyNZXJmR0Bh4xQO6b5K63PODzo6DhjFyiCGqVCn3gI18C1zWiJnZdVrZZPkrIRGVAE/ZimpZdZhD+fh3ny8tLLoKLlegUNSnRUeOyWHjlpUD8POyAiQ5dt3HIFCCncIGh5p,iv:9MBiH+caxTZ3yQy4Sbe2W8V9k9lr70Jst9nPJxhxks0=,tag:ULtGA4xOxA8kT6LrTN7yLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY2M2Q1p0YUI0bERseEQw
            VEYxOUU4UC9YUDJXOStDR1B4MG5JTG9FdDFVCnlnUXZRZFhJeDJDQkluTDRyc1dr
            Sk9QRHphRGhtL0srMHp5VUtmZFE1R3MKLS0tIEV3OUVyVXVxWHFiY1FMK3crMC9s
            b2RWTGdXWVJhYnV4MkRXaWRRdzk0RE0K+M2UXyVdN3q545yarrsAkhU8FFvQwFan
            JonXMjhi9hmmzAie+tOKgvlgfs9q86JfMF+WLpma17dOd9z6lmFgGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T19:15:32Z"
    mac: ENC[AES256_GCM,data:hkFt3oEzkNiDDkIgZR1lUqOS4ss3L3fUgX2W4IhrUjrOIqzkISy8A3FFtMWfO9UZ1Zvd6Gh93ZrPvYdgGIUfh1UdBqzEVPIyXbam81ZRip6BMdCPXSHlYEAPzhLJvHSgptCmRYG1ZOmW3qw+ahJ4XlJLBuIx2LRnxRhK4kaeANE=,iv:Cndxv8n4UPEQY18wBZrLiOldktVcy6U9MPoeuNc376M=,tag:3ZTwRfA1PeVKyxXSrAqCmw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
