apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ndk5jc/zNAznQ+A2CpXXcEYn85BpVwR7UlFz8vCqeiLPZIbqYbMFLIj3MhekJEXztVvEXIkCB/T5//oqqJGiMiiKdy/1bn/A3WOGpvOcxFjvsqd5Us69t00g1h0qtTJiiUNo/Cep//suvqcI85uZcZjpnG6zgBQVha/zWIQZ7XinsuHU7+ktKvZZxGe2Xx+/Cvd071Ivb6qSuER19J7b3IuXD9uF4WYw2CzLj9HtWJQl3vcmoZnkvatUAefKnqlMeRDO2GaFj9C8KzXbIKBqQPs3OCIIVffimZM4e23fUVBqB1HeIhk/nODSlIHEBeTRWn04/MwZtCEgvbeSV/oMGrlYM4vDD4QTz7lzmdW93vMhFPE2kvP+vhVjsdlzGwkb,iv:9xmuRxsN7ZOuTrEbD3mGeauGP3RFzNEM+eiNjzJ5tMM=,tag:zpmExlrjftrqjfmF4L0V4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:2999DbKhLc2UCZ4M7M20JBtzEH0VTzfiCb/znJzfBvHoJRRGJLtJaYwtbIwNNnsX/co+1VScLWFCHTxV96np3NItdgnhGbOVPgTTgftND4WCIyH8+TcyX5X5Jrr5MbNNQspv4LdcFOR1vuGhQDn5BZXnTckqMBJhkHrklpTRIJaYZR/Z4dTMK86Nx4RYx8aMKJnGmTVwUyLDx5uBmMWiPzWrkUM2QzDnjVgvzEiIAuIT5GP8woPgCeeqG/k4YJxZSCZG1JTV5eA33ICtwA==,iv:VSCNWkDKi4JBx8RX5/xhCDau743icXmw/3geIp29Nq8=,tag:9zatvSPHSvlEVdXfLJMFbA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Kapc1zFEMn7YhzId+LfauPLlmwQGcZypcAVOWbqkcVeh+UTIVowlFeb2Cm1Pgx4wseP8xgWojP8ArgDE8uYwrYZgF8Zs7Ix+w7ROaACT20vWTDo+YjmSeiXWPXyH8wq1EGwoTBc507vcJciPXHq9uADNmJJ2RdDTaSWK13kDs4ToGHlAFeO2pxOVunRB0J5XlBztn1bsKnARoHJoF9OZGXmnWPfJsV6YrIWY,iv:gcsznixrr86JGThvck0A+vUs99hi93c2vjyCtPBP7BE=,tag:GkbNqC2JRCrShgpmsHk9Zw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMzA2dVNQS2JiNlZZc1p4
            WWNlYkVOZitycWd0VmIwbXpJdFZVNHNkMlFRCk5JbXRsMzhSZ1J0SDVzRTlXMHRi
            a2ZvNHBXTkdKaU5CS1VsMzFPdTBWK28KLS0tIHlMVVFjanJTZXdHUzNHQk9RT2lC
            ZGJCbEQ3aFhBekxTMVRLSmJnOHpvd2sKszNdBfR1JItG3GxOyZnnAPyrWEkB4oMN
            8QREph/LLu+0VAPNOXN56mWLlIqTX9YpfzcS/mqBGHQ8JurWBkJqfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T06:55:41Z"
    mac: ENC[AES256_GCM,data:TqKQLptSi5JXApf53tYlY9K4FmLJb0mNHTuQFKLLxKUTLWiYXkIda43CEjmwnV9DTFi7F7hgbIHJE/q4dfJKAAt2DlwyJ+Pie5yq6xtftw1/hKmoyTJZCpsPwxbMSyUOOnz4ShncU/Ro9V0bQlc5MWPDQyeQu901BKYTyXntdgE=,iv:a1rL8f1xFHIaGyBNAsn/KvSMLHCYxTxUj/TYwh2XYTc=,tag:R8CdFCes5aSFQTeGfHrMRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
