apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:F/quzN1ITaZA89A7pB+UoeJCN07W7OTRBIP6MMimICw8xnag/UdBT7Qnpqx5ccxcSJJibYd8pTGm99BDN+hdd3jeaku5KaQUj0plL/IBCMQroy4dvZ0R0CVNNVwLYkxXDtH6qQFq+ObsB3erABZPPyoAJt0GoD6ZY17yUSG7ILqCNs00zAUUm6odwMA/yJVZ0VMrNqP6/qack7vbAEWJpgQV/4QCKINH5YC9+XLiGruwbtYNXEimG+7ONIKc+/duZxaKDzlLEFqtA1BwK5KHLnOhosYXuF2l//mzmOkudGpi5daYucxfg+0j6DAgchXV+qadTE78CAKp4JWIWif0GPsHe+YMaIZAfEU+B22UBGAWyI1h3Xn07plJpduCu9+6,iv:ans05jKqIMdFk7aTFV00f4za9hIw42IWNOftN9etPL8=,tag:l3hhJaLucPMx6qVFxST9SA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8PCzoUQCfwD5bRURGzy5L1IY6MKiqOlw3C9XY+efMxQ5xz1bquiz50YOvxVQK4CzlY94lPgNIZYoIrEfb4xgRNvGs2DSXHw+gBe2sdxUdUgpf4AXvFKTkxGY8kLP+RNgvT6T4jm3ETKRteDt7v+nqhqDBuqFpGoNyrrYLDlg51GRvoy3cXW6H7HQjUu5eYww49MEuMvQ02YzJDUXlnkKYU8oyIQAdGXnfHAz6aI/YI38A/obEa/LP8qQ39f9njBn/jEONKnW8UIEmXJs8Q==,iv:Mn4XJRDOX1xDO/NS0m7eMci/jlQU4rI2DTkpt0PwjiM=,tag:fCyV/d7QVsEWDCfF+NchhQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:WRWKVW2WbD7U4RKiPBVZWk+0bwHuk/Bkc79EfUTZOGoyLp7OadpgHvJdwo5qsowfsPpJ9Zzy7fLKKTyg/eTjUOlMfIkFKtTRojf605fvP2l1QQ3jXUAChT+Vp5529sEuCa2GKmRzkmeoJQ49EtUX2vjABDeiyZDu9pq9eW8lxilt1MtR2y7KoxjhXpdHB/hurw5Y1ThkQBE+ZmVdnzwnV1Nh2jOAETn+1kW8,iv:kC2QNflo+un8vHZMxQTp/dkyw+HMgjpVAQaMGw/jSyE=,tag:8VoqCivZuIKDSpPNOK+0Ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaVY5L2Rya01nNCs4NXI2
            a3ZzcHladW1NTnd3MUlFTldKUGZMSm01a3hjClJUaGJvZFp4MjhxdVUyajFCV0dP
            TjZRWC9BL0ZqOCsyb1I2MHhNYXNQUHMKLS0tIHFxdDVPOFk4Q0NEY3picURSMVJX
            T2E3bTJRSmY0M1YrcllVMitNb1RpR3cK2kkQe/1gSjnHObvrvfk5258OGfwhwc+K
            TN13t9lDdwt2fgKvh19+JhW7+QsW17OR/MPl6kffJqa/qsWUJlwciQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T06:22:07Z"
    mac: ENC[AES256_GCM,data:lY6zFfYo0Ohpe/Cw2IA0FJPa+LP2z2JYBWtQh69eIVUSxHsSjBv2GOgnPvWViFsgk4+PPM35UEP0kU7+Wcf4MGXo2y7JEhAznRp/3bGJxSiPu5vHiXpors/iRMk653AgBxfR/GtLTZZVcEFMGF/o4wCy8Jvhuk9oX/jdXOyc/Ek=,iv:cstBqMnzLW84WK7ZfHAlhN2Y1gpxfTCwhX0pTGsihv4=,tag:mU5Ep9h95IP0c19DQ8dJZQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
