apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ujLg5dC/wdhXN28qIb9zTvZ8wEW0ckf0TcX5X4l2rnvBobkvNRrDhMqK1RB2H2dx6v7I3GF6seoVT5xy2cgjuxoFV2ceSURGGPqxiv1cPKXhuTfw/NzZZeYuqRzp8kq8BBmnRcGucYNcpplJ+b5Y4QkPATgy8MzV9JuOB44k8yji1yjWd1wUGQAep1H1lKN5r/VkLiyq0lAtz9JGVlnPBR87Fx8YfZFLq0kAbr2DhLYbuaHbGfowjepbQDab3RZ8DOYOIOW0Eq7US09pQdZz7sbpjfj26Ehaxfk4g934+Iauu1JCIcXHqWlGZQOZvQmIZXqMhQC3/QIvb2QKf0M190f/2FWFjY9j3Kw2EX1mVnVtOaju2/qRY2JWKrI/jA/b,iv:BB0fDdyDDqw4FI1OkgT3MYSlraoqRwxHQNP7WZagHmc=,tag:3XHwftSoC05V1cQSB4CpRw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+7uIr2TvRhVDL4YT6AtBoe4a1FYXnDDhbzJ7FKE8KbMgO4/YKW7jS2py4dn8rntVG8gazB69n7gWpXnYixIazxgwKGDBzJpbZ8Vb0xNYBwJUA31WyaZnCxwZLL7UVxv1HAxnTh0mA7UbvAz+wLYUVc2FfhL+vrpNkzt/e5lgtoSQ0AioqCl+3Qm+0wMz/RqYfTOAeBp71nZvfxWGDRswkcrBVEy0Ek7/+DRGV3mHaRYGdECc9gk5bWUfEuScsLFlHtBHXofAdckwCfutpw==,iv:SVrPMdb2w7Nl5z5vI8289IlekD1wFCHY8yPRXupNYAw=,tag:KUYQMkw+GNPqjxL8FeovZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:eRNPaUgsJ33HJkKZBqUMmCDfn+VkjrLo+rODbMzDIDNTYbc1/NVcTLtB/uR8njxrkntFGOvE4QpiocUFAc3o+BsVPJURu4EhNbyDUNottmzQ3QnG7vtCWs95d3cG2TveEHO8WeHwLEFRwiUdGvXk3ByGjIQJEKj/sXeiGlQBFF4iYKwUVbZwDsL+vx/QqZKQleeeAa55VAVGa52gM6tbOzSv4vFhwuvS9oJ+,iv:VXtMYe+/BrRD4f4G1FUmgUe+cSPU+Fu4RlPs6lGqWMY=,tag:zU0VYR3o20niyp5dboV9BA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS0REcm1FOHY1b0NxYnB6
            ZnZXeVp5bnNKandwd2pHYVR0U3RITGxzY0N3ClhkTDBFTmplK3lDUnNiN2xmNWt0
            K2R5T0R6SW9ndDM0bXZkaTloZEFQNE0KLS0tIFVFYjdlWnB3bDFWSXduOVlIYmVv
            eFp4OVJReXR3RGpMYS9uTVpYNWF6ZWMKSVo9hzuD6RM9ndLSUZ8J202SC7IFr/eD
            eEek4QaSoWNwMLcKJNYyTHhgdK59jYvcrgG84mxcx2IK/29/LBAR6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T05:47:41Z"
    mac: ENC[AES256_GCM,data:Hk3VEGNTYntmD04J5Y5Ir0ufID6ym1tomkZY+3BDZ6pRu8gVvkAG2e/c/GYSmrLkvz7J8SraMDndV/zZQ88jVkKBKp0BQfab2U711yNQ3Pf5HMudXAcNAmh3UwHH7nrfMgv/NEZSVcGgJ0oBH+ktwmbDut+Ib2w8lBRr7xMO2CM=,iv:l8afqOGJS9gMVEtXqN4AG2mfqmZlPn+FaQPrJa54nsI=,tag:q9eQhrw45b5I1oM/HALUAQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
