apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OnrW5E7ztwOJIuqwslUiRlqq9zECuQSXXpgIpfePSRbBcudU6Wj3aqbemj/VrT+OeeXpJ90J//Cos9XX2R1p9GXiWmmciejhPTvb4yJuyjFDydXGi1SuxnFJZKvhEeqA3lr41ovCfJUQr6LOyekRIxNFet7iXEvE0J7RT5M2pBaplcKcY1uhfMyFrcTigPUIOzG9zt2R5/YpaDczQmgjhWmr9U2aE9pVv7V7Qu9QE3I13yb0pVYh2tnduOZplBZEe56Bitz5mu23Wrdzss2aj6dUNF9vWJxuspRa2HCcy7+WiMYyjLNTfBXlfUPRfwGBxQpa4Ln5Msa2cPhFBkL6Ho860RnCZC2S9XAMNjgWvKuwi8u/PEDZDYARJ690JuGe,iv:xpAGAKgQpv9PwdSUWHlh3XdF3mETAp/BjuSug4yryho=,tag:TpV6wqj5ClPh1KWas/PssQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Y1Q1QaJIDEt7RRvQ1AkQCDu0pYYaOE05hlc9jfaS2tjDslzHrkRQWEnvNOcbGaM4EPWMmRuYpRAr/J/hkbk+rUge/ARzBDS6dJqnJAewWhUr6nldXkP7WkAhFtzX4BC5v/n5GQv4PnNpZAJ/LmKyvPVKxtM3JMOCPa0sLEgMA4OSy3jIpTmGBqn9xjXeS9BY/eg+z/UcycSABtEBmxBNExBOa5OcyO37gKp9G9+txSgw5e3UyT5Xd2KDiNVjRAHyTPA2GVi57FLKtjDLRA==,iv:Tj7NL9pL/U5zvymZ8CrEEntpNSY3u+IWCk/fmaQI2d4=,tag:vUcmQUeOHRMXJILl2qAg9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:jy3yKuVSDxhaJSKVxuNoU3GsrjmLHXFchky9lnOFZo1dy+7B1GK9lw8aHDx75XPPkLGGB10M3UpzU4QmmgfwAqj6sjJr58oaWltFzDBm5AwAJnL0bgoWQMfFtbL1gzx3wkKrzdMAxX5dbA/ClNKcqy+3v6ptqPUTohwF1O47829Z3sfJXFa+1uYJOf8XSWPVO8bUvjDERbL0oP/8tReIUa5ttvPOqZhduvLQ,iv:BkXERWHhXCPNL6KPXDqaaxlwSEnRLkFjPK+0cmKxMI0=,tag:atvFOuhwXqnCDMc1KbOuyg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodjV2dlh1SmNxTDcrcVhQ
            bW9tWkpoUTlqRTZZTFo4UU9wbW1EaTdkMFZzCmhEcmRseFpSOFBubC9pMFRYWUNj
            NythRVo5MzJkbEVLcWQ4WThycHhvTDgKLS0tIE5veU1NMHRrYjJpUG8yeDlDTmdw
            WGloL2pRZTZyUTI2S3NiN2l4UXExc00Ka5fA002qOxVswgIkduVn+qS3mUCSQbSj
            d8rMQOrUqmReN5wuNxspLBLRb9nHp0K5r3oKO4NHGX9M4QB06+Wm7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T21:18:21Z"
    mac: ENC[AES256_GCM,data:XsepsoxAQdCi+Y5qjehvMsLF63+B9b2WDy1Y5aX9DPxlR4QwdxSI42mMwhBxfnWYs8asd8WFfzx+hUktTkjHNqD9M+egdm4oLPwz/Lt4xjczhlMg1ezsq9YLxFG2IcX7b6mGBt87bDw458XpG4lZJ6kDxXGl53XteeLgmt6X374=,iv:eHh/yLK4JodpYl5DDq/jlYU3NAnOjrtInSnXAAMO8js=,tag:r2RR5GNi8sKDHq7SNHj7gw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
