apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XqU/dBsRC6iKpeILLiv4eXPYwx9hHLayB2X2t2QbjnEnZl3fnwMNiLiI/dHsAyIA7tVIcNoYpy9CQkVQ6x5zqMpJdpiEGGYDXKRD9+f6JBdggKoqko2rK2dgxguo3vfPfZPSCzsY9QaZzYMI8HVSAvIBVrsNLhAxaNnBbF8H6itkH+h05rKwEm4UsmFrFvowZaMmNOC1J41GVAPT5QQ/40OrD9JuulwO7FLlvup8AcTLIQcKCs420iNi5OBNjv3nmaAtbrmf2ueeuSLY9Jj0RbjFxc7fvuVDZaZd+VcNaev0kJCne/ZDCWUZfsTB19TzdiIbF6yF4Ihz4OIezrGcVSKM9Tl8ifb/pxjEL1BZPy2kkXLAb7QCpKS7E9wyGCZa,iv:QxTdQ2zXlgCwiOmBZjR3I5awzJePrKcXChxY3d7taPM=,tag:lKcu+jwgdCX5cJ8T4dVgpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0CyGggALt4eHHMKom9ToAgvd8yAF+Jndjk3tvDjUIrU3E8A0mBpu4fFCzhZiQLUNfvwg6k7P0CAf0yOD837Y84gSlVTJ0qzwGE54d0SLdMQluCO18tOq7kZyOOwiOJTkP2YM7myTzC9B9Q6xw7odao84zSDW8qzsZgT7EHlQlMZwdG7UPhv6iLgmHnjj5SnHIBwg7KtWwI2Pk23JsgnKQGJCc5oLR+Uu8FM4DDaZfBwGKpmo5XXj6FoMzuiQa/qrMcMHB1OwP42r1O1FRg==,iv:xFzbTFKM9Hk9MA6/9glvIoLfJlNtalODfgyhadEa6tA=,tag:8UOomR5zwFlRUC6q9af6hQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z151kqrgMMLbVW1rRKRdfW0riac8jy0a9eYoLVOyjV7MWtsdFryConHZ7CEocfPcUV8ysNOV4R/wcWZCZmJp6xboYMnxLyGihg83qBV4qzJ91DcteG2D6WjYeCP179Y7dpA8WgWftDySv+aMU4HxYiY0Y5RqEkJ26wIdE7KLBUG104uhcV85e/nKt4h+zpwS1Ks+usP9MCGINzJVJBfNXisH20t3LYL/Bv5g,iv:g9LlpthNVTb5r7Ob+yg4QP2A54RhLny/dkxQ7uH8tAc=,tag:az6h57eomtSptWLU9jWvtg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbVdUb2xjMXJWZWR0UUJ3
            L1pKOXArN2xwdFVPbFp5VCthSmxlTktoVUhNCmcyUGNQYWlyVWY2M1E1K0FwM0Jm
            dGRlVDhobG5HMDZBTldhcFFXcUQyZWsKLS0tIGFiYUhQMHNGQ0ZmKyt3ZWdYQ0k2
            aTlhL0NLa3ZHeC9oMEFJK29jTEtPclUKKeMDSVEN18dSNGDfAYhWZvJQ75o9R1AG
            7/MsBc0A2eLw2cgOGAcfZmBTun0PRbtjvKTyYXz4zytlXeBd93QeIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T19:09:36Z"
    mac: ENC[AES256_GCM,data:aHtsyj+kNfuwD1Fv7brXKrZymYBmpjv40UUBoaHo7seDKsx3Nmc9Agf3nL9La44dGQ0WmJ5a1ETU1SaHQhjGdA4KkShA5ClB3agaREGD9Y9UNCazj47X9siqrinEe3XTPD4Rmj9vS7dwcUEK06GG6DTB0sTJ0NVXsNanrMaAQGQ=,iv:D9nKHvY/VJSFXg1IzLUpNp/JrX65iEInO+BpnvgsMOI=,tag:srpqUKviC1Mcwfx9VmOVBQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
