apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yix5+xuOlzgpYy7LJsxXaIOmjCvGg8Exrqv9ZCOccfM/D9LFkSa4Sv6BSIfcYOlCApGExsy1R1VhqiTdPiuR1W0BoK06KS6CGsP6gVnJ0zohBsSmDcWdWWaU1jVwiGXgXvNBoDfN74Z2xf3zBIeU7NjfiLEev/qq36+Ru29e4pXURodT6bnPwWHQdajqgB2Y9pl681fCC5VVld4JQKtO9JXlNRUeEGztbc4V3fwW1AM35WT0xJeGopWaCKusUYMNuSY70mksydZF8zxMnve/a75CPPcme6iiZjvaH5EHynwkwAuR0AfNbCSIJBZj0fhaKr5skk5S++NW9YfIlVcvcT3T6J5dCE8vQfJAYapaY2FjlC7wJUil3hYD+cjZ7mTP,iv:z/iV8ITSHv3h5JBG/fUXXGfBf3X+5lfnUsEUGlV4Gp8=,tag:OGO5DWsdOPwZSEYY3VrADQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZRIPQOboFtKe3m3fyEClzH7+2ySPPDfb2RmhQpvYqAc6ZGQv5t5fU7H76tpSRGsG0IZtcbPkkAaoRMfV9b5+4CF3ad3XNWtLvjKzmE5A1hw6bbtoT/5ti13qdNSoC6qXeyhbBTx/yzKNG4xCC55hjmDulpzMlWkwEdfI+akQUrCp4SWPVsg44zLXir457b4SxVKuDX6F84gC5nLYsvYF2RAgb1K6yLKe5/03BpokqdLiUJEL+ZJc2xs2naTiYigViBtemKootZwKWCQm2Q==,iv:4RKGXK5XwAGK7gSNXzV3rYTm04y74VPj1OhUmN/IW+g=,tag:Ozs/QBl2cqptEQbbOuBFTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:uj8ZW7C3qGNAs1aSiCjZCVoEhU9FITZuoAZQhd1FMSffnIih0W3zZfI4KG+H1GifLIvccsJ4KqgRbMQY1uLFXq6w7cbZhOHiH0ZAp3bjXlINpHxPfKqMFF2DZXrVGKJYmul49vS71mvOB7Z4yosoKbbWD07CQYcsOQ0osEyvFDJXg5d73kbIj+y9ujFJC4n3Cs2wzi24JJNIyyPW6YwBVSjrxwSNxl56wQ/3,iv:z0qs+ag6xcaL/9eEUYsmF9KyIVaLWAWP5a3JUvg02kM=,tag:Lszd8qosFSeLuCWbD3kxRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVjg1OWNaYjQ3My9nS3Jr
            QmRHZDNIMHY3N3Y4SFhFQ3FoRlN6clhyakQ4Ck1TalpZemsxY1JwUTNDeDZyMDdv
            S3Z0cysvcDVNci9xUmdjY0h4d08yM2cKLS0tIEV2cStwN091dXFkRjlSNlYzSnZU
            QWx2RElCSEpWMmx0M2lkcWtLbmhwRmsKlojcu0DKereFpf5eGgm/2RYa0egjDL5y
            WSn5UJVvscnUaSMD5XGy3ui2Q8veyUa3/hlJFUpnE8xFo5lR2Ekt4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:48:06Z"
    mac: ENC[AES256_GCM,data:4Y6zKtub68kpZ2bXGaZtsu1F5Fue8GD6DvtnEFW0Fq/P7BZaxKNhKjtifVCV0IJwep1GhezW6aamiZOQ/M5lvi8tYBhmkjZgPo5UqHm45sR9aV6mXujwCuircegLNqTlGqnPunR/NevvJ9t6NrWOsKg7Ig4SUG1GJHorrIquv0Y=,iv:y56X+yv7cR/m82V0S658qw6uAnx9wJ5CFG1b1+zdeso=,tag:NaZGh1uzgY4weLSSSexxvg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
