apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4FM3+5Teu6WV7TI/MoKG8VbDz/USClqLwPbgSsbus+Olb8Z9xQT85jWX6afcYuCvRUVV8PdRn5H8z4XRQXXlk7EjsjYpi28HP1bod1WG2vowGgfGC5HdbNBMRncB1gA7MOCPkW41rDEkhNXdDN3hLNiNu5296AKjtQzJKDfy0Sm1q6md/pBApva9lmQnEjQivjjSewfXeS4wS4ih6+FO2vvn4Vdfc5bPERaJWFdIHBOsKfGNgOrXKzHTjRX9Od0TdakF3n8obhSvUfy9IFce3Z5f/L6lMuBfmwl6yTjmBpvw7LrjyXYAIUBYMBlTp1mtHXOEXBEOorMgaDz7kQabN3520HOsEWBxWWAZ3Nhw+eLlwqz9Q43QTGqTzNZUKbBg,iv:WL2msKPFgtvTSb6eT0CNAkumQ1oW6rVcIRFyYtIorgM=,tag:c1ZV7xPWsNU+84IKRrb8kQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:C3JtBb6ZgbcTpFjyoYSlLLAvQHoMnPm6bi2thaOii1IzyCqk6VyrBxLRcX5YXDvSmR5hRwf9DBUYKXcknHOF9MxEDilIpIoBj0nnHHAoeClX//VlceXtBQquPIrTcavx6Lrnh7gkEltyfu8vzOJFeZ3/eS6yUJ6wLkBxkdV9mgFjpoPfxPy6ljU929KBEIvQdZ8sjOZYPOCYNFZ+56oD9a9lQS+pxaBFBVmvajaacX6h/ZWvC9NbNyoYDQSnEtwx9FTigRxOceLyi75C/Q==,iv:oa2JKaOaJOkgFwFqE7BXYTLOMQc9eXN/v/iDmGxYe1A=,tag:n5XSwffCzvfX9+B19bCb2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:ryE2n9vLs8h9L3S1YeahJ3zVuJXvm6TPCk0ebWmNUmcJ5zdYYEi50AoVt+ECBnVMFLqK5COab5orlyHEg3qJGLIq8q7zXZZ8tIS1bjlwCkCLvO/kYNtzbkd0uXDN4TZ45B97FY/cIP0OTh0L2+Oc4tZtv+e+5v3f6oTGYeQY414lYKCbhxY6xihRpBzLhvnti2Ebm1gblvHfwpBzHl/iFsTNE2+080LYulMZ,iv:6Xa9Y3wpqGVcAfxZj0jyRxfqJgFi2Nv7OlwCku9f9aA=,tag:66Wu2ud+sN1s5AWdTY6mhg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bFVMQmRETklZVVRPdWlS
            cElWOTdQdVRiVWd4RWsxaDRGcDU0UDVUSUFrCkZ6VmRHNEF2MXBjUVBMTUdlM0xU
            U3dML254cjlSOXBDSWtqUVFTYlAvT3MKLS0tIDBZOWcyb0lTc0w2OWI0MCtRbEZ6
            YjBrT2cyT0l2RXhNZFZBeVJqSHNNKzAKDXUZpLED7L0sfD8JElwH/BOnwJ2V3qEv
            9b65HkBgfq2ADtB8VwlYPAtHAUlHA/Yky5mLg9vt6mzsH7AyByLGAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T07:16:50Z"
    mac: ENC[AES256_GCM,data:rngqNIGs39xRN6C3MVtlgvSdqozRFuAC5DdCGp1CqDuspfWwZwHnp0sZ2d/Z77ZY0y7s6DccuIY8ZlBqmcc+zO+roZ4lv/c2HJ8EnXibxleiw7yHBxS6UlUw9Bqxq6Y3Xv/Jrh0cNC87mDtjkoM3vDm1Ou9G1PGvkxFxBU3mgok=,iv:gp1Ai1l1hJj4+x3Bh4PUdd29kRbQlFNOpPYLJCvS7i4=,tag:5VTG2VWxj06nXdGG6iyGKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
