apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zxTX/W8em+rnL3KZ83P6DnoYSaU9wJMpa5tbnmJoCtm0n9emT8Bp02pC0dllk2mFTI8sPkXESQPRXZNKfRqG/XGpzEVOcWMk7Ky45xYoWNc0B0WtRuYfIcXtsqXVDC3AB2blhqJEpoO7jzymBTldeH9Fw/fUwuUauQzXGAkbHZ3vkouq7xtgHtEiRnYGzWGX2nxeuMaO/HZ/vsrtSD+7pwHfeoRrYiEZGYKXax8mtxLbTPh8x1uQ0SbySedXiDqA3sU2xhjpUUmh4y8t1r2SUOL78GZ1OL3uAPI9Ml2BIvYG52aij1XO25gzZV/WswX1NPG5vts3sTH9Xt8VARLbizIKapby9QVrxGa3qQ2POEKWLbVKi0379VZHO+gfoZSI,iv:v2iF281RsubqsxY9VSvBfyWvc31STP/R2j35RAwatEA=,tag:RnI6+JT0numSOj8JiO6kqA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ezSWkqijykHJCmEjD/fuGJZWyDTlLaYvHb2iD0TTTHwuBacbRPjctobkT3i0dCuqKIBM3PF5PfjDNGrw0iTap1SAoXsVH4YHkZ+K3lEFEExoZnmjg012n6vp8tKu5SlK62RgX6ieqyqqe4DbZNUlNdXHwGcy9qGWa9Iwb3Ayy9c1fHNj/evgLVKFgtX866YbCtN+FjjjrnPV5WcOMJQsiTrz50ikvFRIRZ+wLmnEdHcJmB7GnH0/BHWyGH75LJLw3w6AF/XD67Wxr+Mkyw==,iv:GQvb7qC6WMb42UhqYIIJy76ER0qdVHnRSCFl+f9NRlg=,tag:dS9tBIDnbZ6YCMeZy+9HFg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2MiK2daOSHeM3hRyBVRg4bmf4sK9w38kFmM/xhimMqX0Anq90CHyBCSciKGX6WDJM0TkjHwqrRKA0U2N4l1kkRE162Gt8ev4b0DRwoKsvYpWWKmMAXP2VkqjbHVwL8fww0PHkVWyLz6tb4Ws5EESG7PzQ5FsGflLaB/9lV/d9fpxzZ2rntvy83DJQcZIJnr++31VvfexwrlCXGi8NstrishhhE9IEOQr4n4s,iv:5tpv+rTfM6nnZ/iX7DnaM2UhRlqtMVda66LENzHkhgU=,tag:BK7UaREGUS1Vv+Av5gmifw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYVhBZTNCMENGTXVFY01m
            bFdDcHVXaEdtbHFBd0Q2cUxISG9jQUpvbkZVCnZuNTFpc09ES0k5ME00RnhhemFp
            ckpoRmxZL0YwbmRYRloyTUowa3BlSWcKLS0tIFFGS2IxTTl4MmlzTHFUUmpESWtN
            bTFoWllESHgwQzJEdjhXU1J1ZWxNaDQK7+9Pbi7b9I/IZdbWOi1FiwTgDs5+u/gP
            yJFQNcPI9AoydHCVXCrvaD2LuVXBNKSDSa/yVGvv5p+2idV1EFzSqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:37:33Z"
    mac: ENC[AES256_GCM,data:T6WDLV7sV79LqPoW3Dn84DvtuhtP1Ub0F+rD+ebRjgKylG59uVry3M+lbbcuIpHVHtlntqrKIq2SNlj2gbxoHVRU0lvT+hM0td4NKJsfBr4qwk1W9eccOO8Is+We3ptIbYZMid8uBaaTgF3wwhpLl6e0SdloIdDydb7CptqMQPI=,iv:a+vV5XRyLIXfnX5eFqVNkgrYn86t+rqVpYutXKPsUFk=,tag:ZWdI+dH/eWS3qShJHJwM6w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
