apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WoTH9WiLMcmhqBFx+WxDnC8DdDD/el+/V99IzGzmdgSBIRsL0HlNjhBXXmz+tjc2hgOH7IbvFPcbvqncly1CkH0UyA52xhe0WTPM5xhBX+S2J1j5O567f43jDuaeDQKs7qXRiHOl5VRaDmCx3TpQwP04shtU2TwaGvVeaxUwmkdukuUaCnrtGhoQ9ejrVC/y1ija/qJsozqSW/ipmUSClPkeZODRmYLTzosWPm+Z+ciyoZPahGOpgY95cPDHN3QVT8EFI3zwbXsuZDGu6cV4+B8WNCaYk0hAn03ACEeiXnIL3wncWulIDRHWOz8dDfWShLbIcyLLumNvX6LItLzVgTNjEksv5AZkP04gV/Q0lzs5k9dwV44ogHQs7k9wydMd,iv:lNKBjpyOTZCivKouImzJoUKgBe8RFeFzorxNPNidCfU=,tag:yU7H8siOKBkMTlBhughnRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:J4iFe6KvHuvNjzaWjViVMA7JpmKfvnIBQucQeGqvBWfqCZDwTV9LT8g6WaYVwFVNjmSt5b8IVehN0u1LCrIdQMj7dKwNAeqdKTNj2D3gXvsUwm0INSj4mTZDIm6dBJ30TNwglM28w6Ba2E+NI9bl1lE5cuXHQZznX7T5Uez0jpEUBkSjetcP6MVfHvdmXZPfvIvLxPq18y8wccjmp4EHUEs2TKhw5828enNC4jg6kaRAmhxlURxEDhwh/nxZIbMWvAvqhPEUGWF1D1yjlQ==,iv:vXqQi0R6f0wyf2WwHpdNoqYFDoaVg5rFmlJVP6CAgg0=,tag:yCvt72fzvyPmYXwelPmq5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:sAHcjTUM3C5+IVH/5KgdOtsD4etJFrBPP031d0HKXKU0k67r05Hu2+GrcBeLHcLOKv0iGfLFpdiXYH1fxdP7eokFHbEf4YdyaB6AqkdEqCTiQOliO1NuA6tf+T9iNehO9pKia3Svi2dmU0z2Lkh46aVaELsLEJiQhdDyYt+1e5Y8Bt7bGi+47fyexnAI6qbQ8jmAV8AS+gsr6Lsf+o8pf/02uHHZawT52pTu,iv:SQQGGwgTsgMGqQxZbI4B3nVPRHV/ENKFOwViOJL1PCU=,tag:zxhgVpxsa3al69gkFuSV4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l8p8vhf8m5tmfkrkr24phx4wf4uglqvwxu5x958xnpfae34qgpqqs6l9qw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWHdlUWxURkYrc3kvei9x
            UU8vYlowdENMdmRBck5MWnoxVithb2lORWdrCkxINlNOT3U1dExBaEVjdWtMdkY2
            MnhFZ0EvL2srQk5BWkdaWWhyQzlDb1EKLS0tIERCbWY5QTZQL3RJUzhUOGJBYWZ5
            aGxjb01MQXU5TE81RFhZWFR5MUJFa0EKm/B5R2BGKpI3xBonIKPjihpcKG/ekJLB
            2oZ3fLqyjUm9h56jXMnvb7pM7qsiSHjFVtlQFY2l1e6TxKAPRZeA4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T22:37:34Z"
    mac: ENC[AES256_GCM,data:AOOjaVoBxraeNAWDfIVFgEM1pFiwaswDemBuHU4EbYheiRVN1y9jd10ZWYhYQkMdy29NUyYlrowpu3TjqJ6RH3MLmbOdpmBjTKFBq/8FX9JifZdS8VWNTFuvgoFHiKELzy1HxoxxonxyoLvirBDG/ndHdJyekn67l3gE7Y3IGXQ=,iv:bV4+5iHmiSoDhxhuSL3OvLj4wW99XvhP7D9gUQ0UmbU=,tag:g/cz39aCzGsqymwXE/HeTQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
