apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dVsvFQjZz33IRYVXyYYuFII6h82RG/Nba5Hg5NU7kC4KSyej1ZEk5m+Mr+gcf0ZOyR8vFlgIZwL6etwu8bx9VgOPWH34dRnGBQzRaGRFAgL6rBJO0k+hkOEX/OKYQsFFRZtWtNVylTSl5RIiX6wtqjoTYv1hi5OmD5BM60uZXOO1frqJRBj0B6QTUV5t9Qnb9hgFoG9wXQ1FdlMfh1X4BxAqZT6xyYLYYs+IWTk6X//61sbL1I30L5pcWuP0j//noBOw5+oWVmKvVvGeXxB1WZ0NRisAIk8c8J+vV5pwHHkEAyEGo8Xjx5rDkUR/LVNTtiGIOD2gV7rMVXpUEhn+7uY9QBus7okhIbyBRADj4FFmUZ+F/Vpohzi1DVQPVu+T,iv:WdNrGHUcQmSoGMWPkJntvfShu2TLeVsetJuWzZMk6QM=,tag:+VQQIXSMljGwI9/haUYXTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:FAmOS+rKnG6jqQkgeVRNK79zkNIOISKecGoB5o/SIgerjuPjvv+W9FwoD7qaObUgQgXjzMeXwag2C6tqTwcF0lfRXH7+ZS/ePC04OK5VN8ZAdOl+RaF4D0ryUFdrJ8FWJGN0mAk4Q8J5TQ41ou0lKXjlGfikXM1g+gpvSFNqY9Y621wgjTrgBUdNPmJSHSKwDGO8RV6mec1jM4e5X/rR22ijOUCZ8PioxC3eSby+hv18q79nQH+2EiK6CCH2W4fokBCy+pRo+4x9YuCztA==,iv:ZEAKNi0pfrP5AwV5OvoQXBsq/cIcd+dHFhx3Dfjj+v8=,tag:uXafjzSomI39rQRavpQxwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:gmfT1Rsk83IINUDZanr0guwvhRipRa4761dYFrKKxqmJPSX9qJYdPYo+4D2h7oOVVuS0hCOVVS89btoJZOUPQyr1hfMbN95aEjStpCe6UYIovTceSCglobz4/ANGgwoTIoXalbdYjSnOz9sPDcjbiuw/DASr4fnGz0XQkwAF54nMLc4nDbZPWAMJjxSFLKhcqfGaArwzfQjdJ7Vt5pi3eFn782q/ER28mzJ8,iv:NwgNHd6EIgq+sc5NgGH4wQL1oqJT0HsLKHp3NThvdRU=,tag:57lHzQTdP9ZcUlp7KobGYA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNi9ycktybWpoYUlyTTBH
            ck9EQkwzMjU4SzdLTWZUMzFsc2Z3T1o1WUdrCldtN3g5RXUrREZCcEswRkRIOVEw
            OUhObVFWZm1VRENQTmx0SzhCN0JlSEUKLS0tIHVvVUpqNmV1OG9hQVFLSXd4amlU
            QU02ZjNmc0gzNURMcGNqR0p3TGlCVmsK/fW/VW+Pqu03PKhZuVFtlJIJNRizdepd
            aOtX384am7NkVr2DjtcgTAGrgYwia7l0dWhW5piehdQfap5ONlcmKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T20:43:49Z"
    mac: ENC[AES256_GCM,data:PbamaIG6ScgXrCoKaFw9MHP39V6ZnXwozIMAmVIfVGpuAYMa0fiYvL9otQBBHjZOc96S2aojbEM6bpK2RvxvqML7SO6RoAiE9qiuR16p0FsmmF9BlDImNl5cztjZO7r2lXfsiH0EHHJ9OFWRxUYYMKNJmuNvwcmf9WPvj+WVYlI=,iv:gJCNW5pUuPfUVkG21oabdwiCq7zovnTftNLmGZ+s7Yc=,tag:QYJIxpDge2sCyVyvSoHSjw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
