apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uSZ2C92UkbVD0UEi7Ls/E1+dJ56VXtJfHgS+N5FULzItde2eOPgk1MRBPgvXR8i6deeqFk6/KK+UL+3pSq9u+NEW3LhKW7FzlVqk28WVdt0pXoyTl9ophU3N0IauQjCu8091FK+AxRstSunGm779I0dagGy8PDv5MB5RRvqThztg531Jx3rm4LPbWo3QQaeIRvUWpzwXQcG+7/Ez170YpVOqY836A8jmn+K9/lP1s5+sKeWVYiOK0/xaxd5i+Vkh7NH+AW6hmOJlu90xbdYWZnwpLSZM30Oc7jZZaKlk4i5322hn7TBjP2Ulz9+AF+LFitChAvul5geU4ks55drCGlhY03QB9Xt0lAVNJr3x1GB1O7JrudnuXE+gmOlESV5k,iv:sDBU0j3M5oI7pEdz1yhKanleqBb3j65d1lxkm75gH90=,tag:oE4p6mWB6hfPQiVY3wsvpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:bO/nNVApoqYrvu7ZM3cgaKOLNFF4pjmRi14MCiPPrtzkoGgbC9yzFgTGmpzvoA3QyIm3V1rsV4AGuDGFiM4hgLh6cfTS5rVL1o1laN115oMnuZ7+J95I1+mgxScupE6tey5RRaIrUMPV/2bssD3RI3dWb6L/4LLi+bLEsbbYN58uZdXlBlnyDK2JisanfBc6ON5wyyEeIk+qxq6ydK+2FS7O9a0SMnTx0RxboubV0UI9jNIEjo/oEY3QhOFK8KmLBoJhSvXa/A/+tnWi4w==,iv:XJLEofAIsbm8bxFF4oCvDHpxdD8Med+pBGwb5Vo40cE=,tag:1igwhdcApxsifsM2cnVE5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:jR5jFR3BwnXPb4OBDsD77BfFcJyIS03sMjYA0Bml2frM59fcC3EYH4nMWJClt+m+ze6rdBGau8BFv2sd6SiF1j2guPdBu6QhbiUziXjiXIlFECfUkoZI8ARmdGTu9WJ2FMEXB+CUQQagwwLEvz62cSqCPVffooZxvC8aXypdmb8c+JTY6lsNaq/h9Jn68VsZa/7ihl8DkOsbdFdaXqC8fK/YAUA7O9c92DT4,iv:7UHQ756jyXrdvaqnUyoKamg9SLzcr5yfx6sCwIuewY0=,tag:mZ0Li6pfWr9U/OkwdkIx5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUUZEMSs2akUvVmlSaVkx
            dDhjcWpOaUtSSGg5U2FsKzVxNGNueldpMjBVCjZab1Awc0NvampwdFJydDl3aUpF
            NjZXOFBsTXB2RUE1dmVwbnN0UzFVYnMKLS0tIGh2cFU5Rnl3d2dYU1lUMXV1L0Vq
            SXJOVHQ0dUMvaGN4QU5rVUdDSzUvalEKHDS4aXqwpBj+atj+mH7zjkOUhOsGufLU
            MPRvvBlG7Apxu+ZCgZkRdw4QSYtOTXLeV0GvTcjQq9G3A9YxioWpLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T01:52:56Z"
    mac: ENC[AES256_GCM,data:DOH1Ft8UlzKLYJ1fotbBpBly2a7c46HLAHZrfGy/5TjFskveHAZBF0RjT2+CXPa2NDAusr5TqIvUCeQGcYVUoJ2O/3dfh4FQkD4EpAB14Da/TIumttZMDz9bl91EvOF4ER+sxjVWZ4e5R9isPFV7nRjFlUB9bniigiEghF8WYKk=,iv:YkhvB6W7bshovZ0acYV0f81IC2LItoO5w6U+RjVz1Os=,tag:MdOUp/ZEtmd7DJklSCl0sQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
