apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yiuvBVVKI5PULSDBkd10d1mJ+c+tPZwHSX6ebTpeqM7vHvaJ1rQY3z6MwE3vRjdbC2Vmr61ibnRIyzP/liqiS+L/urhMewbAmyMqAVWn4NnMiiNVUw5h4/Z3GvwkQ7undjxNbCBn+zLovKXc2zULnKpdex04oEbwNExU58GLn3bVyP1uPaYO+czifF/kXSksKflZN4J1uDQDlHI1HztfhQUKIhFToREjniMjJPMa5pfuek+ySb+I0OwAwHzOmkQq4Kb2yzdrFBbaFeztMqcMWSPF4EQjLNXHQzy7uiqQmj0+/8uasEBe4zTOaGFjgm2WxZxAaa836Pr3bVtHLrgjDPlsl5G3syME3qHAN8xM+/Cx+K2vWWHoTskoOYtVXORn,iv:VTLqTO1TFoJeouU6M+svHOO/c5+NcrFZr1m3YKmTj4E=,tag:otkavosdV8xwyUUyYHR3FQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PYkY5CNqw3GvjYqThobXHabpOjpeMMJIEJZkhvfmNoq2qEu6i6WQl1jVBMBzteni60qJjFT3rmCG38Yh8xDP0tOaGp7QeiOnFBPT/iLfO0d1mpAfLYInXdHKxMB5OzQIgZbXLhsxfNT8zpJjRulCSYWoIAClExuVWnusK74Yioztf/vb5fK17DZRSaTNAVZULdXdeH5AeHYzvM1Rq5Aif11rGN0Og6K1EvwiNLYCOLXRlEruAn82TU3ewBmt56UndTNpeufdw497Gb/f2g==,iv:v5GEjB3+vQb3SI4vQ3OQEEAft6XZsIWLJhL+cBufzag=,tag:B68d5FElJNJydNrzB/WY0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:YRLFSHSe6nVjdDsNHb9PfaR1m6/AXPzzXSu1qj14GrsJR8d2cfXVbu5CUa/HDWrDmdrm/pJhhWxCY3sZRags7GUMtA69LOY//Y5I7nqP2sIZYdGUcu4UUpg/cGsVmHCZHQSRn5mcJLJOaukJp52+N2G/TuzXMdWSkWL4XGtoYzeoha27z2klY+YAjhk1/GawghCuv0nLYjr2z1a50ktN5lCD0xeUovT07Luu,iv:THD62abLcjv3BzliqsakucyS4e/kDde4AFnOdL6l5hk=,tag:jzknklrZJ845dFXns8R24g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaW5sRHJTYmlsaXBhRTZr
            V09aK2FCVDM0NlFrTGFVQXczSkJUNGdpTjJnCjVUUXRIeDdKV05UR0ZpZ2RENmZI
            cjJ0YmZTT3lEZDFQTjUrVjJaR3RURTgKLS0tIEpsRkptQkFLM3lQZVdHdE9LRFYw
            VVpZSDBjWU9EVnYveEF5YUZpSEdySE0KSiLdXeHgUdXu99n1HjuVZ2iiRo3YnUzB
            jHrCwMNqix5eGnHlNebyZBqmYBvc9zXhClMQV9+5h3MA79M80baoiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:51:59Z"
    mac: ENC[AES256_GCM,data:qPxpwbEIW5cc3M3VSJavvKN3Ui75TDpofkP/AIfuyw5TYNCcgNQAXF9aYxwhZHh8hABbws+Waw58yWZiIuqOnBN9j0qJXSAE6j4BUU99bscbI+D3si8zZPVXdqwnEtiPKw7K3dpXGrnYj9232x+LciwdMKexWS9vlIrl0b/0pbs=,iv:zshRYcAU6QTNUv6eo9AQDck4aE7vhSa5WiHs9A+q8kQ=,tag:nF4DCAxJgczEJINi6ImsgQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
