apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rU+OV+F56HVVBXQe8Sf/xtd4mQsj/XmJvywiqYI7/A47Giapp/kwQ4Tpnq6lBgH40VT3kqnFtc2Jph2aj2ZwIg5+8AVs5OyDYeLEGVHQDOlrFCGc1pv/2vy6SXx55N9omul7ZPIexWGr8CDOMg54rEuKbh94W2H1ouv4BrjrQ6s5Lji2ryEf2roivCI/+5Y8LSRQicYWZWwp6Gut/ZOlNUiPS0v/yq1JwLSEw8sVgdc+UkRO8EZUiNqbbgc1pAYbOe9TTFPdDkEi2nhsMJDpgdQOri8ROCG3LWQo+DJqvbsNz3f/VsOWI1JmlvrFmTiDRcTEYL2aaW7+4CA3D8CkW/cP+OLgnbey0ZYCmw0jeAHEVopx5lxJ2LCF4hFdFGLW,iv:WfRLc1FmF/lrSNQGNvSIBBDPYeTjIg9dTfOm0APnlFw=,tag:fxFUWCpbtpXRpVmYN2LOng==,type:str]
    identity.pub: ENC[AES256_GCM,data:P7PXlhmMvBGcHf0IgaczaJgO85DZ9BHYAAaRjy5c2e2arHAmYhJ7MJCwOyziF0U6+hIxg0Go+OPRuqcN+AlQQ4Gcc7dlGmbVQ4yJAnpQTSBOA3SuewaoeXS9h7hSbtSr3Mv4uyf7aF8eG+WUoXQKmeNij/CYoTEf2Qv9vV49zdcSP3bOKndIjb2vlZfaouW87w4Ho21KLH2J6BLdd7cFzJ9lGCnKeUWw+O8abNtVa5CqzZwD+9EGUxBpUfKGeBXtPtu99ssy7lzVMFhvwA==,iv:KbLeDRQMXLa8+ijW7JOHE+Rsz9sy/0YLCKk+ogaiIzQ=,tag:PX7MazBNhAoDGvkzCKB5GA==,type:str]
    known_hosts: ENC[AES256_GCM,data:WJaJzx0NOJt/Z+bd2XmlS3Jv02ElfjdeVdOmp8QYc4UD0nrd5TMy83YoBlUstkM3174i0jbwI/tLGtytX38B2di9D/CBkePjIPLFiQHlvz6tPO2mApqQXYNNbNm75JPzvjV6Nscth77aUEtuWu6nb0G4jojvvkbbwAPrmEx/In3jFTWYjJZXJ3UkWYcCOwg/RS/myjEcfj4y+7pOWu6KJlKAhYPp6oxZ8cmW,iv:w2cTH/iP2cHuYWvdVtsWxjeVwgdZ/JZZOAuuLTmJpV8=,tag:P7YQzNgvVWM3zdMSj7CP4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N1BWOU12R3JiR1JzY3or
            SW5jYVU4RWltR2pqbEJpbFhVOWVGU1pDYmtNCnFtZTVTaE1aUXU3MGZWQ2pqS0Jp
            Y29yYnNrcnlmZkZVckpQTWh3WnJXYjAKLS0tIHd1YWhER2ZIbXFsdjVyVzdtTzAx
            SlFDU3FyOHNYaGtwcUNQLysvSUVMQ3MK0hf1lCYt8YNgvSRJrC+eUlqNJgWhlVzj
            xWNs1JsgLBdusbJF3pcIprDGbaAm4+e8kQ2ekx+P4KkUjQcKlW0U1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T05:04:36Z"
    mac: ENC[AES256_GCM,data:FgYfTt6EDoXm2oXkWz+v3TPDuKwq64/05+aj3U5rT6U+x4pGMqaSI2BkXAOMEiAHD0XNgCqGuSxkLuAxoHXiUDy7U7gwie4QFWGBwELaqayjjkMp91x8TndH9BnyfRVGP1eO+qzTk7OmwEtXuoATd1Fd7JjPhYHCWsQTESW0WO4=,iv:W8zyJrKJlehoi6gP6sYv/EqpwQMvGqOF5dkEgJ7NSvM=,tag:7OiQG9VvlWDr12JdPFm3dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
