apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2gD5PZTbBdhCaTUHSAONWYlMd8QUVt/dhTqAZA6/vCizH0i7660rJ4IKcnNQ/Ds3UK1h37VwuqmEGmwngtn3ls+anQKXKKRSF7xDfg0+jQb2h9L2h4Y6BNgo/dy6BbpWMeNC+gPQJk4j592D/qYm0R/aWQXkoIIog2/KowgngsZcslxePtvn6y1TrRZKaVkgPFqvY8CXkRDfq8Hy/ElK8m/hL/4HFwdnFXhdjMnVadUS6taVO74udNKdj4WUcmWWH4YY2vFXoRx621lJF9qqh2jQ9UN8Oz1jBUb1e6hwCy/YeJZ8HUellmmH1P2fVDJ9xAHcOH0GxQGOhrvml94H/YqbsSX3ATXnhuUy97zlz6LgcT8q31+K1wsCd2Vpcn+0,iv:BKCTdtQw5E7VFoK7ZWydzMKbBWDrqmPpNYNVTUQki58=,tag:reYWhXY93d8KwoSv8S4V1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:va1VzEgy1KwV9X2T59dq2ScDz/hnHgYw0sW+PgMkNZZw8aN1IvfB3/erDDpWYB5D7vCMV8SxKBYqvQKl011xXOdBUedzsiKGmlQdiUWpL7AVMUAwWsbDGHF/RizyqSVKuZ5Qbj6acnIeOLCiwnbP+4d4YsWbQfoOgTgilSInrsBxLbAuR6QGYpPlaiZ9UxrGdrNZn9+DB162nPaTl7KIaljAWeNwYkZLs1o36lOEeZ1IXl7BVGGHcI+Gg+mo55vn++2p2EhKsYMcNYg7jw==,iv:aOBVM4fVsVXc0xVICizNAUkdsBIHCRCiVRSBaN7f4ow=,tag:1aYZeHUWR1YUvLUs2mjI6A==,type:str]
    known_hosts: ENC[AES256_GCM,data:McD7YbZdgy6IUOpFv5SU2jTPqhxqBFKYHa9u7eD/bT1FyZm+WG5qgcG9Zt0/70dOLG5J3J4DuxGRCx9OtCduTqVznr7+4NDonhQ0oqcNj+69GXIzYdncxziCXK1j4zRaAceNwdy7yS9hwm9ClcOTIF5lHL/se8JE2gL9/7s5M1SEGwgPdIRG59dqEC0NFl5pe2VoYmoMmyRaO3u1Re1qDWk2cGW9P+KFF2tx,iv:05Pnvy4yOp/PY/umm+yaSobeBSNtxthskWGZoWFRthA=,tag:eXIXGG4XeROp7SrJXiQNrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZklqUUNyU1pEOG01THB6
            M2JCMGl2SnlpWVpwRXNld3lPNmlXYUZkcHdRClJvaXlMTEJZc2Z2NUZ1UnpUVkl0
            ZzVoeThnZU1VOWhlN0MxemhGcDBtSmsKLS0tIFB1TnQ1UDh5dnByZ3NNL0N6bXI5
            M0RxR3JIYUdjQXVidVZaTXZ6bjQ5ajQKvXo9Y6Dq8877bhKI9/eEqgV9RJ/Rlf9j
            QbYeyorpWiuflGyuPGdRTkPaopm/elt/dOrmIoXvOeddYUb04b2DmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T23:43:09Z"
    mac: ENC[AES256_GCM,data:tgEsinAWBHNi8fykrlBLmCucfSVL3jyWKXZteZp1Htn5Qu+pzpVF116zeyZxw0j6+1kbbsI92nJq9n5qrlqt91wvJ0QJiFQEwgcnbQ5aC+zjbteNRKDntUeB4/CsGV612+vdjn85IKHSw06ILL/FhwrEwFQq4r7KAoU/ljBbKxM=,iv:Sm/MOMe0BHQxWuMVymJPdWN4E8M37ykNYw5goF30+Zw=,tag:ORypoDxJnnjuxeUaJpI8XQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
