apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MgGH7VVxSoxClxyWRI9SkCUyueZDLHtBFWGvCixnxaahKbBsIypUGAyfof8B5PXxKD+B1w8UZC86nRFrM3bYZUGry9emzCyNVxDtDNqYvRdsAzlu5qzC4p7bMGoMcHmrD5S9tjpreqLJBEkVdUn6hau/83GaLvocaoqFYHjr0bbOEgvl/q5qroP0Ss/AeEqA/gSSdmFXIGpL/NeHTZNlg+LLqSOf30GwoGJRnN/SYrnMAxN7EZZ275lJP1dJl6ax/BICGE+lNxOwxGEdYyg/d1HN6SL6PPrDMMQeCR8pmSFes8QdMe07Xkwo88nualB3iX6NqNFdKsSKzHJoKYvxHAicRKB+qqyI8wnmhklun03nHR9uaDP0VWWPbUjf5yAz,iv:I0tNZSAC48a0dU2pJ6sm8KR3k/KVFGDyWll6vMXHZSQ=,tag:UItE76nONYX2ePwNyx010w==,type:str]
    identity.pub: ENC[AES256_GCM,data:JGNaOFkGkmJbvIqyEijllh6GKyeNDgcsHxpFV3ttbV6Xl+v0VzsLQdpJJ1Xpwg00Wf/zGAgrM/jAVX3Js2jZhIEMYc5ZrnsUmtdoMHJsDxtEFTgPvpnyGAfLovC3x1iFs9n56hSumYMZA0qFn31m3AHvyUF9jzPoqaJWJz0pdcfJG3uBKnanuyLAMZfC53/E6HMChkfd8MxkDNZ7JhhuacyYyyWrDR5pzcJv17op8edrotQdbEYrSt1ACOrpMjZJpiKHE/KE0qV5OHBczA==,iv:LbVu8LXSIEpJ/UFIYF4F2cmRwVeC51ZlDow3GigXDos=,tag:3gvSQcXIsmSTs1oSLrjJxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xIzeYwGR7XB9zXsm1wRw21XWE4oIxkw51lRLxwjNTb57mAqYSw16o4qeQloeOGUr3h2JDGHCP5Hc1Jpb7C/s/PCTOj3irG/PuGaPEFvUc1rkJl0qmmJ9Onv7y9EjcA2slBbvwnC+IQ7ECvwp1W1frOXwukMPbIAZ23lP52HSue0WQnmBhZLKVBWM6N8cOzZ2bdPuS2cmCwBc1ZEctnizM51zn6ZVgWNXVfVE,iv:l8OVZv1rEK/b0MQ7W4H28vKxyz4qUKxBUvHxWiVoRNs=,tag:ETvjw6lUyYQ6JoT1GLQg4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TktoakhidG5qeExRL3hn
            a0VhU2J4UUNPSGlka0tYa3BhOXFDTUQ0U0VjCnV0OEJtNDFwRXlCMnk0aXdDdHJE
            aHFvOVAwUDJNeUdzem1sMnNBWmU3bVEKLS0tIDZhdllLbTVPbnZRMnEydFFTS1Vw
            Z3NlNDlENmhQL0ZKaVN3elVuSHlDK2cK+CSjGbE7UdP0Yj8T56eGW2KvmxKB5EFi
            W4YcXoUOewYEKr27P7Hov2NjUWLGPswAUiDiJeKpR0BAZyxKQ4STbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:26:56Z"
    mac: ENC[AES256_GCM,data:Rvk/ieiNs/a0+kLg/qDwIvURyfGRB1HAH+BHY7ssXcz9iEM+CuVZaA/h82g0SFu3KP8vy5HziqGd4H02uMILxgxgMvtDBNqQg4Dn8fvPHg9oyulXX0tThyAjSgnWSZIDMEQ59k31PQEGFH6+cTcN4C9gm+WhMdWiyj97WmHCFAA=,iv:4Fr2olRb02OAJCSyLjGXD1OPlETkP165b2KDi6ZNDWg=,tag:PowEItYDSHZ58JXa32kt1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
