apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JV3359hOIfyjbsZyPzoOKW4RoztbKP9h3Fh7hgimJ6jGU5tVdq8+W5RRNFMTMdKJizRWrHJ7MHnZmeGu/yuEpLR2aB4NPjWFeBidGcOB31WryTbTS3zGkVSDdhnZF5U/4c44P9GqpYrincYUpOr84TiCsJDQAMgmENaAXzct04qsvBB6Pfp5E/vmOITSeX6vxdv6NlbsTd/MAOCBhFu43i+2XQJc8bXpk4cVgLHragW/xr3RKfWv+5ykdxUQe39EGDrHeAqwYnOl0WE+T4KwaDX7FP2eV7zmmQoka4Tj/ZJu3LGOU2VfGa6S3H4QF10QJ4rj+WvstbnovfLy/LtG6YU2EDitjFudEhzDsBPRqC6EVJ1TUg73YKKcewISV7GF,iv:k+mqO4/QKrW+H7MP5Q1UDETmzAUrc43eUdL7euhX9X8=,tag:gAkSkszdEiNpoNSlsf9DIw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VzwMuhHwCgmW+NnSNFP+ZAyo/uAg9qbn0JkHcoBLfaZMeCnxqVxYulKcFuH1+5etzU8nPrPZORaPC4MWjiAhGijx45GpIgU6kgEbwbUz/8N3D4kiVzT7ocGFhVsLX4ubCabAtKahpfj7EciYd+LGb9UYQjiEjw5YnkqW5TRuEqA9IfUU3r1Ft/f/YaTl8IPCck8/kHzF1l9uwmi6aNikPYv93z5LJJpgBqCK88IhaWCHDTSOhJcjYeR6TGxJClXAXHxd43Cudp34p3WMqw==,iv:D4s3YR4/oVouonVBx4KeEn3/AjxmMrwpMTbhX/Bjnlc=,tag:JeA+u02/SRrLmFXb16+LDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:9OxzKE3sJKh5+oNwDu38uqIcnnEtQ6fFOTDGfjKVxAzvbBh1Vf8Id5EZvEakx0S82yC02hvPxpf5x+YjHAB4L3dNTsjMDPDAMNsTDyUvp3KUsdWWLYZpmUvTcyS23hxECU1l9nuih0uKZYj2bV+ww8w1cegXPBhvfEuovWPlnKgT8TsyGgmQjpzeyX0ibnG88kPoGnrvth0geD+5746D6wmOXHa3MXvmPcdG,iv:mJ4xH4O2YlAcbVZts95+PPT12USPdi6qE6hqiYjPxEA=,tag:K99pEhFUEzUPJbwLSsGEZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEFQbWlhclFadEtUSDg3
            a0RVM3dBdlNMOVAwTHppWkE1YWtOYUpOM244Cm9wNjdrSDBDNk12RWtvOGhRb1pK
            NTRSQ2xYaTZJS0RGUCtyRmFSNkVlTEEKLS0tIENOU2I3cVcvY09KdnpENzNKUisr
            MmVRZWZXVEYxaDhtOEdEWVo0K2JuSVEKg7q0tJ95Pfkk9A/TAjooqIaRP+0tsMb7
            gmF7txZ8uGC/YJbFOERA8KVINL56NHvUWc4Fdg6eYQ2MLLavGBXYGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T00:29:54Z"
    mac: ENC[AES256_GCM,data:idye5hdHejwnelO5+La9l5M9rdzF2Ipht7d+44OCiVQcN/Ej1V45vJJ4cV3Dme9mzTZAVIBaxFoWXcXmfMsGfmmKrJiwPc7CrHsDSCusG6vEAnTsbfmDiJwT+Yk2ehNdzyk7Bo2T6YJ001YvoWG3P1FHygQZ5gK/GPxb3CJOQfA=,iv:nr5D85ks1ViOkvTsA3SO3g33vNlipaPIhQgYs4U/1Gk=,tag:967NXEaIscrxzt0QI/igHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
