apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wQDuCY6ql7efutG6C61TpO9fGds7ECmGgGj7pWAgWpqOpB3iisIr1d/DDK+PYhEYfhY1uh7dM0O5KaMV71be1hIuvAC/9+L/BpZBr/SrVojFrak1c/MAZ+HY7kPl1ffG8/aqcZSw51CCuxKTnjulsU//d2hqmbanMnpTrNPmPTG/aGU9da6OO+JBaNl8cNe8CYLzFV4lhTa0bP55qOudrSp7DUC5DINJUHuxnz0DWkAGHAiajrOffRqnNK3GrddxHjPglOmg+Vjb0eSrxuTjb0FDY3UQXA2Rgblxzs+du9Xx/B36kGIn1rv1aPWQgCtmJKrDl64qHxYEQ9kSHjKTrs30qj3KUpdOfnqm7q9ev2gNd/Fy79oJA0ZEil022UvB,iv:y8uarywPqkq2tAEuGn5+AsNm+XtQu01RdhMZFnaS/X8=,tag:KzHsn85EcxN/uuEpFUsCjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qL+UzDTdYL/4AX7x1Qa/OtRUia43NeejznUpuSYeanbSBZl+C/3yXAV3jSMRfcGbcip6D/hRaAYaeAwcRyiS/ydrHqDjMCgnz5W9QRuQWWQ0esvWXl85142cKoNLZV3MnmyczfSaVjhY8M7R5fvFG0blNu5pJ321/84mITCdDkS9pondDDPk2LakjLIBpS/I83uj7BODoe57NjZnN2T6fs6RYfOvR5psAfwVE7eGrPaWN+KsOy9LRA8t6DFCUFr+g+9oUw8AVxseQYKqpA==,iv:wDxD3woQ1bkAWP33VAS0phIpLQI50olBC+2Gjv8LKxc=,tag:YOLX4T8k2aJFUxoI0WVJtQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:nliw2tbkeTAaoxHJU4HPQC805DmJbPantS1iFDmJUtqP9iNYAsDCylqhSfWmvR5i+berDxYiIqcOJuKJTO29+tUZzz6FlM6GgqXxP/XGGtdJFZHlSzCDS4/o+9l4lhtbY71I/ceZpwqEH+GNnwy6gomt3y+yvEpufZy1gKF3cklSruuWLZWCbdB1YFMnv0K0t2pmS1FwGMG1HjUeu3wXgXNzpb3kR/HrY5aA,iv:c+RfSMDxXqaNZLP8g07zH9kEJAo7IkmOGJuHESisg7I=,tag:nnlsRf/kcd5KWhBT3A/UWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeDNQMG0za0ZYTFNRZDV0
            RU9UdlEvM3NuZDIxWWRPTGhNRUFXbjdZaXcwCmI3V09xMHRORW1Fb1dsKzluOElw
            MEt3SnQxanlMalJiMHM2SnNsTCtuRzgKLS0tIGxSbTJxcHhHb0FPbzNNVjRaT1M0
            MmpCVzdUbU5Cc2c5eXByMTVmYlNOSVUKMH/Vi90fCRF5dML39baTmsug0giEqt2o
            wIsHKannT427c6KJc8gQk9ex5VcbCZBjA8ZV0ZnFDN8gIGYI74id4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T22:41:09Z"
    mac: ENC[AES256_GCM,data:UOEiSZpeXhlVk6tiNfB/XryGZFyNBQgEpTvhYjEVAdB1wlJfzhTVjasLJsUnON6dD00X5sUj0rXXDdlW6qAImlp8QU8PSVX8hJnBIqV54JPC+dbQebQrKHrgs3QTb9dBUsxQzoS933Z+LWW3aqFlBwzAdJcbQ7kxBs0zN0is08E=,iv:zkKh2ToefRVzWT8/W1z3fIgt5sJtJhaRPp59HXyYqeQ=,tag:gYhrhYtZpyLFcV3TbKYN/g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
