apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UP7xmxe1TV+mSgr9dcv/xrA4fP8sDtxHRUfBqXFkNDCv1nLoC2PqE27fysQRJmErleoi8B5XYfXP1HXW0We/rkMfUWK+M1LVXjUz4APYX8raJ1D0OGu0zhIyEXUucSyibhQZowTbo062vzzQLRUQLgWbmzsNJcqZniB2KOu+h2XPcWx3dmAk7nWByBWt43uAoF+SwefmvVR+VmJmIFeoAlD9pbKzbvRldD3pxNNxGpMSGKOdZdz/+VUdi9ee8wQivRfgQWQRdCOwEeFATiT+VGaFesYpMaqDUEHjPO/Yaq5nXJEK2k5dsOLOsb3K9MRbk9ZvOpnPSKuXEcT+xR2KH4w6YxBmurHndCcIDjPIjgqeXbcHV/Xl1FJl1c+Y+ref,iv:PQD2pv3o0Mj63M8VZZiR12eespohmb0BPXdJ7y0K2Uk=,tag:ioqkdEOXT92e/K6ZnSIL4w==,type:str]
    identity.pub: ENC[AES256_GCM,data:hbYTcTEOdr/blxo8B+6AKOXN77Up7E7jV1Z/JEgCbzidkxiWoMNgmaiUCbbaCbTXvXGDOdJ/1SpeaV97pvvxRjywK2COtfiZKZ+M2by7jWnXPQR+GPa7Oca3NEIExfaTrSK8WeJnsNHxZR3CK/KIZx7WC3CTkprR80YTchHepV03+i+mP0siXAXprmm8NlZgpScKA39VLB9UHlHfgHuoR+bBeo40Rq98KaZqXWk9MRtGXxzJPWDob8KsM4u/4vm6jLz4EHK1q4RiST9Z2g==,iv:1cgwbpZvtlMOnRTw+PHfrM+2KQRIlV88iskhFjx0KSs=,tag:RbCw6LqJwjiLRLCHe1CrXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:15jOFBmAbYGM/gbjZv4NipHud7HazIOE1y69Y+i1xe1uQO2mjHwbvxC8ETUCBPIyCvIykUXWK5RythIdwe7WiTfWAeIaIPeqx92S995axSePoXSa+HV7JLF0wADusqn+TqAC+y9i33mK3Zhmcbgtv253ZH7cpiw4L2B4JV8aWEAtnIu+ZgLnDWbGKsICYhobNrnYif0UawTL+XOdsr7yQKreKnOtf15VpFfq,iv:Hvi/HLBGiZXE9IaeJaDRqru+6ulzwDUWs364QtjdKB0=,tag:pNCBxKaKsZBrUnk/mA1I8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qmw4WG5YQ1NiNXNJMTJ6
            ZnlQRVEzbXdsT2ZEUnNleitZbVdDWGR1aENJCmFCL3FFQ2htNHNYdzNKM2hRMFZ4
            dkJsSlRJNGNUOExRWk1KNTFlbHF2c28KLS0tIEdDTGtxNCtpcUNaV2hnRVJKamVy
            Qi8xTjN4SVgvVTJ0K29NUUdHckQyM2sKk/ZmgZ/N07u5zHZHM3NpUC0RWp8wTIBr
            WxwqQ1hZbQQ1RQ4tbCvKJfdpzyYh7Xmg4kiptzuxpGh+gyy3ZAQrtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T00:54:21Z"
    mac: ENC[AES256_GCM,data:cWo301AAcJbykCT0fx2sMIz81og6Rhe+vDCJD/KGHI5UEr0tR4nrT7lkSic+GzUSGRq1HByXSplMao9txnjofJMtKw+tx5siM3R8Tysh1E5gKD+JF12pq31EaBuYEPHEBUfXO/sC2TU3DIXrsje+A8CAgoUEdNnNMiJepX1LnVE=,iv:IuUflyExLUGdDp46Gi/dGLTZ17WO2sowew5z7DbDG/M=,tag:QwPLjrSwn7Vw5MqyOE86kA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
