apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i9WdL4KqbCM8KAuf9f4MbL2sF1bnNNN1hCDy6P9jmREjZ102weNEb8SFXqktR2AvoqWu7cx+RwSW9aWmhrCImx/+F4nXnT6oZafW5u5V8JynIK5J6Lo0zhSmYhrKZcDK1JSwYKpECEcnQjh7dDY4O4fOxt0k/BpsM+VPLDGSqJb6D/O6lFS1P8tJRZ2QS62/enUXjt53WM9Tmceu8zAY/myMHGIpxiSDmP2ixB5mdErNB4bOq9lGLXQ2ou8Bi4qVRL0iMs+rWdV9tBCwBeVdx1GTzSxmLzQ5EW5XDrRpDFe8CRH2rdb2YjE6Y9bQcV8H3LJJGweguiX1kFLcgqisY2V/YC7xTrpNtSvS5JNHq/dZ3k0b8LX7Y4CeqjgP1X/M,iv:xqRrBNS8+F7LxD9tFM6rcT6jHaUk/z5zuncA+eI9nR4=,tag:afsYMYKADxi6amlUjKeOqA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EQ2EXsdgPg7A1nfnKMohdnisiqbbPz605QyvX2Cazh9D9LSWDgPFv+BD2wcXS/QzqroP+U49EYlYjH1CWsoG4ibFnivt4OoWg61n/Pb6NdSWDLe/bM0oyLiTebRrfhtZm5AfgN9ATp4hVpcINcLtBxjnaxlUnSQ7w9o0/6ccqB/9/N2GB2gw4IPHd8Sgf8eGtldu3M7ToXLgzPhld9LHM24Eg2To0MzewLH05jnEqxxyIAmYZpY9ARzy5vx1+GIyXDxSyzA5N9CBJGiQrw==,iv:NTJVOhT7t8tTMLPsXH8a8p4L4MWfeZQKqTHfpDRIAzA=,tag:JM+NYxqL1nzj2j4/0QdjjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:upt+df2Rlp5A7udfHk1r3JNCnRqIZzi8tblX5OOSUUY93t1lakm4p1lDR4GBJ2qJTR9rKLD/SdIiIA9fu1o3m3DbU9e7MHZBl3aFTPfDSHfbvEt7C4Acqg3MGPnuXcwfJDcpDQYfS58VC7k4j4hLtP4kYXyfTz5AdyxX14ANjuP/t3g81xSM53mmxw1W0yfiwek7CmaO0BsdZSWIQ9PtJ08VjXS06iAUNlm7,iv:nbud884xsNbKOVrPiM4vuZD+PfrPoi04YApEFcSOTg8=,tag:XAScpD4GHa9fyXt9VHMuww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVlZOZU1LKzZIU0VBUlBu
            UHljSzVycGczUzdaMTc2anVydWMxcFRiWW1NCmFIQUc1WGV3akRzV3FJMkNSYjkz
            c0djUjlrVlROZGJKTHZ6M3BCdU9aWDgKLS0tIEtGVVJ1cTdyMTFPRmtkUllPRGVH
            NTA5TFR5TjE3SDl2aDVHN0dQS0tlcncKzh5Xs4e3hfArPYdEn6zG+6Gg8Vfh6gEk
            E7O/R1ssGmQmr7OZibULX0wbyPSdJPGNmIyt9VoejWNsNgoY/R2vXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:08:10Z"
    mac: ENC[AES256_GCM,data:xdZqBGZMe+xGDRKx4TlEztHdKSKk3Pvw7ncxENHFVzMLZpXebcLVOb/sK7cdbNx+oUGUJ7uAR9j86b7Jys4hpiGfP5Y1/R9EmLVYiUFoGFuZfZi13SMIkfr6AzrY1bjrvC6zO18Umyc7sWX7wwaYshH2tbNJOMwOxd6dVtgPmZE=,iv:nZLpxKg2iOVcjysJPeRncBJXUT4vdrEJYjRANmjTZOI=,tag:zJ/fzJR1ENAPvo6V/tPdGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
