apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tbD275B2TbWYy2AK1tut+jOYiA36Y6vmvYLuAuVNkLQtnR7S/xrKrF4qQrOwMCKvGs7CtCg+lCnj3r5aewi/j3r8aqRB+7DUFo3GC14SoOgAElrP6aM/H8sqkLYTqQPPDYSqxbJ6tpZjSgROFCCZlh5JUR/qau2CBWf1lmRMKROUmEqALx6SNVE+l4zcyhm8eVW1dhF9mVQucrN3EfwmNvpCRTW2C9aKJ8Tbx9vdJin+pHlhpI5K3N/PCcfovHDBk75Id7+btqTTaw155A8+uIy4+jgLfIZN0sQgQIW5qKgZ6xvpDdNyP/T7gmizYO4W2AH3hZkt5YiVs1buJXioDvT64IouYbWsnpDrB3JYwFVh1kmF79+aKC+tjgB8qhZp,iv:rq0KGhfVy4Yx9rZSgUXfsVhEGKXyzv5YQ6u7EHmuko8=,tag:mjOdDY7S3BvKtyp2FOrWmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7+x7jGLVc605zXuApJzgTEK7n2eipKJNRpsnFGRG3YuCGweHsSWQRqJ4Nny4kFTacQ/Qrx5Os8Tw6c/AqM2d3pknLWpp6k/GSh2EJJBj6hg9adyD2PXd6yrM9Le83x8jhkC8V8jKK2+QkAP1LAaAMsNNZyu98XpO9oeMorHyqukfnUTFIX8TYFv/RZX9e8b7V1BV7mIqir/5ARWtqncXy6Q59AGZmZMA2Wdr6VDsp/ASoUq8oFRSQbCo27gDz1NYdCSCsMZe2jDWJNp/Gg==,iv:XnDHU3G1eG7Lel9b3R0O22fcQ2jkKk/JTxS0MY5awOs=,tag:/43vZDQwIasg6Vxn1Rh5jA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9bnusRmDrEn6KIemd6YhmiC5rUowb5Ah6lBTKA947cDDKsv0AKD2LwII7O8FDiHCjsHMi1cOj30e+OBpBJSD1jDWeQkHQKT7S6wYr9ltKqh14nME58+FnMnN8ARMHXvXd0NZ01OVmKEwAE8fnqJQrjXEqy75Oo3iwDmiC6LgnfiakCGdSwmfWZZJ3+Wket++fSn85W+3GFjs6G91ZVzItCpIRtrrfAu26zbp,iv:BTCgcaNwIN1+S8Q8efEL4OHSJ00/2fqExPH4YhcbW64=,tag:v4m78qEvLm7zu+kZKZzjCA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFdyOWg1WHY4V0liQlNZ
            YXNOdFV0NnZIOGtCM2hoNHVIZzNHVWJkd0E4ClR1T0pOL1V2aHpRU2lTc2U2azVh
            WkZlZ0VPckhvT2VBMVZ2Y0V6dlVFSGMKLS0tIFpxY05IRUZWV3ZleGVpdEx5L04y
            UXJwWTJrTXBzYi9WVWUvWStzYjVsbncKkn+9T3R5W14YD2jgn1JXffAz9mFJGyVc
            M9a2hD6vJ4WY/B0ieAgLfVVuxih0uFULXCiior050mkpmwgDhukNtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T23:01:57Z"
    mac: ENC[AES256_GCM,data:PCJkVkxPRTTuTL91OV2CLfURQUonvpd+3voME284HkisK0KUD6L4/2VMwKieyuovDeD7uRnwGCgII43uAtPml3YD/UdH/ELVDvG/sxwgAP0fxmrpSBIKkIAqdlQOF8FUFEDa2mwClC6pPTqEuX+6cLzh1eRMfBTIRNcfzLNSNTc=,iv:ITcK8XEdUKvbfQADSLTW6KmVgfnQynUVbekq+3QMZqk=,tag:0IMWPP8bNmf3RXZPzcykMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
