apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B8v4inkhR5If8NCA9MRCXnY2noDsV5VEyoiAM4iRHSF8uRGE8QLsI7ATWA3cXsw4ah2iT1LV+B1C52jzu3V3QnVLDBLO4IfP7dNl/Cu0kHlhMNkgdg/RtqvmURpD6ckn7chnxmuoB5yxNOp4/4jyt7OYMUGit9YGsr1LX+LO1xEt71yXi2N8eEaKImL0RUnk7PcRvpAUS84d36/9J0grvO4GJRgaFotRwsCXvAqUXthHeYlL8wx6C73XYdmpUcCglYh+TgylnQEZq7B7nlCDwGxm/ejwJEdATp6Nq3LeRvcT0ForKFcBH/tkSuMGnb00Ngv51CrCIurQRUKCPQtUyCjTjQ16eUn5jc6dhfsG8G5ZylMaZDZDm7eJhDL8CsJk,iv:xY3rc6Uir91R3Lqy7ZbwQniYhh9ORj0oT0W20IIw/WY=,tag:+JUNbDdNnmkcWf49V5PEfg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vvvqnnNJsrkid+3AvJOmqyuDOAWMhrsxDi9Ud2z8Uj9ka3QwsWb6ubY99BvUKaTvRrAjxbGjUBtGEocZgshNqRTlfq1CPu2BUKI9l+kh/n/aUF7mEVfS4MPK/mNyx8yhLcZ6B7ivx1AwyFKgA53OpQ8H1RTGZ11BR1DHFUD10qyDKnCnUKq7hB6pCYwgv8Nd4FyDyHbAQHMHm1LgFTczF9HTFyo+3hmmDnSwxsw2c8uVVOcBGTag76Y7o83yxlFcjPj/Ea0IPrHyg+ToGQ==,iv:/UH/SaHUpL2P30EYXjRdriNJs+sJyvIB+uPRnwJEUsk=,tag:p+voG6JIh/gdy0gxQNqBSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:MSDX5i/8aCtkpqLOBp/yvpXlKj33toVyuuYItjWI14DBI+PGbv7JbNrPSOWc5jj65qb97KJ4zhmn/F7jAwY09PAZQu1zoiNfm2KJnWnN89WWnHQBOwOGVVNYsihlrUuWTTg6U0fp9hud9fa0p0w9v5cjDZ2W6BjpL2dSa+Ns0nVtMALXJt75HbBpUO0R71L4+dVkRbwZln2hbFZ9ZMD50PkMjNY9nRFnImp9,iv:6HdqLzWSpe/9Hr1RaSYJmJEMnEvAhiWTCTL5wGOK/3Y=,tag:f7zpwVGhiTwvJPzlIUWpcg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2vu8qw5e5ppu40tlt32c3zm0flz23j0z8n3nyp0ng3za727qu7qqs2p25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VUpsWTJHbDE3Tlcwb25O
            eEo3KzUxQVBqeDgybTJwdktyRFd3NmxIbjNzClZJQlBsTDdjRERIUThIeDVPT1FP
            WkFNbDA0MzQvTmFocDJzR0plL0FmSzAKLS0tIG5rRVkyYnBXZmxOMnk5NFZxblh5
            ejNMUENFNStkT2VKK0E2bWZuODVCN2sK+DtpSdlaovhsQh7QEa4q09RSfOct7ojK
            Lr84Ohc4uBR0m1uoRr6kK1dMOEEAzXDwKOddI88Ly4OVX9hHklK++Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T18:11:45Z"
    mac: ENC[AES256_GCM,data:9iIgjZvWJtrhphoC+UjhI9sQ/qZO6sz5aBhW9rmZy1JGbYTM0UJUBTnI6Qkn84gLslzgx53YixApZzxR3SY8CbdI6Ji1uw5NJreYVLfIfEMz3bWdYdHR0Dsm02F7kEttsBl4aT2+nhdKHlNVEXX7bWc/yXzM2SDtgaBHvQkiO6s=,iv:RlmbTXGpu1McfkfxUiBEtrKtqAwStiBnc5O/SrZD5rA=,tag:a1GIM1BJt3BRd4LftyVSGw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
