apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oqWgjKlFke5TM52LU6XuNcSH6zZo/uUS9y7LtPycUg5n7AsoyNTBjJ40zWHy7MWMIPo/ZbLshfD3Rk4DBEfHhBCYqvQ5D/d9xittYqH3sTeRUbK/mC1ibBkOIUHPzJqS/niWZYFMCu+MF+1u2iH4wyKlvf+AC1N5ZiEX4eJcHdDc0Kv6r6LCao68ka8r2dENnF6zfnMUckWtTVFWx2rnuFd6peUYA9mZBKvcKBrpgUzc+UPPrpVyxd8zQ0aWBI0Mfps+eGxfM10pk4wPzQ7oStlWZthNP21JHqh0ybcCM3BRtt/UldI+Xude+QDDOB6BaTR0KlNjhZtsygthP6absAvqdG0wiiowlfqBZ7oKQUUNjyjRJlWpts7ww9iQcm8r,iv:3GX01ROYH5rYo7ZTqXYJovH1rVloaFyApZ/Zxho/6LQ=,tag:nMntk41zrZR0QriCrhzZig==,type:str]
    identity.pub: ENC[AES256_GCM,data:+A1QH6+B31cdfpNDbOeG26kS350kssz4YzP2mh6t1wKqEbQKRQEsPsO8V5xlpaYSj5uTvgCqsDLX+88fH4IfHgTjc/zMKWbj9L5iymylpDO3FSy/vqUN4sjo6E0gi4pEfI3RhJVERs4qkofX+IcWC6PxQpWSC5YWWm/vv0TehXh7HrIwYavgLHXKJxIUtJbs4kuuVNO1HQRPMUmea7mtDaFUb2IhCU7XZ3SjQVUeQ0/YSluTHND4sA6GIqjCy2ZrL2BhHIgr6QIc+AMnpQ==,iv:0xK9O/e74BoshIVvDZ670WbgqRo4Jc+0N+k4TfHE8VY=,tag:H5RupmTOroLstivGaDNFQw==,type:str]
    known_hosts: ENC[AES256_GCM,data:fmu23qMnw9YmIdRyGc9W60ETQ9Lab08CFfhEE3kPWVogdYoSpoOwUWEVIOOKu0E3P8cMEFEX4EWcAU7hqzOMxZ9QS7s6o6K0gXn89AodhlYcoqhRY3GfKsKCIXJDL1JDEKFc0tMZ2kdm0mYLsf0eXZvt66cueE4OFujyknajyPtmscX8mOp9Lmzsiz1oMLsizSBD3qb6oXYggSUXJF2I3vG50XU3mDSzXhCv,iv:h8P6VyXMcY0Xa3PtEf5OMnTndbesoaXOr48Y5eb1gKU=,tag:IOPKJNFmR1bAzhhHwOSsqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuME9kQW4vcEgxdFZCUWxM
            R1VhNjZ4Nk1MbVZZdGF2dU90UmR6Ty9DQ2tJCkxNd3YyUU9nblV6WGg3N2JMTG94
            TjBwWDdNWlNPcU90M3dJajU5QkFyNzQKLS0tIGxPdGZDOFVlN3k0S0tSN0hRNkRR
            SnJGNFdLNWJtbm9LR3ZYRDBkKzFuWkUKsV8QgqF5uKbfYtDqiiaXffaQhrsFP5Fu
            jLx38TLug5iShWKBLYdsxgTomS83TVRV2XV2KR1iTPLA5VsD0PtInA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-06T22:05:54Z"
    mac: ENC[AES256_GCM,data:BlJYrLMhC5RZJ9JBZSMIxk7qn/8kiAoNmghECubu7yvXvD1ldQDJOzwCnqHgDsGjjabyG76g0CcAmQuDFBGSFfw+jRC1lu46TBHhUIvusrv4FNPmz59YL2c5wEfUzS4j896ih3tIRImbU1jLOdr7goF8R/racbryyKtYLSPRKE8=,iv:6OUTHcR5jivTTbn+Gj8wbL9R59vR7w/3a5svGJTTbRk=,tag:/KXXD37ivoEz2XpGru3Egg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
