apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dcpcs/YqpnaMszoTsosbRgWVEqiLGJZS0EVlr720OWxxQ5YNWKWFVArEtcSTYKx1eMGSYgzWYbaOL7V/ooIHJcuo/f1k4/dMWTgw8hErRSKi0+BMYmz2as7Aeba2TwzDNnrFyYRiiYPenKxahkKQ+KQnNDVt0uoUb9vhtYQhdl7VcaTT4zxtc2XKoDhofJKnDz7RDfgdMvR/ru5IMZFVuaFnprhQ5aUdVkoAYqG+qmk2yFv2/a2TkWnYcsr1PZdceRePlkY6vIzctBiiKxnBk6KGGvZQt5Y6IlfxRRJSGziCmXXmQbGcXahaJjooO/t0L/IAGCjfVpETHhxEG7GTckirW4PEtknfZZfL/15GlmHY0zFiLlEE1dWngssYinsP,iv:3VnXyV2f82vlW5clwUFmqsuTli0edvyibWvSo1jtDoc=,tag:bpkceqtd2Eqg87FIS3jbcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:HHa+igitfJR+ErLhLSetaRgs04HGOakVJWVjC8XnQ8HiuwftAcpR5ngd1DuqoOTuqpEaJ/bZRBPduifLJXSWuRiC8OYpRm8YrEwwqxQmfyUVIvZbD72twr/vOLVV/arD3oG7/KAvno+3PM366zsD1Rj8Z4nhJLn7mg/MqjTpG16uJKHML+mpHnG8Be/cfnX0Pnf9YRTEGsiRS1xHIxjU3uRz1dy0anEBvBX0MK1ZvzhOsh4h3cWaL/QLSLwehyItxZ3KfTY25971WGcd1A==,iv:p3zN9LCUvg1ou7AUoFSaWuG8FP0EdopBD0u1o4+c4Tk=,tag:/vNFJT53Nc0FnARVOrpp9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:XpDt9w2i4ZMPPlBSRHFOFQWhVFrvp5cD+ShehJLQxj2xUkEZhrKGb+2P+nXlQTPwRUgu5n5OcXxBdq2TQ2JtYPLWwJUPHAJO91O7s17gfaVY7KQK4L/vkqmVZJ9m8Rj+5uuqoePIj3iKYO6rc5dIdpxG4/LF3UQ4O1GWK9vfDGqMB2I0I5yBgsROYEhPglkPHP2Rv5Nw8X/iyiyw6lLV5cENAMJs6f9xpITN,iv:Ub6TqD+fa5n9kl2dIrHJfIwFYYeLEGTRRyTwdxSVDbA=,tag:aFB0rzCMlpe+HHQgSQLDLA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcnNzTTcvSlZvY0FWbnZz
            SjR6alp4ZmQwNDRNUklGUi9yRDdnUU90VlRvClp3a2QxTjBPSHVINGdrWnlrblB4
            aDM5OG9UNkpZUlM0MTFaY3J0akdwZ2sKLS0tIGY5L1RZWUJiOGRFNXFyM2U2Y0RU
            blh2aVVtRFlqSk5CcW5hM3c5Q0tkRXcKN1PolS2uP5rVXVQQuFziA56lV0S7ljzo
            UOhDSIJvFRaJ3p2qALdthvLhDPYj4Vvmpl+1ph/+Ck1k284QjuujBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T07:17:13Z"
    mac: ENC[AES256_GCM,data:/afBrC+9ZBpmjBshVPvA9LUs6MO7GqmJMG0vr5jWzJ2k2sSTMksEOGy9DR9dwrmfpJRJ7d0eTYIM5Ne2ROSkTSAjA4vcfYtwjfyrrdhQOIKGzdXKbkjysp3JX2JefdBPrVaY4/bid1vQoWc0eQdKYpPDElUW1/u5AxPw6ccFVI4=,iv:pseDXmIZKo+vW85wA/qK6L66qqDFYUC6ls5Y/Jvve8M=,tag:wEHJzJjF3kDSxn4eRiboPg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
