apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:USNJu9NKcdMN6X9HdVSWFBy3bysWV/Vdzi7u7jkK11Ecw5ybLMrlSTQQZQlV1B+hg2edXbY/dT3LedZqOnOMX3HJNtuIHJgNLmn67PSzed1Z7cN+JQ6xSC0Y94FZAwacP7XbySi6Gjo06Rd7+ZfU+PY6mntZ0l1FglHEU4oPv9LWATRrN29ZI054OoQyGEJcse4tfn+vqMybVcAF9SH4Ax77Gp2V5xfEhEvDQwLDDJ9RB7qseR55WXgwHz9Lj6BRzVKokR+SQ94LmX2+KVr7ibnXTBtt8W4kjMwN7hy1OeT/94g8LPhzh8DLB4wvlqIt1c3UHbaeB38cYucwklgqhuPIlq4zU697XTkCmtSV/jJSpMeaQSLfiHtqo+1NEVwT,iv:4oQ0lOF+V3raaMgCSFo8lPIKMyPYRsf++FD+sMh3pUI=,tag:4F1mXuSFKEZkq+5vzZiHxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JCvfHO4E6Yy/hTvRJxF3ffflUgUsQeSu+uBq3bmmmtfKfYvmvyiP4VULetQaka9hBQdRvDbXPC5J28Sfs36Znvc7jcIwnehaYc4tvna9Dow2JMe9XbovGhhkKiWCkNL5IZ5+4seT2UZDzQrLMGHmX8yAwP9+aAmKjielGuUowBJCqggq7pS7Ri+fZO8vmmj0fUDs564BmzufSLAv76wHWr5P03Xa1yE5zv2OtLYZdmQGKjrvtDGfYR7hJiZb3wjotJ2b0Ivh7Wj9q5QR9g==,iv:lkeYqBn1NrUnraLT3xZmS7IvFgJnYrJ1R4LydD2D0g4=,tag:Gmddo6suceB1W0XkLWqu6g==,type:str]
    known_hosts: ENC[AES256_GCM,data:H0lI4dGkanvsBQ06N//mPyFXJ7bCeNJ5aQgiCjfuRu8oNhCy46a9o7fj/4ndWpY3vI5nup4x8n6Xczv32LVz0CXOcBvKd+kA2r4klVnPs+uQFRWlvXgi4cJxdJWZprT+NAw3/ZqZ/3IWSTgdIJMmn+pRBc6bX+pYdCihowJf7uLLi0GiPRL7V1wra4eCM2Em+oMYqZzAnJ2Rc9EkBIoRl5zGbixwduDEvYs2,iv:UrXDvqTtznP8Q/NqIqxau0cv1z87F9/ggjMZeYr/wL4=,tag:LqIj3mUAQpMEs9m+KrNsSQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TUtETnlDcTloOGp6SHBM
            bmM4OVRKRm9BRnRpbEgrUnFxcXB1MDZ4YzJFCmZFYlAydnFHWnQ5TFVldnlpVlN4
            dHUwY2RkT0R3bU9VQXh5OVVtR1M1YWcKLS0tIGpjY3RibGxaUHdGY012WDZvblpk
            UWYwZHFPalU3NXZDdTRaN2RoZVlpa0EKf69hiVuQDwslDo5iv7KkJPWDWGcROdDc
            jxrH1pIWaVOspBQ7DBtTpai8P5RyxkVkz0fxAX0R7iJqEcL1PJOS6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T06:32:02Z"
    mac: ENC[AES256_GCM,data:W0EqZFyGscnShHgFkQhRPeikptZECFN8LuqcyzrFVOxNQNGsIBzXz1SfjRztca/Hn8v5wuiXVuRtYbCiwdQuoU+qa6Z5Go3TdDaXXsxUbQlpCx9aoH0Gyx3Gn1rAxhe7IaJjKcz4yYUmQRBHVyQYIUOTdKCvdKbteMOVbNG+9EU=,iv:nEIA5ZzR4VjNtfB0COk/hS3DTTIT39L6CvQhsxXAvz8=,tag:hWepyhstxWWaeO7D2M8uFg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
