apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:h9r2NgvTjlXBA31arnsSSuBAWk+J59HM9u0y2IsfchDY9iqeAxEm+hI6asdqe0EdDLYA6YL/12ruQIIDWYvgbn/CtyPoPH7M1Bj34bicu0rbBouhh02N6SKYYdjTTj91xRorDmvzyMob/6J/rUDV1zeIDLpP6YlBK1W860KK7oVELF6NeHH0GectKEaL7AiBcBE/DW8JQFzp6KPXUsIZ8RJ/816EzcVO0TWDFMfTwkCc538JHOP3LAR67rraCrOt0fuNe+KJBs+zwstrUBsDRSQfUARn25mlDxu2xOn7BF2xIPsXhBMIVqwfTslU4pyrUm+fid4qOVIEUsGV7mDReeBEur/lkD60D7ETuSg9Ko6avolGzkMT5bese0GesGnf,iv:gi8vdP2RdPq/hdD2TSr3DPGY9YALJRI+oRTMeH9SD5A=,tag:5gBAKY5wyAlCKbgwnWsaFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:9l83At+07dwmb01CvIAEthSB+dPg2XdT++ZVvRDoAuM0PxcBVCWPQSMtTgD1bQaSIxvQ1nfXhLxsLGTwq1NJoPLwwn2H5zJkUbgOSxiTfktfKJcr0tNoWyH0fqW+C9KNqCACXF3Aqv6cKeLK3Krs3Gv/ympN7kRfdh0UTrrrMzsFYIUtQG/WTnRgL8IegYFTt9/lzi+9egn+pXHG8byRxKj8OdG20hGYh7d/YNck2cUMs9So6fMKWidSYfLUGu6WcfHdd98rAsc/vDtQWg==,iv:CBFUzM/kFpe5a9eoBcP0YiOboHeU/+QLPSBUzkLmLwE=,tag:RrwDFxg3wd+mrOX/JfBrHQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:KuObewqonX6drtuNEfKlS3524KQNrgfSXrIMnbpuqgJvi7VtUVXGOoaqpCH5zhG4V705wVlb3oMd/PM3vAUrBIhxw+jTXOPrYy7pt1SITRp7qkNtplUzm/rMOGxFjoIkfe6EDhAhKnBEb/GMO8cz0nbQ5KorcWc89kGYIPaIwbME88NrA34O8zTkHRwhdUXJPRumtx/3pOlaDoHVifUTpRqvq225w9VnpiKX,iv:08gxn+4q3FUjKrhE8RSNlD8/WcQVlrV4pdVYYeHpe+E=,tag:2HkvtPgHs+olpbWnF7YV2A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wns3u9cpkrx6s5t9end3p48xvwrpr3rqcfq336lsmh0nwwj704gqqgh522
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUDM0K2Y2ckNTZ28zbWdu
            UWtSR0x6ZWxlbUF4YjBIeWMrcWhrVzJQdXhZCnNDZGpSVU1IOHZjTTh5dGlneXB5
            cHRTVnE2dHN5K1VSMWRWZ0I4VVprNjgKLS0tIE1DejJ5RXM5T3dqenYwM3U3QkFo
            aVV4bXROVlJQSXFZTGsvcDNYSHdnd2MKv9J7m7zelK7KAFoMgB7uXQeWeVzRlrl1
            5jkJVy9g1fz5dNWVFEGpHXdlmKPjTh9zAPtQqcq5PnVh3QRBzayovg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:48:01Z"
    mac: ENC[AES256_GCM,data:PurgoXAPNDcvny3zgML61USYOMxrKDoQc5qiPrIvPvJJB6Tf+MHdfRnMKKBRJOxOALIvcrCHux0Ces6bk41nznTS4AA4h0mYPOpWaAV+sb4lhBa9lsDUOH5g1aYWQl7W8xKBGtovoj4Bhy8auUQEqqJ//dgERhScn+yMLVBbx+M=,iv:N1RtF8R+YAoJjzlBmbMdARiO9o45NH6ixO3am2yx3vc=,tag:lQlpkn3b73bzBcdHbI/qpg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
