apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jrifO5QD+g4LIESY51NHpcXe/Mzkcz2gUwZFYi4MjmOWL1Fl0Trru1mZav/EeP8tEOZUrWZnYJJa2xKlxiFkndT59MPTSCdHePqhboaMIiBTQlYsM17VAp/VmTmXuiASYFV67CQ25rcOhuZW/fvlH0B4RZV1lSYN6yIBSoo/GPDV20mLZ0ue7tb+eKNJov2YM3iqn120p+a3AVLbjTJhYk5mT/v+wadWFO61+TFhb61BKXbpDq/wWWBpG9IddDOmCWEEneQsDOpZ5uO+nleGQmo/V0Ccl53GA+K+bxkxUOhQIUFvvvr/OS/4UNTRnAJGu4+ynosCMDkd7tpJEvzQYkLFF/mjN0jdMdekKC6GRfnpE/oEXOzVj7BLLMZmjye+,iv:o7zEtgbjerUxZCOb1IUGefTBNhAOMqSNsKPtrHZAew8=,tag:DxGfOCLnWBpeiKQukAlvvA==,type:str]
    identity.pub: ENC[AES256_GCM,data:TR8ON0iYp0KCwvZGxzGVv7dTUr5c1X853nS8SvaRvi5h9OxAu7qWrmoMj9kPcRq5/m2+kuw7Gzi1B3dTlfG40V/f4xUSQdVlFrkkIB9O/dIZ5aQVy4vuUsIZBjjgpq/gMg5eGJwIwTIvw3AD7hejUPV/h7RUuUuDsGszR1Xf6sK+QLRtNeXEhmKcaHJf6JkRuM4+L51o+qwl7tfl+1bookIvbtc66s7eyVhEdRtjtOmnDfl095n6BFC1tZRloHQpyMH+WzLYlhkQyvbNTA==,iv:XMUw1GeZ9iIxHFRfVpPgFHisW/mULPT1Nupqj61zDF8=,tag:wX7s1DQ8G2jdE6iJjmdtug==,type:str]
    known_hosts: ENC[AES256_GCM,data:uVFh1JUILFJFV717BpcCeMYiRyryBDXxcy5mApmZU+sn6nTORpULsM9RogkZu2ztvSyp3VrN2hQsw1UcBLwqofxY9ad6RIv0jzLiW4RZdM0rfaQ3IoJLAFIdNNJaUGQ6q3Ipwen6x+Tg9Qo3780IwQvjMjPw+aaqazECu6/Cf2Su/2k4jGTauX5X54KuIVJ5qa8lgVb9axVFUhiwXAmM3TersrFuVL0bbvXV,iv:rhR9DZ9mYNACigjmhFEeg1/h8FDweQ1bPm/a8jFoAJQ=,tag:8br9vlt/vzCsWQLg7Wilog==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc1pNUlNkU2xFdjVBNk1V
            Z3ZkRDloN0RwTlFuU3FvandDNDF4S1VzQVQwClFkQUJoNXNFOHMvREIvQVBUanVT
            aVdrNjBNT2NLeDV2K01uam5MNkIybFUKLS0tIG45cnpTYlZ5UnJFT09tbXFKNG51
            UEdzci93bEhYTWlKaVZ5elZkMHg3c3cKkCupoEnbh6zXmZordqiO8+ohoRz0NN0n
            kt3VHuIhbjVE2L2RKuNh55GNEilTuKEbw0DqICvVxFYwFAe83AMo6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:11:51Z"
    mac: ENC[AES256_GCM,data:OsSwDpQawAmZ1Pi33kKybxOdQi3D+o7BETSMDA24qwjbcYo5vy15u8Xegej6IBAP6EujZa8gdx7pq1sXDTMuHxCLXasGpp8CLRiRmtOIMGlQgpq45IN69AOfYdcb9pStkdEHkAnL/bNbotSqE9qvLOxnwzjaDqf7oWdjv68yVNM=,iv:TO676AaPXbHHDL61dthRoEw87d5JsK8pdB/OTthXbjs=,tag:RQTBXduqeSTJNFvIU15hRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
