apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WrK+xNcNBt1Krb6qywKVcM+wOnihhDeM8nDGSF8jWCUlq0bd0lMBYWT3loc/BLZWrmt05vX4Zkm9ombBOkpAYsSWT4V4DWMgsc82SzcesWzC/pN2OIH785KBc5vINx0Utn2HLQUHuoKXzC9mQHa3hissPNpYrS0S+2v2Q0Lz7E+oj/SRCABD8yOpNGWe9CPF5jEKd5gv/LkIvUW5U+JGcmbhK5rqHamqlMpqpsnRPg1xOIMuykJ4g7t71aCEB1KIhmo5eifneiieI4nl28995pFIZ+VEYmZ10DuIQNwigQXpvab7DkACG0V26CeAd7deVqEBi4kvBM+Q8OvgxBv+Z8xazKfTAicqLBvoLxUd4aXB5p59fy3dqe6Glc46Yk08,iv:3an2sJg6oAZar+d2yKTBdTarS//7ricw+2VeiW6PuxQ=,tag:R/oLC//XwNGIcTTa+Jz/kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QD6ISRYF2DSIlUaHqOpSUYNK6Cg4NtHeES/IyUrRGq/wFOztOT7n7FWityDOoyITVUZR9sT0j6SBFaZQCPSMQPDe+SrSFLT4fvNV9wd7CmsIUl1AbbSROpaNwI0rXKMvveQ9n01KD6eDWL1ARLG0/ckmN0rtBGZNnlH1WOjen0ioK4wxDNcjKDuNPecd9RduTmI2zgrRLFqgI4C93JBKQklvNyE6FTStjVqbBTub5DdbPlbCrC47cKFHmSIdQPi9MTgFDuihgVWxa/dqBg==,iv:OfyiVfMQ0dr3/LV/9U6g/ymtIvE2InVaXPctAkIfHEI=,tag:vIAN6xm/c4EDHlacQ+iX5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:zz171JyEZbE793XzSHjaixG3P1Y6//eLZfgnRQtWatx4USgafMgke9NBhSVPJ5xCf9N8oyaWcBrjNnz0aQ9tYH38QFuVgROG1vVAAIjaz1X3jzyyCw5MPaNe1YwBMRwFTMRQZMc+lVEBmtJKldTjVI398VyRpTvaW4qz18Im50cO7Mxl9eosw+UYx4WsaYZuqDtdiEbL9quMvsBsS2sWd6fpnp7kAAjCnSUy,iv:59faKKeyttF18uVZoDnE1V3QEFpl1JkeQmTedUNyRT8=,tag:WV6bz3X63lJKMt1iT0nZww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFRFYVlON2NodDRMV2Rw
            Wk5GSUtNSXlSbUhQdFF4c2xoanlYVXNoVkVrCm54ME1GQ1A5SzI2WFNmMnFCZlhh
            WU9IZXlteFpzallKMUNHUVY1ek1VR00KLS0tIEw2NFNDcm5KWm5KZmlHOGFudmVO
            MjQvbjNQbm52ZDR6eHBPQlptcVZQaGMKup+LRVP7bB9Nr1kHdBZCJ7fzurJSyJFX
            fA5+al56dGMoqdrzaYEnJIEkyUyWwYlhfcraiz6r+93mLYqlHIvrJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T21:39:58Z"
    mac: ENC[AES256_GCM,data:C3PHhVy53kIOHllPAmMs3DPeoOZcXec1cAJxxCaSsGdQLwMMJ+Ts/EMQGmQwUTsHS8XquhHvUMPV+XoB8rutei4zO6ZtMpb/RocqIvRi8XIcUojKvK1CHu+9F0xu1BzIJSmnybsFW5PmeiyxBjrZmQYlLHvApA6EIZAWwQL2LUE=,iv:BXWSx7M0HTFl4jVrrry0GSXZyPkp80OdB12AczhT7gA=,tag:H43nYhv83ijuh1CSxpKQ5Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
