apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GiyJAdFHlkMclR5dBqYaT3bQ2l7BMls/vcKMAmEnuZVv0VtXU3DSv9JkdrCnh4amWrBbm+LVg9yt2XKD3hKp7BUpLjF33EvUquH48IDb/fYJhkOTBmcPaYD2UL2nrQHh9/WctZNcJ4YwkpntP6smAJx28EFxUfb/bzfEhmVz3lOSp3WZAYebDKlkSpLb5dOhVQ3brjn0w1xS2tsr7QzvOkw7dT3GGc2xhdEJ9vVv63yQ0n0o4Ou3keq3iUTrPPski0pywsNTLnFbafMjTVzbhoLZ+ZVRZfcVrqBsYgNbkGAThGtm89YBTp6sH6tW6DEnQOueYR//CGd0Sy3yP7Wr0VgodNGt39+perzzC0PIb2SS69URoCrBUIgxEh61jwvH,iv:LKzVVTbRoBZ2zGHufc2GmLidX6Rz2dpIGBCYYhSlW0M=,tag:kLMl3dAnAlsCaL3sUOngRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:a2yUbw+bmgIOJ8GqBfdyBwLQXr4ZUBTChl7fMaWBgahvmU2ZDry63PijzQCn3mE+QrFhR94O2jFUmfL/O4fv3U91vfEGc7qas7+joillygR4edyCaLTzIjp9ZGj6ewoLAi41Q29+Avu9S6/km/aiX1K7ncDhbKF+ekQPiJKjOqm2pB+oQg5dCthxPqG5Hvm6K6vQOKEBWIhz19SJvIfPnSEl3ghFAxWGpYButDceU5zzl9QSE5y6VNUH7+DTzaRZYIc28I1c/mFN9VqLhw==,iv:arvQIWZ1pkeAulKbYr08/iE3MDC547TuoXqyx33KZ+c=,tag:w4VlmA7Z4JvGLWwTGnO9Gw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ugw2jjeGAcy5FgTDXgV8PifybmIShwjEJDRitde6Z5S1zytNID5yYItegZOZaILA8Tj4sYwIlk9LC3prTo9F9+P6eKk2jPPY+DDXIJYEVVMgFx4q/iYdc78tqoagrE/dxzl4z5b1RJvMRmMfCyRs7mbjICbWJP2h34H15+0V9ITjgLZ122TYN/bikTpfXYxW+N9U61ThKOKQY/n7XiuRfemoFaQWh7QnN8aK,iv:qtn9fSOH67GfXpyrPUR1lR0dVOO6ohz5+sEsh811n7w=,tag:lwbeyMs6p+v6nav0dUEYzw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbDB5d25RZEJVWkkzUkgy
            eFN2ZzFGSVd3cTJvV0lUQmVuY1FDL2c3NWhrCllSN0dqL3hWZmN6dGwrck9vRjg2
            YlJJemxaeGlBeTJXR1RKZjcyamlGMWMKLS0tIHB3TVdwM25NOWNEclU1V3BScTdy
            M0VVdkVoNWJVM1kwaTRWTzJ3UHd6ZFkKMtAbjmmyCnKMiN6fOhRYdcbQiSyHLnFy
            9NXgpBP37B1ETivLFi75h73gC6E7Bo/bc9OBP16D3LcKN+oMuABL3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T23:45:08Z"
    mac: ENC[AES256_GCM,data:GzsMwwpyAvqUuyC8zy28ziOYbsDD+ig3Fn98y5LZKI6eUDRwJkWOQmIrBWPoqDlovHxZ6euPEju94fFB/NViRIzPz2wkHYyN+mL8YClaIisarD44wSxsouP2SSyehsMZonVgTp8D4uIZP67ns+BJqjatyFLjzZCbXgw568OboYY=,iv:p7oKdkOFmxnWl3Pv05JGvanCxKD3JP1L07z2hLlsWrc=,tag:Oy5izSKc8rbbOF63681DfA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
