apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1NP7ZtU0jyMn+BkgYWveFYbrRAH9IHyGGAzntC7fEAJtTRTGGzBOz+YcekyPII2OUKzx+qXaONaFPJlkEFC11W2QfZ2Cni0yCOJfLnJTAtbvan47KJzVNthXXPv79m4FfkhsEizucjN0vX1SeWR91h9DA+ntLaPH/ebadpUobcg/7jdlV/kh1gq2lGRu+T6HH9/EyWxDET6fNQaKqzLYQA2OrQHfrws6tE246eEecKMXGb+kqzkKL/qfTHnusPa846t9U/E79epjZg/2bJifocemvTybTbzvhZLVq5a2Kkz++weXNbYiBpNAr14aMPgA7t50OTMYdX9zgqdtZkW1T1A/QjFw62EK3ZcopFE7y8bS1dB+TXAWvwM8Mie/bYgx,iv:c0N2YD9VjPJhIHxn+Gz64pZQH9dOdFyvpIOGAzVw9lI=,tag:QEmRCi07jORTleggdmyoUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:b+cBGmQO8KYv+VDYKN24qUcbfFkZZBaKWOzU5zln3SxboHvu/YwwOFaKbE8z/pAotNl3Vp8FY1nky8lrbO7DKtE9EtY82KGys7PbHdGQ2yEbKhV+ptK7XlGst4JfQ1WuCuReqOtVy8kEs6u3q+J4uDYkXEfSX5HVIg0VXs6jNSUrwaqYri+wLuPhbF920DqhYfx9UO7RPB2pF7rGBD4UGYpZzjtJyTFo2U8rDFyseqtnfDKCYb5oXoRE1Uxr2UMSfZGY/D1+S1ViXMvRQg==,iv:L6kCuxpLAgIqxmUzr/wy3PuYFrzM0HWvRlqHRxq2sj0=,tag:DRN4BM1rPyk5mC6VVALTAw==,type:str]
    known_hosts: ENC[AES256_GCM,data:7uHahdGwyz/wnNjPRZwku/dh+AbrNki5cV1GtDj8HB5qTVByPz7/rVzmRHniZIILK8yE/Uu4hIlLieJQjPBQPsDBeMZ/9CtVGasfvTuCW+MIh0diaOwLlCo9m+BNQND8Lvl/JeeByB322/Wvvn7Lc8kF1T2bzpRPMk2SpMGIsonhAv2umntWkNxszHwDA6GZqII4KUd9WrrUHXItrOkYpwPK+a5rqV6QkVdU,iv:1LzY8IcANWXu/PUTbUtRuvgFT7wZLqOkAtlSOhpacSw=,tag:9i0j9ikEW2gqsSAhy5YtRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajhSelBIVkVELzZNUUxM
            aDVYNWNxRDcrcWd6LytKRXNjSEpKNFl0N3kwCm5TZnA3b1FKaElkOURmeENWZklV
            aDUxQWozK1R6M1JBdVlXaWxoNDZIckUKLS0tIGVENUhYbVVTNGJKak15aEFsWVRN
            ak9zbEkwQnZiTE43MmJjWTBTd2VQQzAKKqW1R7Y8S4V7GWarExQMO5VCK3FI8DAs
            keJNsLJyv/a/dbYbz9Gw7cm/ZMKMX8+RUomLlXJNUYlLK6jABNwbxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T21:09:29Z"
    mac: ENC[AES256_GCM,data:yK0mPoTkee2iGAdB2tVyhRR4RL3t5AvuLFuf8s1WyJEIjGebiVPOifQG9xD1uCDqJm4569kypc/EXOz2AUUltFRA7BCrmuizbH7lXm+5sgZlHgwnwMlZLB+LttUCroOMLzJUFs/NXiUP17e/XOU35IWMJvO9Rjvy+duMHv46zzU=,iv:pTA7U6k498ye839HwUHEqriLBZdaeflRmMt4gC4c2yI=,tag:3X3SIb9CGzUbgFU3cG+hwg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
