apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Rwa8wsy9iVnIHkUzn+Qp1R4woqh6EzhUAuWr0+PBti0j1eGMjXSBdslPcM1khOSuegk0dPrL/HF3Wwe+CIdW2fzJo/i1rm4nU9zqHdIEdLg2kOPcpvqcgyIglduhrIkgFbff8Ig/U6lSQCVZkdQ8tbLEg2yVU5vQ6vMwYM7XPDlW2FuyJgxYE6gFA7jI00rnCIb/y7j4NvtNLoi7GfUbsj4PB57SsPIHSVaZgPt5dtV/b/JRb8/duxf1Dhixq31pGgHtpk6yRBWbU1Ebr8bOJv4Z8wjwYsK8pIeKj03QbW0yOPSxRBqnfwd51SmAkyAKd0FnsPP05LmxGdVSPH162tFms26Iwx6JdFDx0KqjX9syy/JDe671tZg2vK9ThAfc,iv:9NH25pQ0uKox0QOQsz/EPHEe/80JIDkwIEuQKYq2f5A=,tag:wFT91uOfuc80suMFfsQkkw==,type:str]
    identity.pub: ENC[AES256_GCM,data:nLKxPmNi8+Xz3fHWSmvyWIYuW8dCKSKT2hJ1CerIcAFOD0BZDzhljp9bd3R9JXsCTT8S3QiT6PTxcIXgfoHasoc1N+vyk8kRaaL+o/vm7cacLFpBPgfWM+Url2UV4yTnXVkEp6JkyMNNRt/kpG4haNiBLwz4XXH7T4Vsf1B37yzp8aEIAAJp4FJjXBDb/FVL+S0RyYcoy+dtnWoAwI4+ED8ZAxPI2yyIGibmRwTp7LU8/cP6/CGWzi/togHGUI2f7hWwmJ0dLtkLL1Gkag==,iv:lKl/yXIT8kwvy7SvwTKSU5lSJ3m8mgAGChNckmnW5tQ=,tag:5TQ9cxY8QdGKHNsGSWneXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:2f6viZGWJKHkgbuFs90IEOB4im2d6hxCDJEPkku3UHH1qWwYuyzNoDKXHVS151FqAPImDRtWBaDJHb7byszUYBbDHrdUuyddza+g4wLlVo/SIx5RuizP/C3+peZ7H5EbXkQxOOaJRnc26bllXk3rqRJTbuGao/1zvKZjngStP6qFme6QlpGnptmTM9XPRsBX5Bv5ODlsntO5OMr6wLJxDKmnNH4LZ7YLMlb4,iv:QeHbxS/zI0IzIxbuFNNxrcksm5sV7DT99QiQsNftfHI=,tag:tIB/2RxnwUT5QU4/hm+DxA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzemRNNmxUZG84ZlQ1Ymxq
            akd2M1A5RXo1RHN1WDV1bFdYZ3dSeGlscUFNCmMzM01FQjRocGw4ZHE3ZmJpdnJC
            bGFMU2dXTU5ZQ0E3SzB3U3FGTWcvTFUKLS0tIHYxZnBYVTJYc0FONkptZk95dnY1
            YVFOU1JsdXpFUHg2U3laNkF1R1Vsc3MK4PHnARqs4Q4B+SYZKTm7OvczeUxrWKM0
            A7zcKjey58jBvvjsg1+wsCn2HBIZYAUTrcO41EGNvgIVgp6ndXn/tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T22:46:59Z"
    mac: ENC[AES256_GCM,data:E5CJURr+PfxtkRAn3joxmH2zyqMfcpcVYZKx7GoZfC05rOoNiTTgzJ/9UBzwBwVIU70wqshwRGZls25pSGajKnvBLx3CBTFguW6XPAJo3VexPcuaJp8uPSVGeIE/GOCo8iAX22iicN/HuA1+j454Z/1zTPWgs0WGMfZD+1isDE4=,iv:fuXNT3TuaANZaOVyEUxxt6KFOkFLF1xGQAHjAacLYos=,tag:t0PJ531AOZ+noTKhLxoe1Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
