apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KeCFvQALJZzAGicnLGcFZN+PZaF0V4jK1s1uaeoOFixI04Ua6JvrZqRi18xqx7RbLIZQYKM0i+i0BIu8hXu2blcwB0WUpqjIFcxq93yebnLjueqhXt1pQ7+nK+CCowGGyAsQALCsrCBbmGsK6aroKLyXvt/mENhRneGwObg2wapLJTNxB8USfGah/IHv6AUuL9ju4PwajogZ0T4rlcqWh6dBXxsDLxLUMxklgldg7hqmo9KjuKluNS7z/O2CwAvNvs8y2UnaxyQ5+tsYmYfZEA+FNuRQf2LbomxP8HWdKO9rBGEGigm2qya2I51jkXqEDZZr1zkwhmk6596pN//4gxGcil5vMhTDLPmxOZB0z315WjcixEondUnI2LR407PN,iv:srE8EcfgaewClbcJE0TAZPt6aBvh5uzBkasF7Lt/JFk=,tag:2/ZAwyDG780IZn/enZ7lpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:H1wqo0hmVIa5v6sbgnpdKBeQJZYVcFo71VykM//SWLO8d1DdsecxNMXZBhqr/6nqqE69gPVDTR6P1FSSgZPnuwSOndFlcM41tnuwkZ6zxnv0Qd0lAH3NNWVAAf792BDD/IM0MiCDgQPPPI7cz5FMfob97Bm2M05qT4BrfwvA9xa8bNaTmBcx3AHQ3YNsSmbTXGYCE9boY8nhjtvtwHcgszw9yDGbdmJvxy9/4wSPfq/M7saaiUxNu1TZzTz1pAwiKfv38uoyNidxxTVfwQ==,iv:idL28XIN+czJZiOfvR78MYEEr+TKgbuSg35oT37JqL4=,tag:2VvOUKwNFbunVRMPYI+RHQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:X5nv0uqykei5xR1mnkQrxg5nS4pFxXJtsVsNND+k4H9ksSi9DjJYKFQCLUErNKqOMePXONys1Byr57HKk6grkCkfRBGkC+1v/Kt+CBfmXLwhGSPqaRcmBqZEVAKwYa+eaRHpxI5j3iDBKfzz/tCb33KI5C9vS/TmaDFJTB/wsRZjhYC/tj4IvSZsWmrEyiSWO+J84w7CdRm4hqwBXDbo1R9VB/z5xZltL/Ha,iv:ffMLon0bU/ndFjYJfJAUGFs9xDavXpb5MYN2gPmxLFA=,tag:X5B98A/F+V462Q9Ub68q7Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTit0S3lZZ0JycXM5aUFL
            TTQ4eGNra1dnaXZsa1E3cmRhNXdESHhudlhBCm1vcC9iRmp6UVNEUTkrV2hTNXR6
            YTY3R1c3eHdJWlVDS08zZWJNb3NrZGsKLS0tIG5YOXJwdjBVNmM1Y3krcUxXWWg3
            N0YwUEhubFRWbDNVZG9kKzFuYUV4U3cK5e6olyO9xPbYfy2i8FBVAb+rtYccs2/z
            EqwOYXR08M4rOpxmxCrawzNkVK5/cQvwEglYhu2UmUf4cC6+AmxOhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T05:18:14Z"
    mac: ENC[AES256_GCM,data:MZWK0dQgFR/TlJGUNw/dKhQsEcTNP9bg3+FmXulHeEmZrEXqCBVkd79Ek/QuSRVJZvA5TuokOx2PfeggDD0Bv2KxA5yfLNBGhVk1EAFzA++PtF+2tv2HWm2f21bcomjSPzITY5ga8C/j8FcmplKts6r0dGjNtUyerUoLcAIYpE4=,iv:tDHhC4zjP4qM9+Ff03qH24gKp/BDkHEpUZ6Pe6XlzJ4=,tag:xW3gGynvYvs5Jhno8hG53Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
