apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1a8zvKQ30Mmur5Q/Xh3BW4mTw82sS2S3tK4IHBFmRXKNk0H6dQPwLf78yp88qePWELIQzN4AZbDLxxAAS+eWh6NXHutGZs70WgqydFM0P8g1SOKlAfujfsj8aM3kIw8uqQkZxC/uDRXElRkcUeCBT7fBQivvJqprx12R9BmIO6lNKHE7j20Xd86AgkSllkL2PFGZ0v2W79IHy3RWEheSxpVLUB6lQ2zEcYmH9nzxHg8NEV6ZzNYqaETZJHThacAqhDUo34lbS2MKHtYCpYbNzPlTQiFyf0+1WwOfI9wFoed4A93/xXXtMfD01QlwxQN2Ut7vtjmo2Y+rt6T8uxL5/3r2lzKL+FE08ugC9sJbn4Dy7pKpLVR13haNhZ2CA3n6,iv:5aVwt6OwVbvFNs8bWXO2f7sijIlh4uu4S4Xe7XzWSRQ=,tag:8tWp1K6Hf1v+nzEocyHAIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Jh3CODSvw9OWcFthcnpPE2OP+c93omwCXIdhoeTLWbPAwtVfd8vezIk0S8wq8QTsQ3bnTplHpFV/srDWpCZoTTZC4PJdrh85v/fWBQBK0V88O4MR29UH+9xQ9Vt892jDRy6eofX96HfVO+tD/2I41bAZ4yRyK8U/SOLBZzKyaLE+rWbIhk5EGl3kV2LnX43e8m4ALsV0qjAIrBGS+PSmALXEydntrW6d8BzUrrDCIsdSc3pYSylfaXcBn8AObNmTvZB0PE8oNHfxsfIjqw==,iv:irtRkEqUY7XV4p19vKTyj5+xeYXWOArb7b7GvWtedCg=,tag:UkMCe71efc4SbPJ/jUTHDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:wr52l8sDclahwK7M+HYj3kmpeVg6+aQ6uteWX6nHo4k5NjyoEOTQIDchnDdmBk1v47HgSlFJR8hscxO+2DAoyys1MUB/g79AKnq+v0PWYOp7sXXFGTP3EoSt/2c4h/zcmHtUBTZdSCMol/yGFQi2/+F5hqMLt5hE+auJQfAMN+Tov3VDDfMgAxzGYRNtflVZeaLFzeKpXgPorus+j/8+NKFQu7i6gwtjJrRT,iv:pU87UxQbAWQdZznIEe1uAOFuqVc+5hkY5lRGndc5Eao=,tag:39qQ+tNmbCCXQLgoqY3Hfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUk53RUpHOXlXMXNydHpw
            VGNOQWdQbmNUTGtqTlovU3hmYjhhZFhMZVFnCkY3b0laVnVjSWkxdGk3emxIMDE3
            TUxMZGxFM3Q2dXpPK2pNUG5EcVR6ZVUKLS0tIE5mNnZUUHZ4cC9EWDR3RG1RTFlB
            ZkxKRmI3VnNhYloybjdjSXpxdWdVSHMKXOW5d4pIIOC7Efgx7N58N99xRjP1nVGG
            qkWfmi7boAhf91S/y/KbFDUrvpT9vtBThAnAlrTkeXOAdLLp4f4NUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T06:12:29Z"
    mac: ENC[AES256_GCM,data:XRT48y1mS4TzFGxmfWRzKppGQHzpUdo+/jLabpJIQMzDO4zZLu+Ku0liuexlDUDwc0H9UR4KPID7JwavRgGTqAIwwfSrYN/WLLkOWe61WLziky6QA266yCqBCtRaEWBhtJnMHZhcxmgWMj2Q54PAl4/rlYuvxF2L3OkP56fA6RQ=,iv:n+edg0egFeyLTNV4PN7OP8Jl4ByHlh5khWIWCQy1EEk=,tag:dySkGNwhqv1kWZzlhMKK7w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
