apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GyUCsJaorDHPliFyHXAPL3FgCJAIwhQrgKRn4VdCbX6TawTn/V6u4tNaK6AcvbyAYenxnJTusk1kLYAhPjz3M4LyXnfd1aW2UJnglJknpulxu7dabLeruZGAUjda1fVVNg9rkPPWJh7yTiDaHf2tETib1itah8COXMr30x3U90kduGWAj0i5RlUnfXCOqRZnAZAfIeHTfl7ZlJwV8my+dThavYdvu1BUicgNcOV4ky4+5/pkX0UIG7gnrJUjtmqREUmQQb0U7vUR/VJBtX9L4qApI9BrYeKQkDZ9ifn8H6dLCHZoC6X/hejvUstlq9Td1c9sM5MLAgpPHcSMkTZNlcChwCyaZEtS3zYHjS1GrjwdkoTb+y3tqx58te7gt5Mw,iv:aJpn/4HFGrOysnTPzrkxsSRtqdgYdbwFIftJcPmudWw=,tag:g582jZzp3AlUGcl/vCaHRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:mCAywAVBTGLWN+NwGwx9gcF09T8pKIwUOMnKZ5OBWfjOwaqYYilSEPwZvLp4TpIAvHtdSrAIaiqXjmMQuKGRBttugKKnKoxuZuvRG2PCe3Q1hEXxCr7KvvXK4dKsophsNI2f4pYhfiTuwrYDxoCGkHVO+OE6oH8BzoJMgk3keBO+yN2mJNyksmJB7OPEUg2mIa0NgW5EghYVmGkEJQ5dE/XQz5jzPrmISLo0tmKmlaTAUxagyVznI+YJwqapzPY4gDEvonXIWH/4LGEt3A==,iv:6LRhw+eRb5IGalCcA1uQyvjhfs50eeWM/wRT7x4SNtc=,tag:qE8y25e9E0Zq0Euc5OiGHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:zEXa3PE/K025kXaYbET0a6FyNpF3N6q2SxOuZajon4rQ9gW0Qwh0ctjXi1TtpUWKWgz8phd68FkqyA9/OE2XJcsXk3iqMUF4+l2uKkfVh1bNbOfkG65N5iL6cxgnXKiqLb5RJ4kfgMDJj8Aphtc89ttr3o/gp3in0qKvXelo3JfCDW32ojDrYjFMVUQ+e9W001b4YR5iWWGFlEbhrbrJHbk6M6PflF0IL14z,iv:mtTPwITyUqEiryCJB93AE/mf8gk3Ch7SpiBJlsMJLdo=,tag:o7PkutQ7rMUvjBx1FuJRew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1czpcah6tm5k73skjqelgq4j0xu4wwwqtcz2rkhlkdp0egf3pnyeqxtlm3v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb1JSbkZBYUJhK0RXZWRp
            b201ZE4vZmhsNFUxUmszUUIvVjFUa0h6dFYwCmtLMVR2OW1tSXhsOG9lSkluOTFr
            QnFOOFV4eXZNNEtBMGg3dm1wVU1Dcm8KLS0tIDlOY1ZjQWtjeWRLVEVEb2oyUGlj
            Z3IwNlNxcndxaCtCbU92K1pwbUhOaVkKRoX3DC9VYSVYv964XaLNXl+LuwWAWkKY
            wUzlRZr1GN3Ts9i0H1/az7wZ4byYCIuIIe1GB9yDByXJV8g9Ll000w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T09:21:01Z"
    mac: ENC[AES256_GCM,data:K/uLg+AaR/OKowD0hUiAdMAr2s/zHBGDNz/tzLdM/XSFO+eDQcoCPBPt/hIFm36WRTlp3v98Odv/+fhTbfzj7j8Jo0b8alhUoy7Dlb9OTN8c3BQk8LG9vx/DK7IltcaJFMK5twZveu+w8zMJWcM8ooxj7JxdohkqYL5UmWZk6xQ=,iv:qQrAnfR6gCRm0qY4wEXcVTYB7netPLSTo1ENdABiaHs=,tag:WR7KLh3jMpk0FPW+8tI4tA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
