apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B9dCjkSEqo3eDKgebk0qqPm5fLR0RtDc5r4oeq5oe+obn2RbkW0x24TnaZ1oBWEn52wA8sA2+d85fzpG/xuaUHOJivvyDJ7GUHjGKF1+WSnxpr3rjvPzCiPnzKoY/A0CyqaweDy19lkRYSbN8WQE/fbts+DTdzfQNE4zsEx7knWWS1Mw0yA/jK73bofDGmfoM27LAPR/+Q48n62NGVXX2un+BtyrdyGXm4W0UAwAIPGUI6Dh6NOgD7HUNcAqZjlP/NOCX2gVCetYuz9ra8EEBNlw8OOZMaVZxd3pMxZwHIMxBsQKVQrG2dnrD6W9Ns6iIHhC7hn1+FV1zquwNtozBjJHIP0C/P9GSAe/uXyHEWEYxugeUF6I+858FHXElzkB,iv:UJ84hBxA6Gk2sNYmrurHAoqbc8XwhzcqtxeJsiA7adY=,tag:z6XorXWlQGbtzn3ykBab/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:/7lm+/okZGhB5R7Wu/cX2oKvgREpqPpkniGZfE8ORWwTnjyjXfI3j39DGid41ZdYjh3S654bIO8KuONaVLELWnimmDD+ySjRbzPLUDYoCbP+r8pZJOPuvrC+niE9P088fJAMLzTJZQBIemQR+KvttvHwIweixr8buLYekuDmIwI0RIS1rQJWIpL72fKChyxfcfU+AaMUCD2+hTD1hQxc/Qz/7hK+ilOLCNTLgcQ2KkpWyUlbAfPHnGVcgpLeQIdMVaLde+FBAPJtivejnw==,iv:3A04RUCMjsncmS2HevuJnTb7762cnG2+DLtOF11F3i0=,tag:+FM1Xjgos1aHta7u6timow==,type:str]
    known_hosts: ENC[AES256_GCM,data:CBhOh51eNMKRe1isReiK49eG8M4qN0mFll7FZ3wlZ/wePCHKjo4b8q/RloKa+1hiiWkzOLML0ZP4nppvBQOqmO41cvcIVM4nDhoAqus0MJtkhx2HJXz4w0xUYufi1g0wpMeIrZpnWJQiMfm5OuCt9qFPy853xdMSf3co2+GU8tu5TN/eooYOjc8z9ePUi12bwjz9DV5v2SYvFhZsvXuT5t028++YrcVTND0D,iv:zMt3Sf24snS57N5HJzYSE52JaFo0g8fdn1BQOjxiN9A=,tag:FqI2P/Ld+1rnUyB8SB8o2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YnFkRjErT1BSbU9vdis3
            aWd5ZFV2UUtIVHEvMzJ0SXNad2YzTVJ2eGw0CmRsVTJ4RktXbGxReWJ5ZGJtSnRa
            VEg5NFQrS3kzQXZ0aTZJVnQ4V3ZMd1UKLS0tIHIxRUdTbTlkVXpNVk9jQVZmaE1l
            a0ZkejRGanovOEp5Zml5dkk2Z3pqSjAKyWWe3Lk/ZLorqQoVMSAewY4UuUDbBDiW
            lEdal5hfeAI8vED1BNQ6ALFpSJZvw7OJY/iM+h2GxsuusXc4hshHiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T06:13:58Z"
    mac: ENC[AES256_GCM,data:mBce8blwODhtZbSIf3fwCZPbOaFm6yKHx098aNVt8/k+5TTxjofULJY8kMCRJmOsfU6HklHgj2QNMCVAv3iz0Dx0n7y6yNTWskqDB0sPjoPhnit3TTbYtloZSrU/DRvOfBFFeb2SZTZsdq//NQknJO7jbc0yR76/hpRtZkKqVqw=,iv:JZxeGDQP41us+MneEG/jpIQ6074OscK44Gk+ktgxiXI=,tag:HdTZ1WLe35tM+B25tzBixQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
