apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u3jky63BMoKbpjnLAZ39hK9hm4cVnLEoNX5qge6cK+7ir6GbYP8XzbW3mY6eDN6HtoaAr5jtIRbuRLrQvrqLbuT1SFBGIAIUx73UNPkb7rTE2g4tDV4jAOMGTJ4A+SzLuHwzG/kJkOYrv0l5mWhW+WHSjrd6hwjSR/IT1mPrNGPYrLdW4/QHbasRp1lAt1pjf1ZIZCD+8HGLwmihannTtH/b7CTmAH5Eo0vuhoFH2JSgWMhMoxCNeW67iaElT0gwx30LA6bxS2Ikx6pxlMLJc//VzND1Z8gAoZbt5Bp3nLb7/FdycFTwE4LIRsX+Ch+/3c5Df0naYjspJY63hJ2ESckJraGIiIkfCHUTPUeXk+MahxxacMvZREbWXcPcwUXa,iv:pwX6gkFO7LgluIshwpFq/N0URQjupEsq2e9MxpB5mDA=,tag:FqtjQJJ0GriQGdfigOOTDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cokqoN83jmq7pm8ctAlpWKBuOZ5ic/od4O9ldJjxuuAA2DtAqQPdGC8BRlB7Ichpy+HGGN0sy2Ms85Qe0EN02jlqDEbVU70pVnbZrdKLvMHmqy7AOzX990jKBz6rUEghrcbVdpICZisEk4ZUj5Ga1fCc8qocQGFKbJdTZK3rBCrcBmyvLz58gNcJAT6QoMkk9EGVVPEJuYZOdaTLAnp4D3JpkNtDLrXk2P3MDgy7iFrnEZKkDpGZbV5lrgdoeR5HB0FfGbjR1Hsv5GT3Zw==,iv:uUPgQClu9yLnoGWPzuW9tbeCx3N6B1kzEt4jt66KB7Y=,tag:DUCkfkMjVNoe80SflqvnKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:FwI/NTPfm2GjkvMc+p9Nvqtanxmv9cyURmV1xYADF2ZkrzCrBQ5OUcIGpxQnVpx2yeoZnnDlzwMI5dtzFuwL8K4EVWneTqH3dNpe803M51b0lLbDQ49K9v1j94VGXuTa7kQLUO4Pe34krNC5kvjesDfn52+rUvAJyxhbZzi5cUjrK1SPYCsvlzBFbOBlvym4rIyzz3aix9vQs5XvbvLCevs32ueSnF970mTm,iv:NkbtVUzAQigDLYLV7tyTNyICycIixZiTrIFNPOU+mWg=,tag:WanfAMF36Uft4RqapGN4Lw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKazlzcjlGNWUwN0xZVlZX
            NWpiL2hCajRlbHJ0dWNzaVFtQ3FRRFZIUmhZCmdoTURPMllPVXQ3THVsNlZIZFYy
            YzZIWHdybzR5aklCZktjczRjZ2hmUm8KLS0tIHhhbXoycWZ6N0oyYWRRN2l0WVBu
            dFZWcEc5OGhhWjlVMUhRWWJST01qcWcKcZOYbTM72BWxc8lusrs0keiDtDbh+tcb
            GJJYS6yL69qwv0hNfGG1g2eI8hY137S7kEgQOGVyo7igY/+AO+nYRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T05:25:08Z"
    mac: ENC[AES256_GCM,data:uCRMc8Jn4Fsi5iITNBMK9fdQw/gz1lUeiPZN4K1ZTRXz3vHGTLTOHuCWkmjHgmQTFIzNgON8felDSKmERCU/N6ut4QM5M3iVTXhGHFZwAhxKUmrSJXFk90Th4IYZK4W5PHBSQnpVn4lywvve1TUm2j1Vmn5jXJrRsmzAPTIrONw=,iv:EtZCEa4NFimimSj3sosvT5XMS1gkwUJECjNLA+kuHKY=,tag:J2fsZ/pZ+F+cBG1lGsxgSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
