apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ywXRlq5W3Uxrwx2tghAlX37JB6CqdXzAO1hmbb7Z/lXGPKdV6yhvsFj6vaSllSwgQWDz8j5wNtqbz5kNyunJfVes1+KMzM65G6OxQpDqhee6WBKvvFC+9sDOfSMXEv9JP0qHLQHju3dVIEoX1gqqSkEgJVB5966KN/GII6aDzqKfH3KoTbXrewE1DT3OnEWYYPgclWpn8QOMJGoQkcJUAIUNOZGA34iL1af1hfHTUgAruEhoptrE7maTL6B6hXz6rqkKy1MCDHazPQcI0otoTcR+vnS1P/sI4q16BsvdqKQCL6tXScaH4Xfo3kRLsd7jOSnvdvlvFeBIOf2KTS8GYJFynTCr7YCzFdfJe0YwG5PhodSW45pNjkDmwKAUpuz7,iv:NJz2H7cDbd3eDNW2OrDx0fHkA3v12dkPgokUIk8PNWA=,tag:LF+YF7l6GrFzWa4GAc7wEQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PrSzAPeoEFMoEoW7eZfiK/w/ro3BRe0HdMQPR755OfLuQrlwsh5o8wz61lSBEiY4N3YpgiKDmm5qL47EAXVqM5a7VRl6v4Z9AKPvsaIDtq1Hq6nKCBMbrmqx33q7sLRtHSjwUZ+KJRMDTISgorlAYr9uLRzTW+CPPLe1zPX4Wu7ie108Wu7IU2HMcqLARwKqQqjMCuia0aJ2DGDnTPujEGBKA0T5wOrf7q5hai3qfEgAfq8yLnSD50Plp2AotUGhtudhELxzruCxudZ8Og==,iv:BAyt5fbOii52fvA+JbDVRVDGZYilBCzk14zbEnNcKo4=,tag:x+2QbvJgRPxrf7ERQvWmdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3n20+Fk0A1kCWZm1tQqP/DaBcNSP5zDE4cdGbIxOIaEkcSJsObrtgkcCGI7c8Su3zaaDDdBo2hrpyuZ5Kjn/o22g891CUVo1gwvAU2Nv/xNPNueWZKk0frSUeOUKS2Cm1Ut/LRf24HrBf7kGY9T96naogxujyF80qiswoRi0bkv9F1agQ4g3OdHPXXcdEuThUQjLYvz8prE9OQqleL4+H4RwjtdTDCJxERh8,iv:XlTVU+DwzK2ZT2m/hKTmQWF3I6wIX1sbNhgvykfVD8o=,tag:kbvAkCiYNn0fctwcsoJQeA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UTROTHNDbWFOckpFMVBC
            bU4vTTh0ZUE5YWNzbFA5Z1RzR2NQSVFvM2xrCk4wbm5JUDJJdnQ4Q3JYVmF6YUtN
            ditZQ1dLNlAreHRtZmVMOHM3WVJIemcKLS0tIHV5UE56eG1NVkk4cGZ2VFRhSlZI
            eC9LdTRndXJsYzhibGhYbGlrb3hmeTAKAvoEz3uRJdIHoQHwcUXJfGnb7IAVaJ6a
            Ql7qOa0zBMpb6hjf2GI5H9WbAMq7NcjVOm7qR7s7dXvquE/qPBdhcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T05:56:16Z"
    mac: ENC[AES256_GCM,data:Z/yYQaFT5NW5Kv3HAKLTP1WpdbzR3GVOc5x8zZVkIrlB7wLEoTrwZwqhk015xIvfMf1Gvdwa0kiQ846fS+nc8ZI2hinvWfbJC95tfijg0VWPf4oXhjwffl1QNh56YL9yB8v+FXBam4GQnNzt6856HGtmOFvpo0ZFVyubjQhWhqU=,iv:KLxMTUl5K/r5DeHhiV/d1g2LoHsIqjDblfRmZX1G3EA=,tag:vny8E8E0tEKt3akJhlP7Zw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
