---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: dashboards
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HOMEPAGE_IP}
    ingress:
      main:
        enabled: true
        annotations:
      # Example annotations to add Homepage to your Homepage!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/description: "Dynamically Detected Homepage"
          gethomepage.dev/group: "Dynamic"
          gethomepage.dev/icon: "homepage.png"
        hosts: 
          - host: homepage.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          traefik:
            enabled: true
            entrypoints:
              - websecure