apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
    persistence:
      config:
        enabled: true
        type: nfs
        mountPath: /config
        path: /mnt/Applications/apps-configs/jellyfin/config
        server: 192.168.30.49
      transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
      family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
      movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
      shows:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
    ingress:
      main:
        enabled: true
        hosts: 
          - host: jellyfin.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          traefik:
            enabled: true
            entrypoints:
              - websecure