apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media  # Ensure this namespace exists or create it
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 20.3.5  # Replace with the desired version
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true  # Automatically create the namespace if it doesn't exist
  values:
    service:
      type: ClusterIP  # Change to LoadBalancer or NodePort if needed
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "default"  # Replace with your storage class
    # Add other Jellyfin-specific configurations here
    # For example:
    jellyfin:
      adminUser: admin
      adminPassword: password
    ingress:
      enabled: true
      hosts:
        - host: jellyfin.yourdomain.com
          paths:
            - /
      tls:
        - secretName: jellyfin-tls
          hosts:
            - jellyfin.yourdomain.com
