credentials:
    backblaze:
        type: s3
        url: s3.us-east-005.backblazeb2.com
        bucket: hoth-systems-truecharts
        accessKey: ENC[AES256_GCM,data:aMJX4HNOp1ax,iv:UEaIgYpSBRJin2DVoCpOxPYVQn4oIn9SA09xqxbv/5M=,tag:fV9sEGDf7AP6A4p+2CI8Ww==,type:str]
        secretKey: ENC[AES256_GCM,data:E/8MuNPdIUoFp7Kb,iv:RXMv/9IMoQLIFZT13MYdg2iRroP1xPlMlmzFq6VTjbc=,tag:vKFFbecDaIwqGy7JYaRWCw==,type:str]
service:
    main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        JELLYFIN_PublishedServerUrl: jellyfin.${DOMAIN_0}
persistence:
    config:
        volsync:
            - name: config
              type: restic
              credentials: backblaze
              dest:
                enabled: true
              src:
                enabled: true
    transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
    family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
    movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
    shows:
        enabled: true
        type: nfs
        mountPath: /shows
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
ingress:
    main:
        enabled: true
        hosts:
            - host: jellyfin.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        integrations:
            certManager:
                enabled: ENC[AES256_GCM,data:ifb0ww==,iv:qkE5c9okisXAw5og3Kde1JtsAOxrurdSlOIkmbjqQXY=,tag:+vJmxhD4CtzQ2aj/d/91sQ==,type:bool]
                certificateIssuer: ENC[AES256_GCM,data:2mAxc9uC/TpP5Pgpd4/ZJw==,iv:au6TTorxzgSQQAowGE8QrR22pRHVfhVkOjPe93LpYMI=,tag:BIXLQQ129fbU/wRYkEqT6g==,type:str]
            traefik:
                enabled: true
                entrypoints:
                    - websecure
            homepage:
                enabled: true
                name: Jellyfin
                description: This is a jellyfin instance
                group: Media
                icon: ""
                widget:
                    type: ENC[AES256_GCM,data:No1w0lm6gkk=,iv:wP/eZQYxB6ZU8LugZvAkk+S+ZxYi0nIRvlzT7evimm0=,tag:cjqEq/vCkuN8UckZ3Kb3aQ==,type:str]
                    url: ENC[AES256_GCM,data:PGjq8r7IhevXXQIzvfJl9bhw6qPD8BLaCMYBWBg=,iv:VHgi3A2XfEoX+w/zkjQSZ7uWe9xdIi5FqatJGENET8s=,tag:KfZURQD54kl62SAx4y/Clw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dXdwTkMxZGI4d1Z6UGdW
            S2VoN2pERWU2QndSTEtqdGJUT0ZnWjgrYVRZCnNsanBOOWlzdWhsZG01WjNRNFlS
            em9iL1VPajhTSHdHb0NCQzZPNDFaakkKLS0tIEdyRC9ESTNOeUp5a1hJQTdnaFBm
            SVJsWG1SR1JjMUJPVVdqYUY1d2w5ZkUKkexx7PqLl8PO9aF/AUhFjJjWScEl03I6
            CJ0fNSmHsWV/Ihgprq+blWdnMHOg/eeQl+JW7XKq/1g6m8FnlkM0oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T18:26:59Z"
    mac: ENC[AES256_GCM,data:7OminiJKwUXotexvwh7mdLBmfK9PbGW1Wbm6Vc+1xBg95CS7WxKLfew/q+I3gpWMXEeI0JL0txKWqWenm5W12h75CkWVxj2Oy8RVFzvPqm71/Og1aNFDqegf2Nb2Bqsg4QaJtuo4w7FnIKo9sxcpeeR7UpXWJjTm5cpyiXsBzHc=,iv:5HctUnlcNQ2GGrsXDX8iaYFLerkc1cQD2v8w8O/QfiE=,tag:ePwN1iv5C3yLSULhYsPgMQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
