credentials:
    backblaze:
        type: s3
        url: s3.us-east-005.backblazeb2.com
        bucket: hoth-systems-truecharts
        accessKey: ENC[AES256_GCM,data:fmK6AM4rlnDOyhWN7s6zLRorug==,iv:Neih5DHBAtRg/eBiPboRlfF2gsZwMMawwnX85cjggHg=,tag:HZeYBhU+Gm8D3SnQCL9u+w==,type:str]
        secretKey: ENC[AES256_GCM,data:Tg5ubJCC1ufOcxUD0LXK8NBkRw==,iv:Nn8phMto4yK6o9A1x5A5s1GfDwYCCyStfBb/0gScASc=,tag:rJ8bkQi8ux9qdZJc6Qon5A==,type:str]
service:
    main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        JELLYFIN_PublishedServerUrl: jellyfin.${DOMAIN_0}
persistence:
    config:
        enabled: true
        type: pvc
        mountPath: /config
        volsync:
            - name: config
              type: restic
              credentials: backblaze
              dest:
                enabled: true
              src:
                enabled: true
    transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
    family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
    movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
    shows:
        enabled: true
        type: nfs
        mountPath: /shows
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
ingress:
    main:
        enabled: true
        hosts:
            - host: jellyfin.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        integrations:
            certManager:
                enabled: ENC[AES256_GCM,data:owpnWw==,iv:/6iWWlRZrrl/8OxQ+QQ3XULLYBr/9/bavBZfoOuTryA=,tag:qTVxT0+R0+0IyOpPZ1R8Qg==,type:bool]
                certificateIssuer: ENC[AES256_GCM,data:nBjlwUaot4x0XH3/W6uvow==,iv:luEYKzh5U4WJCzzz2NS+T2EaiM5C8YQ4lDS/35QkJjo=,tag:9dSBx/11v3YZTLB1eLgGgg==,type:str]
            traefik:
                enabled: true
                entrypoints:
                    - websecure
            homepage:
                enabled: true
                name: Jellyfin
                description: This is a jellyfin instance
                group: Media
                icon: ""
                widget:
                    type: ENC[AES256_GCM,data:YtwkT6kADww=,iv:ZCyY7jMx4K8vPIuzJeuUsP3o0Mr0QnfGWQ1rIb02kHE=,tag:pY8gU2RkHfdG9VPaZZxmiA==,type:str]
                    url: ENC[AES256_GCM,data:P4KKRyYh9EbcGPq0yfdNNSEqOfaeivXMz4GshIk=,iv:rnVrbGTuUXe/zPBcd8MoeDVTQnNpGL8ne5kuTQn/tSw=,tag:aGngJ2iHqdOglkWwjc3fIQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU2h4RzVxbmJmRW0rMHBY
            Vlpyd3BvaFNIMm4yNFViS212SUxiRHZ5OUR3CjJmNUxHUFY5MGhQcVV6UXowOEhs
            R29ERGJMYTduSG1qKzNQK0s1YVAzT2sKLS0tIHRqVzBHT2x4VUl3MzBQenYyQVVU
            YlFyUkhWY01ueTN1aE1UU3c5azlVWjAK1somVgMTyhM3p712kXaiZG1DVfNJC3yv
            fCe9UKLgqJ02G1td8VIqiAPSoTNqsx1De67Hcs0v0p3ia/wyi4Autw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:18:51Z"
    mac: ENC[AES256_GCM,data:Rz94vpAp/994Sed5Vz3ts7OgWypxPMAGy69a5YIiVZweO0xMQ0u6g0F/5hRjaB6TkKXrco3JzNDsGia9HEMLlBr4ojeg/3vSPjUhFhnG0qtb5Qbs6slxHNnL6dk9wQ0YjCoURjOyXQ98DrHiPtly3IRM7s2pq14n/zlGhaql+8M=,iv:zrfnJOL/30ACxc9811MSfxZCRbqn7gW38L4PusyJPvw=,tag:CrTM1P5Ts/f1KLY7wRk7oQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
