credentials:
    backblaze:
        type: s3
        url: s3.us-east-005.backblazeb2.com
        bucket: hoth-systems-truecharts
        accessKey: ENC[AES256_GCM,data:ma7DSlUIIesZQ2IpkqB6CSlN9w==,iv:ia+cAESWcnDfA4TnzsuSVg5qAlklhISTN+HsBnJ50KU=,tag:ubYzX4sOH3stb58Lr6Otww==,type:str]
        secretKey: ENC[AES256_GCM,data:FX+jQ/Xjg6ZPaRfUfAB9l9VL6w==,iv:SBrPHmbiK0s66hM+HaBARGuRsJFQNPKa+cdWwSfNdDs=,tag:gXD8kVk+fhqHAG6j6YdlCg==,type:str]
service:
    main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        JELLYFIN_PublishedServerUrl: jellyfin.${DOMAIN_0}
persistence:
    config:
        enabled: true
        type: pvc
        mountPath: /config
        volsync:
            - name: config
              type: restic
              credentials: backblaze
              dest:
                enabled: true
              src:
                enabled: true
    transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
    family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
    movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
    shows:
        enabled: true
        type: nfs
        mountPath: /shows
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
ingress:
    main:
        enabled: true
        hosts:
            - host: jellyfin.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        integrations:
            certManager:
                enabled: ENC[AES256_GCM,data:kG12ZA==,iv:Qzxsg96gNYMUfVcSuMl7gfWf77/Q9e/ktp+EZrHzPyQ=,tag:idTIvw58azpSwvYbsXca8w==,type:bool]
                certificateIssuer: ENC[AES256_GCM,data:38JQA4eq3SimGiHPNTIB0Q==,iv:fww+Z/t9RfVPuSwfPlFWjqfg2oSsamxRR11VYpKm7Fc=,tag:yBDnWEBygaJEvvam5L1zRg==,type:str]
            traefik:
                enabled: true
                entrypoints:
                    - websecure
            homepage:
                enabled: true
                name: Jellyfin
                description: This is a jellyfin instance
                group: Media
                icon: ""
                widget:
                    type: ENC[AES256_GCM,data:jIwQ4ksqu5w=,iv:PjwEf/yyjPVanqvZ8r5EnKBavEyYDy/VHAa46HXSMzA=,tag:/aaftT1r3DLljzdh/60zHA==,type:str]
                    url: ENC[AES256_GCM,data:czNg9l04WioiA71sfCdArfwd5oPbV97CpbjqE7Q=,iv:yjrjDx2DtHEpYAHFT0puoYiQaAcLF1qPMR2x7Knabw4=,tag:eGA9LcXjc9nk8+2r5az9Lw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b3FzRE5NV0o1RHJGRFRt
            YXBtMENKYXkwd2NMS2dpQjhBU0J0QWsvbmhJCi84UjJoVW9ibW85RVZDYlVnekpT
            aHIyaC9sTUNId2RmVEFqWm5FK0h6L0kKLS0tIEdsb0sxbVhLcGlaVFlYYmVrYm1w
            WDRzOXA2Y0x2RmUrcmdxQStQTkdGUnMK5SL0PUINUlI5+4Td3Re6eGBaj9rTjR8e
            tBK6UtVrvC84Wg3nL6BAoUsPosIbHR9pnCEufmQT7yHh109RC4zKtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T18:46:26Z"
    mac: ENC[AES256_GCM,data:4PSLFx/E+FDkrrS+43fjN4UpPFq6VzpK01VLfYEz+Y3SolkuUs7mShjQY0gkt+5wv06BprqjvpGY1IVoXEx9uoo2t4nwwAVeTxUQPxp/vy8IxR4TJSZ8eJ0frgr60MWV2+wIl4JEroIZUMWQ3ECNXjVcOck9X7Gp2Cri5ah1kJc=,iv:Px6mm1YfQzL9tsy/9j20R1o0rA0iqZFxVw05UezeQHM=,tag:Fr0Eg/jPsPU7v5tQrZk23A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
