credentials:
    backblaze:
        type: s3
        url: s3.us-east-005.backblazeb2.com
        bucket: hoth-systems-truecharts
        accessKey: ENC[AES256_GCM,data:FbR2Zcz0BHhVHlAmSIf44m9D+g==,iv:RhOVdAzUtcVZ9a/fw7lxiPL451rfAY9tc9u2wUWJiK8=,tag:jk1M9lyG5s2NGGs6/6VDxA==,type:str]
        secretKey: ENC[AES256_GCM,data:goav681Eq7UpMuDhQcq/kfTu/w==,iv:+8mGGKQ8HsLYbH2ti0fYaXfkxZMD+kMEr2mIPMKdYqM=,tag:NA0Kc/c0tyjGHLxikXvDzg==,type:str]
service:
    main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        JELLYFIN_PublishedServerUrl: jellyfin.${DOMAIN_0}
persistence:
    config:
        enabled: true
        type: pvc
        mountPath: /config
        volsync:
            - name: config
              type: restic
              credentials: backblaze
              dest:
                enabled: true
              src:
                enabled: true
    transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
    family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
    movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
    shows:
        enabled: true
        type: nfs
        mountPath: /shows
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
ingress:
    main:
        enabled: true
        hosts:
            - host: jellyfin.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        integrations:
            certManager:
                enabled: ENC[AES256_GCM,data:8nLbhg==,iv:5GsMwlOU+3Jw5/Kbno/+CtBJ7xJpe8dZlSwKvEDfCcE=,tag:rWu5u18I4oDBeGS+w4EYhQ==,type:bool]
                certificateIssuer: ENC[AES256_GCM,data:J8Z5Ueuiy7TG3TG+5Gc3JA==,iv:imr5/XfqLtecKjP5/Cd+i/TpSJA+0aX7JD3sJWcyP2g=,tag:kS6SqsHQgWANgozq1KnyCQ==,type:str]
            traefik:
                enabled: true
                entrypoints:
                    - websecure
            homepage:
                enabled: true
                name: Jellyfin
                description: This is a jellyfin instance
                group: Media
                icon: ""
                widget:
                    type: ENC[AES256_GCM,data:eVNSqX6KfJ4=,iv:9xdAOlwwzUELVOScg7JW8Lpg83ihs42uwyTpIoFNZn0=,tag:elgNeCPATm/ooDXVcLqgig==,type:str]
                    url: ENC[AES256_GCM,data:lD4BfB6Hqf9IryLDjE7InFSmYNGW8F21+rT3Ms8=,iv:EewcjSVTGX8AbpRmLg++GkcHtdFiFVm757xV+gLTAjk=,tag:0nK4E0QZNrEkqvlXlw5hTw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z3lXQWVKTStJTDFVSmFs
            ZTJ0UGdnSEZIbXRTNURNd1JSdXFaMzI5VVNjCk1BaEZ1STErWlQxNEpPT2RzeExh
            VHBkQlBpLzFua3BUNWw3bEgyT1d3MXMKLS0tIEFiaENFMW1vcklYUHdMVUhLblMw
            bU9LWnlsbjdRRmJrQTdvKzluYkUxL28KCTUc8B8A2aOkTRcpP3MLQskkD3x6+VdH
            qJa4rhqKXm/adzbZPVR8MjetMlsj6gekDtTcsJ0INVOHrBRNAjdGJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T19:36:24Z"
    mac: ENC[AES256_GCM,data:WotubbpxCUtHU2hEUWJWgGdR7BUstlyyKO4uXUn/VeEzJibV5gjmMEZahh0frnlFridrqD2tS1sAmh1xfuzD/O0498dvTnsx7n0Ay3Yj7W9Ejj9pzGL9SZnuPu+zPI3O+lVUxyHMk2HatB01Y6cNCl8o9fjmSS+urhxTreucuHU=,iv:ra8aInWlR4qTKp2lk8XsP8toFOO9k28Q/grlS5tGvQg=,tag:LXfl5aBco2Y5wzvIYCQgXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
