values:
    service:
        main:
            type: LoadBalancer
            loadBalancerIP: 192.168.30.216
            ports:
                main:
                    port: 80
    ingress:
        main:
            enabled: true
            hosts:
                - host: jellyfin.hoth.systems
            tls:
                - hosts:
                    - jellyfin.hoth.systems
                  secretName: jellyfin-tls
            integrations:
                certManager:
                    enabled: ENC[AES256_GCM,data:1y4VZ8s=,iv:D7Jzytm/APNzMvMkUBPaCAUS9CYAO5XDU99LoHFVh7Q=,tag:TzuTf8z4a56M62sWDe2mfA==,type:bool]
                    certificateIssuer: ""
                homepage:
                    enabled: false
                    name: ""
                    description: ""
                    group: ""
                    icon: ""
                    widget:
                        type: ""
                        url: ""
                        custom:
                            key: ENC[AES256_GCM,data:NSkLMIU=,iv:T9OZohB9rh+5LSSSqzrRIwUZXFFj/foVCWCD0aORHq4=,tag:XAzxPsfcNuj2ZG4GQilZ2Q==,type:str]
                        customkv:
                            - key: ENC[AES256_GCM,data:4sZA2RxteUU=,iv:/GC4rw7Q5jL2LTAbMyNM1wKhN71VRBUVZaoeIf0D4uY=,tag:N7FgiZ8MpwnyPDOdwzw06g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19eflpg9n7449y963agj40wcze693pvwu80a2umdd5h573fzjpsrqkwfrs7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT0k1SC9vYU9Zdm80ZXVr
            ODNoRUVLQ3NSV0hESHF1b3J5bUpiaEMyVkZJCkgyckQ4K1REck1jNU5FVk9JMW93
            K0JObi9xVGl6Y29Yc2Jic1lnMENRUHcKLS0tIHQ1ZFZMaUdaSU9SUyt0TWJCaHN3
            NldsQ0wzMWRzS3JCNVBQVWhJWThBelEK7adSITSNJsc6hmPsXCr01EQvoQDXSPiu
            Nz7Ybi9N4Mh/39VrBHQDWs2O11hKrOxUmSUiaWSNjjwEobfDfzo/qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T05:02:01Z"
    mac: ENC[AES256_GCM,data:UGs+0QGs0gLrqjl9YCc5n0evExt93Fv/gTkG4V8VGXwQPiwb6Tx3DdOIqN+j3/7tg995wYbziAFx25V6/v425PblHG89zpdMikejohUgop7BgSvDmiASezODXOY6mq0G7qrfxYFNzfUB5mYjxCHNvzGsm2D8AkHw1H29UnmsQ60=,iv:CRbbwRIekrAnLN7F1XNVVksjRrmpxqWpIQAtkBMFvL0=,tag:IxXYdR39b2YWmosRf3LLhQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
