credentials:
    backblaze:
        type: s3
        url: s3.us-east-005.backblazeb2.com
        bucket: hoth-systems-truecharts
        accessKey: ENC[AES256_GCM,data:NtOsLDP625B33CGJ7nxDxxx5lw==,iv:drqzKApNUkikUTh7IJc+dx5o2W4/Tii1g70YKZLDgaI=,tag:tzrv3gvRDmBdQp8MrXTMyw==,type:str]
        secretKey: ENC[AES256_GCM,data:Tq25wmaTWQgOdYdwn00Mu99IbA==,iv:VQRYDiZGBmxwHzWFNG+pfJbkmrIu2PzX4M8vbo/5whw=,tag:oahBD89Qcwbqs7tGbSgKSQ==,type:str]
service:
    main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        JELLYFIN_PublishedServerUrl: jellyfin.${DOMAIN_0}
persistence:
    config:
        volsync:
            - name: config
              type: restic
              credentials: backblaze
              dest:
                enabled: true
              src:
                enabled: true
    transcode:
        enabled: true
        type: nfs
        mountPath: /transcode
        path: /mnt/Applications/apps-configs/jellyfin/transcode
        server: 192.168.30.49
    family-media:
        enabled: true
        type: nfs
        mountPath: /family-media
        path: /mnt/hhd-hc-primary/media/photoprism-original
        server: 192.168.30.49
    movies:
        enabled: true
        type: nfs
        mountPath: /movies
        path: /mnt/hhd-hc-primary/media/data/media/movies
        server: 192.168.30.49
    shows:
        enabled: true
        type: nfs
        mountPath: /shows
        path: /mnt/hhd-hc-primary/media/data/media/shows
        server: 192.168.30.49
ingress:
    main:
        enabled: true
        hosts:
            - host: jellyfin.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        integrations:
            certManager:
                enabled: ENC[AES256_GCM,data:FTHx4g==,iv:bR3lDvhB0rYXIbP25m7+rAkNDyB0a+aTfaRUoACST3A=,tag:82A04sgzEULU6C839zetUw==,type:bool]
                certificateIssuer: ENC[AES256_GCM,data:KxWMBWufWEQEgm2umdT9/w==,iv:faqNIm+7vmvoMbaejejALwUQiRo+3e4vRc7L8yoHsQ0=,tag:IpohhdKws2yJU/phPEKERQ==,type:str]
            traefik:
                enabled: true
                entrypoints:
                    - websecure
            homepage:
                enabled: true
                name: Jellyfin
                description: This is a jellyfin instance
                group: Media
                icon: ""
                widget:
                    type: ENC[AES256_GCM,data:6I4Uc49QAyY=,iv:PtPZrsvYWz7IfD/VnSQ6O+hCFOwmT5O/F98fKPT4ReA=,tag:SpYdoPEWj0C5W8JsOUJQ8Q==,type:str]
                    url: ENC[AES256_GCM,data:wOUShhZfwJb7GYZ5Bny/Gnytl286NF+I+2+S2sQ=,iv:ypRjZS4nazMYK1h4ttuxCdP2npEY03kDS6Q/MIELlCQ=,tag:AFmiPJLatjN5kCd0zmPsAw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFRNOVl2cG4vRW1pS0VG
            bUlUVDc0eUtRb041TmNleUt2WTkxNlJHOW53CnNUdXExMFBTZGtvcGVqSGpxZFpm
            TGU1ZVlEek9uVjd5Skk2VjdSYmR0VG8KLS0tIElVM3BVajA2dnc3SDBLNmNKS1hs
            OTByMmxmbWFrSUxEclpsTE1DT0p2ckEKDukiQTq+Fko0ObqgJbbqGbLYL10lqAax
            sWqDeoKrc+RAyDSStraMFeG7jv0Xw3syYZlEIhlQOm9FSgHJGEBgSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T18:42:15Z"
    mac: ENC[AES256_GCM,data:IbTaIObOC3Qf5TbKRF0PZ8nphZCQXF4Po/+h8rG92UyWoDatO3c63Ke8dRQ3zQBirPgOMtbRG1FhXpN2fRcvYY5We81A7Jmsyl/JHV0q4YWC6QLuWdAleXGgID/OofELRNtCEuVDlGrpopOqvfuFDvNtAGfZgkNvGO4mS1Cgzks=,iv:CAcaVS18Ic46h8V3dPCtBxI0KNTuZ3kvQ6ev49AVxEM=,tag:j07CYenu3PjjmiFF8ku5+w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
